### ISSUE TITLE
ToggleButton with IsChecked="True" 

### ISSUE THREAD

**Issue by cashok78** [ButchersBoy/MaterialDesignInXamlToolkit#10]
Set ToggleButton with IsChecked="True" in Xaml. Run the app and toggle the switch UI flickers and double toggles to settle.This is only for first time, from then on it works as expected. Just a minor glitch in UI.

**Comment by ButchersBoy** [comment]
You are talking about the MaterialDesignSwitchToggleButton style, right?  If so, fixed.  Thanks for the spot.
