### ISSUE TITLE
DataGrid checkbox issue

### ISSUE THREAD

**Issue by QuantumDeveloper** [ButchersBoy/MaterialDesignInXamlToolkit#100]
I found that I need to ckick at each cell twice to have possibility to check or uncheck checbox if it not focuesd already. Could it be made that I dont need to focus first and then my click will apply, but check or uncheck with one click?

**Comment by ButchersBoy** [comment]
Yeah...I know about that...I've already a very big fight with the DataGrid trying to get around it...

**Comment by ButchersBoy** [comment]
OK...when I first did the style I really banged my head against that one...but now I've taken a different tack and have got a solution which won't require any user input.  Just got to tidy it up.
