### ISSUE TITLE
Need Help- Can't build project/ start new instance

### ISSUE THREAD

**Issue by seibaaah** [ButchersBoy/MaterialDesignInXamlToolkit#104]
Hello. I'm using Visual Studio 2012 for this. I downloaded the project as .zip. Restored the packages. Installed every materialdesign in I can find in Nuget. What step did I miss?

1>------ Build started: Project: MaterialDesignColors.Wpf, Configuration: Debug Any CPU ------
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>D:\\1\MaterialDesignInXamlToolkit-master\MaterialDesignColors.Wpf\Swatch.cs(40,32,40,34): error CS1002: ; expected
1>D:\\1\MaterialDesignInXamlToolkit-master\MaterialDesignColors.Wpf\Swatch.cs(40,49,40,50): error CS1519: Invalid token '(' in class, struct, or interface member declaration
1>D:\\1\MaterialDesignInXamlToolkit-master\MaterialDesignColors.Wpf\SwatchesProvider.cs(91,17,91,18): error CS1056: Unexpected character '$'
2>------ Build started: Project: MahMaterialDragablzMashUp, Configuration: Debug Any CPU ------
2>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
2>  Restoring NuGet packages...
2>  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
2>  All packages listed in packages.config are already installed.
2>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
2>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
2>C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3243: No way to resolve conflict between "MaterialDesignColors, Version=1.0.0.14576, Culture=neutral, PublicKeyToken=null" and "MaterialDesignColors". Choosing "MaterialDesignColors, Version=1.0.0.14576, Culture=neutral, PublicKeyToken=null" arbitrarily.
2>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
2>CSC : error CS0006: Metadata file 'D:\\1\MaterialDesignInXamlToolkit-master\MaterialDesignColors.Wpf\bin\Debug\MaterialDesignColors.dll' could not be found
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by ButchersBoy** [comment]
Hi, to build the demo/source (all in same solution) you require VS2015, as it uses C#6.  

You can still use the binaries in VS2015 though, but you'll have to follow the wiki/blog posts to set up your App.xaml and get yourself up and running.

So start with a brand new project and report back for further help.

**Comment by diannereyno** [comment]
So I can't use VS2012 to build but I can use it of I will start a brand new project? Or am I really required to use VS2015 either way? Thanks. :smile:

**Comment by ButchersBoy** [comment]
* Start a clean project in VS2012
* Install binaries
  * Install from nuget if you are targetiing .net4.5
  * Install from the .Net 4.0 zip if you are targetiing .net4.0
* Configure App.xaml
* Make sweet UI

No need for VS2015.

You only need 2015 if you are trying to compile the solution on GitHub, which contains the source used to make the binaries, and a demo project.

**Comment by diannereyno** [comment]
Got it. Thanks :+1:

**Comment by seibaaah** [comment]
![material](https://cloud.githubusercontent.com/assets/4338015/11020873/3c6e6db6-8669-11e5-9449-c9de0960b6a2.png)

**Comment by seibaaah** [comment]
How do I install from the .Net 4.0 zip?
