### ISSUE TITLE
Tooltip on button

### ISSUE THREAD

**Issue by zirius666** [ButchersBoy/MaterialDesignInXamlToolkit#105]
![tootip button](https://cloud.githubusercontent.com/assets/15053407/10616667/dcea78cc-772b-11e5-89ff-cfb6398dfa8f.png)
When i  mouseover on a button i see a type of the object on a tooltip , how i can disable that ? thanks

**Comment by ButchersBoy** [comment]
It's just the ToolTip.  Remove it.

```
<Button Style="{StaticResource MaterialDesignRaisedLightButton}" Margin="0 0 8 0" Width="100"
                    ToolTip="Resource name: MaterialDesignRaisedLightButton">
      LIGHT
</Button>
```

**Comment by zirius666** [comment]
its correct i dont think that !!sorry man . Thanks soo much

**Comment by ButchersBoy** [comment]
no  problem :)
