### ISSUE TITLE
COMBOBOX NOTIFY ERROR

### ISSUE THREAD

**Issue by zirius666** [ButchersBoy/MaterialDesignInXamlToolkit#107]
Excuse man i ask to many questions hehe i promise this will be the last today :P

Using the notify error with combox and datepicker fields the notify error dont show like textbox ??

Its suported that in that fields? if the answer is yes ...Can you put an example please?

Thanks 
![combobox error](https://cloud.githubusercontent.com/assets/15053407/10651556/c9e2bbaa-7815-11e5-8847-b1c0393a9193.PNG)

**Comment by zirius666** [comment]
I fix that with some changes on the templates thanks whatever ;)

**Comment by hshahdoost** [comment]
I'm facing the same problem, Could you please tell me how you solved it?

**Comment by ButchersBoy** [comment]
...or like if there's a bug in the library...

**Comment by hshahdoost** [comment]
I think it's a bug in the library James, I checked the Combobox style but unlike TextBox style Validation.ErrorTemplate was not set. I tried MaterialDesignValidationErrorTemplate on it and it was almost fixed. (the color of underline doesn't change but the message appears below the control)

**Comment by ButchersBoy** [comment]
OK

**Comment by ButchersBoy** [comment]
fixed recently
