### ISSUE TITLE
Not exists in the namespace

### ISSUE THREAD

**Issue by zirius666** [ButchersBoy/MaterialDesignInXamlToolkit#108]
You know why the controls send me this error? 

the tag doesnt exist on the namespace  XML 'clr-namespace:MaterialDesignThemes.Wpf;assembly=MaterialDesignThemes.Wpf'.

**Comment by ButchersBoy** [comment]
Can you post more details?

**Comment by zirius666** [comment]
i found that is a bug of the visual studio on xaml , i delete and create a new project for fix that
