### ISSUE TITLE
Support for Textbox with floating label

### ISSUE THREAD

**Issue by cashok78** [ButchersBoy/MaterialDesignInXamlToolkit#11]
I know there is a textbox same as in material design sample with validation included but I am very eager to know if you have plans to work on text box that will animate the watermark to short text and move it above if text is entered, as shown in link below :
http://www.google.com/design/spec/components/text-fields.html#text-fields-floating-labels
As this control will contain both label and Textbox in small area (Compared to placing a label or Textblock) this feature gives a lot of real-estate in UI.

**Comment by ButchersBoy** [comment]
Done...but for text boxes only currently.  Will try and get date pickers, combos, time pickers in the future.

See demos for usage.
