### ISSUE TITLE
CLOSING DIALOG HOST AUTOMATICALLY 

### ISSUE THREAD

**Issue by zirius666** [ButchersBoy/MaterialDesignInXamlToolkit#112]
i try to understand how to close the dialog host automatically .

In the example of the toolkit you call this control with  

           var view = new SampleDialog();

            //show the dialog
            var result = await DialogHost.Show(view, "RootDialog", ClosingEventHandler);

            //check the result...
            Console.WriteLine("Dialog was closed, the CommandParameter used to close it was: " + (result ?? "NULL"));

how i can close the dialog automatically ??i know presing cancel can close but i need close the dialog after login automatically  ....the can you help me please?

**Comment by ButchersBoy** [comment]
Hi @zirius666 

You can also show the dialog by using IsOpen which you can set from a view mode/code behind etc.

But now you have asked this question I am thinking I can enhance the .Show method to provide some sort of cancellation/end token.

...watch this space...

**Comment by zirius666** [comment]
Then there is no way for close without a button?

**Comment by ButchersBoy** [comment]
Yes...you can close via binding IsOpen. But I am going to add more to the Show method to make it easier.

**Comment by zirius666** [comment]
can you show me an example please?i use 
     view.IsOpen = false;
but cant close .
Sorry, im starting with xaml pages
thnks man

**Comment by ButchersBoy** [comment]
Just working on some API additions, and I will also add a new example.  Will report back when done.

**Comment by zirius666** [comment]
thanks man

**Comment by ButchersBoy** [comment]
OK, I've enhanced the .Show API so you can get hold of a "Session" to update the progress dialog and close it on demand. I've added to dialog sample 3 to illustrate this.

I've also added a sample 4 which illustrates using IsOpen purely in a MVVM binding scenario.

**Comment by zirius666** [comment]
thanks again man!

**Comment by ButchersBoy** [comment]
Just show your love by hitting the ⭐ button! 😜

**Comment by zirius666** [comment]
i cant see the image of your  mention of button but thanks :+1:

**Comment by enrmadriv** [comment]
Hello... Who can share the answer with me? 

I'm trying to auto-close a MessageDialog opened into DialogHost after x seconds but i can to achieve this.

**Comment by Keboo** [comment]
@enrmadriv you will need to [manually close](https://intellitect.com/material-design-in-xaml-dialog-host/) the dialog yourself. The simplest approach is to use a [DispatcherTimer](https://docs.microsoft.com/en-us/dotnet/api/system.windows.threading.dispatchertimer) and close the dialog when the timer ticks.
