### ISSUE TITLE
ComboBox Content not scrollable

### ISSUE THREAD

**Issue by mhn23** [ButchersBoy/MaterialDesignInXamlToolkit#113]
![comboboxissue](https://cloud.githubusercontent.com/assets/2280353/10784424/52b1507a-7d5e-11e5-8eb0-55dc9a9c6980.gif)

ComboBoxes with many Items that exceed the Height are not shown and therefore not being selectable.

**Comment by ButchersBoy** [comment]
Note @punker76 has also pointed out latest style breaks virtualization.

**Comment by ButchersBoy** [comment]
@mhn23 How's it looking now?

**Comment by mhn23** [comment]
Yes it's working fine now, what buggs me a bit that there are these hardcoded marging ontop/bottom

also do you have any plans to make auto hiding scrollbars?

**Comment by ButchersBoy** [comment]
@mhn23 the margin is according to Google's illustrations.   Scrollbars -  yes, can probably improve them  over time.
