### ISSUE TITLE
For black color, few xaml files missing in source code?

### ISSUE THREAD

**Issue by krunalc** [ButchersBoy/MaterialDesignInXamlToolkit#115]
It seems like following files are missing from source code related to black color

MaterialDesignColor.Black.Accent.xaml
MaterialDesignColor.Blue.Named.Accent.xaml

Can you pls check n revert back?

**Comment by ButchersBoy** [comment]
Hi @krunalc Black isn't an actual colour/paletter; it shouldn't be, I need to remove it.

All the "proper" palettes are setup according to Google's specifications: https://www.google.com/design/spec/style/color.html#

**Comment by ButchersBoy** [comment]
all Black .xaml files now removed.
