### ISSUE TITLE
Run dialog

### ISSUE THREAD

**Issue by andrey-poltavskiy** [ButchersBoy/MaterialDesignInXamlToolkit#117]
How can programmatically display a dialog box. I want to make the password input window.
I'm sorry that I ask here.I did not find the forum.

**Comment by ButchersBoy** [comment]
Hi, when you say "programmatically", do you mean via MVVM?  Or code-behind?

Have you looked at the samples in the demo project?  There are various techniques according to whether you are using MVVM/code-behind.

**Comment by andrey-poltavskiy** [comment]
I would like at start of of the program display the password input window. For example, in ShellView.xaml add:
<UserControl ... cal: Message.Attach = "[Event Loaded] = [Action OnLoaded ($ view)]">. 
In ShellView.xaml.cs handler:
public void OnLoaded (object view) {*** Run dialog here ***}

Maybe there's another way to display the password input window (logon window).

**Comment by ButchersBoy** [comment]
OK...have you looked at the ```DialogHost.Show``` method?  I think that's probably your best bet.

**Comment by andrey-poltavskiy** [comment]
Add code:
public async void OnLoaded(object inView)
{
	var view = new SampleDialog { DataContext = new object() };
	var result = await DialogHost.Show(view, "RootDialog", ClosingEventHandler);
}

get error: No loaded DialogHost instances.
What better place to call dialog?

**Comment by ButchersBoy** [comment]
Have you wrapped a DialogHost around the root of your XAML?  Like line 35 in here: 

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/MainWindow.xaml

**Comment by andrey-poltavskiy** [comment]
Of course. But do not moved event call to required level. Moved from UserControl to wpf:DialogHost:
wpf:DialogHost Identifier="RootDialog" cal:Message.Attach="[Event Loaded] = [Action OnLoaded($view)]"

Working. Thanks.
