### ISSUE TITLE
ComboBox virtualization doesn't work when the control is loaded with a selected item

### ISSUE THREAD

**Issue by jfehr** [ButchersBoy/MaterialDesignInXamlToolkit#119]
To reproduce, bind the combobox' selected item to a non-null property on the VM, with a large ItemsSource that you're attempting to virtualize.

Removing the `IsSelected` trigger in combobox item style prevents the issue (but then we see the selected item in the list).

**Comment by ButchersBoy** [comment]
Hi, what version are you using?

**Comment by jfehr** [comment]
Hi - I've statically linked current master.

And of course it has nothing to do with `Tag`, but rather the `IsSelected` trigger.

**Comment by ButchersBoy** [comment]
Note: I am also working on some other issues around combos...

**Comment by ButchersBoy** [comment]
OK...set item height to zero instead of collapsing it seems to do the trick.  I've added a bound selected item into the demo; seems OK.

OK in your app?

**Comment by jfehr** [comment]
That does the trick!

**Comment by ButchersBoy** [comment]
:+1:
