### ISSUE TITLE
Support for ColorZone in Flyout header

### ISSUE THREAD

**Issue by mgnslndh** [ButchersBoy/MaterialDesignInXamlToolkit#121]
The default style for flyouts 

I want to give the `Flyout` header a look similar to what is in the [material design style guide for settings](https://www.google.com/design/spec/patterns/settings.html#settings-usage). I add a new template for the header which looks like this:
```
<DataTemplate x:Key="ColorZoneFlyoutHeader" x:Shared="False">
        <mdt:ColorZone Mode="PrimaryDark" mdt:ShadowAssist.ShadowDepth="Depth2" Padding="0,0,0,16">
            <ContentPresenter ContentTemplate="{StaticResource HeaderTemplate}" Content="{Binding}"/>
        </mdt:ColorZone>
</DataTemplate>
```

![image](https://cloud.githubusercontent.com/assets/1139118/10993572/101159c2-8470-11e5-9539-d790ab3d9f42.png)

This works OK but the foreground color is slightly off. The header text color will switch to white but the back button and the window buttons will stay grayish because they use `MaterialDesignBody`. I guess the ColorZone somehow alters foreground color for TextBlock because it changes to white.
I can replace the header template with my own custom template and fix at least the back button but it seems like this is something that should be easier to style instead of complete replacement of the template. What do you guys think?

I think it would be nice to just provide a custom style for the flyout to get a header with a `ColorZone`. Perhaps there should be a FlyoutAssist class that could be used to control the Mode of the `ColorZone`.

**Comment by ButchersBoy** [comment]
OK, firstly I'll look at the back button see if we can get it to understand it's in a color zone, then I'll look at additional flyout style.  I just want to be careful we don't add a custom style for every scenario; I'm keen we keep all the pieces as compos-able as possible (although a header is a pretty common requirement).

Looking good though :smile:

**Comment by ButchersBoy** [comment]
Added a ColorZone into the Flyout HeaderTemplate.  By default is uses PrimaryMid option:

![image](https://cloud.githubusercontent.com/assets/658107/10996708/68c6f63a-847f-11e5-814c-cfe40313f691.png)

If ```Flyout.TitleVisibility="Collapsed"``` (or Hidden) it will display as previously:

![image](https://cloud.githubusercontent.com/assets/658107/10996732/9609cb68-847f-11e5-9638-a886b8d82c4a.png)

In addition to this there are two new "assist" properties in the MahApps assembly which you can apply in XAML, for further customisation options:

```
<controls:Flyout 
    mahApps:FlyoutAssist.HeaderColorMode="Accent" 
    mahApps:FlyoutAssist.HeaderShadowDepth="Depth4">
```

![image](https://cloud.githubusercontent.com/assets/658107/10996773/f814684a-847f-11e5-82a8-93278a79a315.png)

Available from version 0.0.3 https://www.nuget.org/packages/MaterialDesignThemes.MahApps/0.0.3

**Comment by ButchersBoy** [comment]
...now I'm thinking the font needs to be shrunk a little by default...

**Comment by quicoli** [comment]
fantastic!

2015-11-06 10:16 GMT-02:00 James Willock <notifications@github.com>:

**Comment by Insire** [comment]
I can't seem to reference the FlyoutAssist in my Xaml. Can someone take a look at this [TestRepo](https://github.com/Insire/MaterialDesignInXamlToolkitTestApp/blob/master/TestApp/MainWindow.xaml#L29) ?

**Comment by mgnslndh** [comment]
@Insire this issue is closed. Please create a new issue for your problem. I think you are using the wrong namespace for  FlyoutAssist. It is not part of MahApps but rather MaterialDesignThemes.MahApps
