### ISSUE TITLE
Windows 8.1 target

### ISSUE THREAD

**Issue by wouterbenninga** [ButchersBoy/MaterialDesignInXamlToolkit#122]
When I try to add the package to my Windows 8.1 application, I get:

Install-Package : Could not install package 'MaterialDesignColors 1.1.1'. You are trying to install this package into a project that targets 'Windows,Version=v8.1', but the package do
es not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by ButchersBoy** [comment]
Hi, current version is WPF only.

**Comment by wouterbenninga** [comment]
Can we expect a version for Windows 8.1 soon?

**Comment by ButchersBoy** [comment]
I'm slowly working on a UWP version...which I hope to invest some time in over Christmas/New Year...maybe then someone could pick it up and back-port it to WinRT if the so desired...but the UWP version relies on some Win10 libraries...
