### ISSUE TITLE
OpenedEventHandler won't be called?

### ISSUE THREAD

**Issue by AuroraDysis** [ButchersBoy/MaterialDesignInXamlToolkit#123]
In DialogHost.cs 159-161, I found
```C#
targets[0].SetCurrentValue(IsOpenProperty, true);
targets[0]._asyncShowOpenedEventHandler = openedEventHandler;
targets[0]._asyncShowClosingEventHandler = closingEventHandler;
```
But the OpenedEventHandler will be called in 
IsOpenPropertyChangedCallback
(DialogHost.cs 226-228)
So it won't be called when the dialog opened

**Comment by ButchersBoy** [comment]
D'oh.   Thanks for the spot.  I've updated the demo code to illustrate the fix works.
