### ISSUE TITLE
Binding error occurs in DialogHost.

### ISSUE THREAD

**Issue by yuka1984** [ButchersBoy/MaterialDesignInXamlToolkit#124]
Binding error occurs in DialogHost.

children.xaml
```xaml
<Button Command="{x:Static wpf:DialogHost.OpenDialogCommand}" Style="{StaticResource MaterialDesignFloatingActionAccentButton}">
	<Button.CommandParameter>
		<StackPanel Margin="16">
			<StackPanel Orientation="Horizontal" HorizontalAlignment="Right" >
				<Button Style="{StaticResource MaterialDesignFlatButton}"
							IsDefault="True"
							Margin="0 8 8 0"
							Command="{Binding SaveCommand}">
					Save
				</Button>
				<Button Style="{StaticResource MaterialDesignFlatButton}"
							IsCancel="True"
							Margin="0 8 8 0"
							Command="wpf:DialogHost.CloseDialogCommand">
					CANCEL
				</Button>
			</StackPanel>
		</StackPanel>
	</Button.CommandParameter>
	保存
</Button>
```

parent.xaml
```xaml
<wpf:DialogHost Identifier="RootDialog" IsOpen="{Binding IsDialogOpen.Value}">
	<ContentControl Margin="16" Content="{Binding Content, Mode=TwoWay}" />
</wpf:DialogHost>
```

```csharp
children.DataContext = new childrenViewModel();
var parentViewModel = new ParentViewModel();
parentViewModel.Content = children;
parent.DataContext = parentViewModel;
```

childrenViewModel have SaveCommand.

An error is logged when open Dialog.

BindingExpression path error: 'SaveCommand' property not found on 'object' ''ParentViewModel'

Is this a bug?

I was corresponding by modifying the DialogHost.

DialogHost.cs OpenDialogHadler
```csharp
if (executedRoutedEventArgs.Parameter != null)
{
	AssertTargetableContent();
	DialogContent = executedRoutedEventArgs.Parameter;
	// Add Sart
	var dialogHomeSource = executedRoutedEventArgs.Source as FrameworkElement;
	if (dialogHomeSource?.DataContext != null
		&& !DataContext.Equals(dialogHomeSource.DataContext))
	{
		var dialogElement = DialogContent as FrameworkElement;
		if (dialogElement != null)
		{
			dialogElement.DataContext = dialogHomeSource.DataContext;
		}
	}
	// Add End
}
```

**Comment by ButchersBoy** [comment]
Hi @yuka1984 

The dialog popup content (your StackPanel) will take its DataContext from DialogHost.

I think, looking at your code, maybe you could have ```<StackPanel DataContext="{Binding Content}" /> ```

**Comment by yuka1984** [comment]
Hi.
Thank you for your reply.
Did not work on your ideas .

**Comment by ButchersBoy** [comment]
If I edit Dialogs.xaml in the demo project:

![image](https://cloud.githubusercontent.com/assets/658107/11032922/33f5314c-86d7-11e5-83e4-c128dbb253cc.png)

And then open up the SAMPLE 2 dialog, and use Snoop, I can see the DataContext is passed through:

![image](https://cloud.githubusercontent.com/assets/658107/11032957/780d7a74-86d7-11e5-9150-7678ba3162e2.png)

So I think the key is to make sure your CuttonCommandParamenter/StackPanel has the correct DataContext:

```
<Button Command="{x:Static wpf:DialogHost.OpenDialogCommand}" Style="{StaticResource MaterialDesignFloatingActionAccentButton}">
    <Button.CommandParameter>
        <StackPanel Margin="16" DataContext="????">
```

Do you use Snoop or Visual Studio 2015 Live Visual Tree?  Using those you can inppect the DataContext of your item displayed in the popup.  This might give you  a clue.

**Comment by yuka1984** [comment]
I Try
```
<StackPanel Margin="16" DataContext="{Binding}">
```
and
```
<StackPanel Margin="16" DataContext="{Binding Content}">
```
![er1](https://cloud.githubusercontent.com/assets/13382333/11034418/bf9944fc-872e-11e5-9941-51aa88ea5ca0.jpg)

**Comment by ButchersBoy** [comment]
If you post a demo project on GitHub I can try and fix.

**Comment by yuka1984** [comment]
https://github.com/yuka1984/cmin
I delete this Repository after an hour from now.

**Comment by ButchersBoy** [comment]
OK, I understand now...it is a bug in my stuff.  Because CommandParameter is not a logical child it is not picking up any binding.  

:disappointed: 

I will make a fix...

**Comment by yuka1984** [comment]
Thank you.
I wait you make fix.

**Comment by ButchersBoy** [comment]
OK, try with the latest code, and yout binding should simply be:

```
<Button Style="{StaticResource MaterialDesignFlatButton}"
            IsDefault="True"
            Margin="0 8 8 0"
            Command="{Binding SaveCommand}" CommandParameter="{Binding Model}">
    保存
</Button>
```

**Comment by yuka1984** [comment]
Thank you .

**Comment by yuka1984** [comment]
contentElement.DataContext
It is not null. DialogHostDataContext has been set.

**Comment by ButchersBoy** [comment]
Ok, so if you call it a second time you want to use a different data context?

I have to be a little bit careful not to accidentally overwrite stuff.

**Comment by ButchersBoy** [comment]
I was a bit worried about overwriting the DataContext on the element passed in.  I think now I have a better solution:

* The DataContext is applied at ContentControl level (inside DialogHost/popup template)
* You can explicity control how the DataContext is applied using ```DialogHost.OpenDialogCommandDataContextSource```.  In your case the default value should suffice so you wont need to change this value.

**Comment by ButchersBoy** [comment]
Ok now?

**Comment by yuka1984** [comment]
Sorry.Very busy now.

**Comment by yuka1984** [comment]
```
Button Command="{x:Static wpf:DialogHost.OpenDialogCommand}" HorizontalAlignment="Right" Margin="5,5,30,5" DockPanel.Dock="Bottom" Style="{StaticResource MaterialDesignFloatingActionAccentButton}">
                <Button.CommandParameter>
                    <StackPanel Margin="16" x:Name="SaveConfirmDialog"> 
```

and
```
setupview.DataContext = setupVm;
setupview.SaveConfirmDialog.DataContext = setupVm;
```
And I was able to get a good result .

**Comment by ButchersBoy** [comment]
:+1:
