### ISSUE TITLE
In ExtendedOpenedEventHandler call eventargs.Session.Close()

### ISSUE THREAD

**Issue by AuroraDysis** [ButchersBoy/MaterialDesignInXamlToolkit#125]
In **ExtendedOpenedEventHandler** when I call **eventargs.Session.Close();**
I should write like this to prevent this dialog has been closed

```C#
private async void ExtendedOpenedEventHandler(object sender, DialogOpenedEventArgs eventargs)
{
    try
    {
        //Some things should be waited

        //May be I want a button named "hide" to close dialog before this time
        eventargs.Session.Close();
    }
    catch (InvalidOperationException e) when (e.Message == "Dialog session has ended.")
    {
        
    }      
}
```
Why not change **DialogSession.IsDisabled** from **internal** to **public** or another way to avoid try catch
You know it's really troublesome.

**DialogSession.cs**

**Comment by ButchersBoy** [comment]
So what you're saying is, you potentially want to call Close twice?

**Comment by AuroraDysis** [comment]
No, I means if process is end it will close automatically, or maybe user want to hide dialog before end, I should make sure the dialog is closed or not. So I need to get IsDisabled property, I think it is a normal requirement.

**Comment by ButchersBoy** [comment]
OK, I'll make it readable, and will probably rename it as it will become part of the API.

**Comment by ButchersBoy** [comment]
```DialogSession.IsEnded``` is your new friend.

**Comment by AuroraDysis** [comment]
OK, thanks for revise
