### ISSUE TITLE
Is it possible to make a TextBox animation invisible

### ISSUE THREAD

**Issue by beto-rodriguez** [ButchersBoy/MaterialDesignInXamlToolkit#128]
First of all thanks for this contribution.

I am making a control to autocomplete and I have a textbox inside this control but I need it without borders. the problem is that no matter the properties I change I can't stop the animation. Is there anyway to stop it?

```
_textBox = new TextBox
{
     BorderThickness = new Thickness(0),
     BorderBrush = Brushes.Transparent
};
```
the problem hapens in currency Autocomplete Box
![image](https://cloud.githubusercontent.com/assets/10853349/11126314/ed421d50-8933-11e5-9755-b44a0d387759.png)
I dont need that animated line, this is not a text box, its a custom control but it gets animated by this framework.
![image](https://cloud.githubusercontent.com/assets/10853349/11126345/0d83b682-8934-11e5-84d3-75ded0e42b9a.png)

Thanks. I hope I was clear enough

**Comment by beto-rodriguez** [comment]
Ok overriden style works. 

```
_textBox = new TextBox
            {
                BorderThickness = new Thickness(0),
                BorderBrush = Brushes.Transparent,
                Style = new Style()
            };
```

But I dont like this, I think the thickness of the animation should be based on `TextBox` thinkness.

**Comment by ButchersBoy** [comment]
I'll consider a shortcut to make this easier for a future release.

**Comment by ButchersBoy** [comment]
P.S. Nice screenshots :smiley_cat:

**Comment by ButchersBoy** [comment]
Now available in 1.4 (pre-release). See https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/212 for usage details.

**Comment by beto-rodriguez** [comment]
thank you, awesome job!

**Comment by ButchersBoy** [comment]
@beto-rodriguez by-the-way...have you considered making your Material Menu use the colour resources from this lib (MaterialDesignColors.dll)?  Would be cool to evolve the ecosystem with some compatible controls.

**Comment by beto-rodriguez** [comment]
@ButchersBoy thanks, yes I actually wanted to make a pull request for you, but Material menu needs a rewrite, I will as soon as possible, I actually was learning wpf when wrote that, so I need to fix a lot of mistakes I made when learning

**Comment by ButchersBoy** [comment]
Well for starters, you can make it your own separate control/package; so long as you define your styles using DynamicResource names specified by the palettes/swatches it would be compatible.  This is what Dragablz does.  ...if you try it out one day and need help give me a shout.

**Comment by beto-rodriguez** [comment]
@ButchersBoy Thank you very much I really appreciate it.
