### ISSUE TITLE
Material Design textures like ones found in Android wallpapers for WPF

### ISSUE THREAD

**Issue by SuicSoft** [ButchersBoy/MaterialDesignInXamlToolkit#131]

**Comment by ButchersBoy** [comment]
You referring to this kind of thing?

http://d0od.wpengine.netdna-cdn.com/wp-content/uploads/2014/10/material-wallpaper-full.jpg

**Comment by SuicSoft** [comment]
Yes , it was night in my timezone so sorry for the late reply

**Comment by SuicSoft** [comment]
@ButchersBoy  So will we have to use images for the textures?

**Comment by ButchersBoy** [comment]
There is possibly something I could do...I kinda have an idea...but whether it will work or add value I don't know...let me think on it and experiment a bit.

**Comment by SuicSoft** [comment]
@ButchersBoy Ok

**Comment by SuicSoft** [comment]
@ButchersBoy Maybe also some of this https://design.google.com/articles/the-art-behind-android-marshmallows-new-wallpapers/

**Comment by ButchersBoy** [comment]
Not going to do anything with this, can't think of anything sensible to do with geometries.  Best to just provide your own wallpapers in your app.
