### ISSUE TITLE
ColorZone not found in materialDesign namespace

### ISSUE THREAD

**Issue by martauk** [ButchersBoy/MaterialDesignInXamlToolkit#133]
Hello,
I'm building an app using MaterialDesignInXamlToolkit.
I declare materialDesign namespace using "xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
When i try to use it (<materialDesign:ColorZone>), VS tells me that it can't found ColorZone in the namespace.
How can i fix it ?

**Comment by SuicSoft** [comment]
Are you using the latest pre-release NuGet packages or building from the source? Then you shouldn't have any problems.

SuicSoft

**Comment by ButchersBoy** [comment]
And you definitely have the dll referenced in your project?  This should work...might be worth you joining the gitter room for help on this if you haven't got it going https://gitter.im/ButchersBoy/MaterialDesignInXamlToolkit

**Comment by SuicSoft** [comment]
@martauk I think your trying to do this without adding the NuGet package or referencing MaterialDesignThemes. The custom namespace has nothing to do with the web or the server and is just a 'name'.

**Comment by martauk** [comment]
I installed the package from NuGet ! I decided to move my project to Mahapps, thanks !
