### ISSUE TITLE
Some animations on low end windows 10 tablets are laggy

### ISSUE THREAD

**Issue by Carl-M** [ButchersBoy/MaterialDesignInXamlToolkit#137]
Opening and closing a full screen dialog is quite choppy, the last few momments where it grows slightly seem to get extended by a few seconds. Observed on a linx 810 quad core 1.8ghz atom tablet.

Would be good to have an option to downgrade the animation or disable it for certain elements to improve performance.

**Comment by ButchersBoy** [comment]
Hi, I will look at this, but out of curiosity, can you try this on your hardware and report back the results?

Stick this somewhere near startup of your app:

```
Timeline.DesiredFrameRateProperty.OverrideMetadata(typeof(Timeline), new FrameworkPropertyMetadata { DefaultValue = 30 });
```

**Comment by Carl-M** [comment]
Hi,

Yes limiting to 30fps seems to have made a little better, with out it I get the occasional laggy dialog opening, with it enable it's not as smooth as the desktop but is consistent. It could well be a hardware or wpf limitation. Have checked the processor loading (stays around 30-40% during dialog opening, memory is fine with 50% free, no other fullscreen apps running.

**Comment by ButchersBoy** [comment]
OK.  I will look into adding a zero-animation dialog opening mode, then with the above you can tune to your requirements.

**Comment by SuicSoft** [comment]
Maybe we can also auto enable the zero animation dialog when low on battery

**Comment by ButchersBoy** [comment]
@SuicSoft please see new [contribution guidelines](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/Contribution-Guidelines).  We won't introduce any "application" logic.  That's not the responsibility of this library.  I'll help out a bit with the ability to switch this animation off; but the decision on when to do such things is an applications' responsibility.

**Comment by SuicSoft** [comment]
Yeah , I think these kinds of things shouldn't be in the library. Anyways how about adding a Contributing.md file to the repo.

**Comment by ButchersBoy** [comment]
I've already added a link to it from the main readme.md

**Comment by SuicSoft** [comment]
@ButchersBoy If you create a contributing.md , it will show a message at the top whenever you contribute to the repo

**Comment by ButchersBoy** [comment]
@SuicSoft OK, I'll do that.

**Comment by ButchersBoy** [comment]
There is now a new attached property:

```materialDesign:TransitionAssist.DisableTransitions="True" ```

This is an inheritable property, so you could put it at your root (e.g Window or DialogHost) to switch off transitions where supported.  Then you could turn them back on at lower lever elements where performance is less than an issue.  I'm going to work through the transitions so they are aware of this property:

- [x] DialogHost
- [x] Drawer
- [ ] Clock
- [ ] Underline
- [ ]  ???
