### ISSUE TITLE
Multi action button

### ISSUE THREAD

**Issue by ButchersBoy** [ButchersBoy/MaterialDesignInXamlToolkit#139]

**Comment by SuicSoft** [comment]
@ButchersBoy Is this like the one found in Google's new inbox (inbox.Google.com)

**Comment by ButchersBoy** [comment]
yes, it will be

**Comment by ButchersBoy** [comment]
Bugs:

[ ] disable eager PopupEx when drawer is open (so should be able to disable based on PopupBox.IsEnabled)

**Comment by l1pton17** [comment]
Have founded some bug when placement of a button is changing.
![bugexample](https://cloud.githubusercontent.com/assets/5460448/11769264/10b0aecc-a1f4-11e5-93bf-f283c83bdfa3.gif)

**Comment by ButchersBoy** [comment]
@l1pton17 fixed placement.  Think I need to improve tooltip positioning in some cases though.
