### ISSUE TITLE
Need a logo/icon

### ISSUE THREAD

**Issue by ButchersBoy** [ButchersBoy/MaterialDesignInXamlToolkit#14]
This project needs a logo, and I'm sure there are way better designers than me who could do the task justice.

Obviously this project is open source so there would be no payment, but if anyone can provide a decent logo which suits this project then I'll link to their website/portfolio for the lifetime of this project.

What's the spec?  Well, it's this project: a XAML/WPF toolkit for creating material design interfaces.  I guess the logo will probably follow the material design logo guidelines.

**Comment by snalty** [comment]
Hi, does this look?

![md4xaml](https://cloud.githubusercontent.com/assets/9409534/7445765/40c50faa-f1b8-11e4-8a07-505205810719.png)

**Comment by ButchersBoy** [comment]
Love it! Nice one!

**Comment by ButchersBoy** [comment]
I'll happily use that....your wanna send it me, or create an images directory and send a PR?  And a link to your homepage portfolio?

**Comment by quicoli** [comment]
Great!

Enviado pelo meu Windows Phone 

-----Mensagem Original-----
De: "snalty" <notifications@github.com>
Enviada em: ‎03/‎05/‎2015 13:17
Para: "ButchersBoy/MaterialDesignInXamlToolkit" <MaterialDesignInXamlToolkit@noreply.github.com>
Assunto: Re: [MaterialDesignInXamlToolkit] Need a logo/icon (#14)

Hi, does this look?

**Comment by snalty** [comment]
Don't really understand git so I'll post them here. The archive should contain the PSD and a 512px PNG.
https://drive.google.com/file/d/0Bz9SXjQies59RVBlZVpKYW0tTmc/view?usp=sharing

[The closest thing I have to a portfolio is this old blog (I'm only a designer by night haha).](http://holothere.tumblr.com)

**Comment by ButchersBoy** [comment]
Many thanks, it's on the readme, and will popup on nuget, and the proper web page (when I get around to creating one!)
