### ISSUE TITLE
Where are assemblies with Strong Name?

### ISSUE THREAD

**Issue by takuya-takeuchi** [ButchersBoy/MaterialDesignInXamlToolkit#141]
Please forgive the boring questions.

I develop small application with Material Design Xaml Toolkit.
But this application must to be signed with string name.
So all referenced assemblies need to be signed.

I can not find signed 'MaterialDesignThemes.Wpf' and 'MaterialDesignThemes.MahApps'.
Will you not provide signed dlls?

If you never provide them, I have to compile source code to add strong name, right?

Thank you for your cooperation.

**Comment by ButchersBoy** [comment]
Hi, I suggest using this to strong name the assemblies as part of your build process:

https://github.com/dsplaisted/strongnamer

**Comment by takuya-takeuchi** [comment]
Oh my god!!!
Build errors Was removed!! It's miracle!!!

Thank you for telling me good tool!!!

**Comment by ButchersBoy** [comment]
Happy days :)

**Comment by TheMintRubber** [comment]
The solution with strongnamer does not work. I have created a small strong project with just 3 nuggets and the themes applied in application resources and the app will crash at runtime with the following message:

Could not load file or assembly 'MaterialDesignThemes.Wpf, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"MaterialDesignThemes.Wpf, PublicKeyToken=null.

Check the sample project to easily reproduce the issue: [StrongTesting.zip](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/files/913449/StrongTesting.zip)

Do you have any solution for this?

**Comment by ButchersBoy** [comment]
Put of curiosity, did you sign the Colours assembly too?

**Comment by TheMintRubber** [comment]
Yes, the Colours assembly is also signed.

**Comment by TheMintRubber** [comment]
I've found a different solution: 

I've embedded all the unsigned material design dlls into my main assembly using [Fody.Costura](https://github.com/Fody/Costura). 

Thanks for your help.

**Comment by C1rdec** [comment]
Any update on this ?

**Comment by mumarniaz** [comment]
We also have the same problem. We need signed assemblies and there is no signed assemblies from Material Design.

**Comment by Keboo** [comment]
@mumarniaz. You can sign the assemblies yourself. https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Strong-Naming

**Comment by rmorgan001** [comment]
I just ran into this and wanted to leave a note that it's an issue with strongnamer. When it runs it is not properly updating the BAML (the compiled form of XAML). here is what worked for me.

public App()
{
    AppDomain.CurrentDomain.AssemblyResolve += CurrentDomainOnAssemblyResolve;
}

private Assembly CurrentDomainOnAssemblyResolve(object sender, ResolveEventArgs args)
{
    var assemblyName = new AssemblyName(args.Name);
    var assembly = AppDomain.CurrentDomain.GetAssemblies()
        .FirstOrDefault(a => a.GetName().Name == assemblyName.Name);
    return assembly;
}
