### ISSUE TITLE
Remove usages of .Tag on ComboBox theme

### ISSUE THREAD

**Issue by ButchersBoy** [ButchersBoy/MaterialDesignInXamlToolkit#147]
- [ ] ComboBox theme (ComboBoxItem.Tag)
- [ ] Also, TreeView theme, but lower priority as on more of a hidden element.

Should remove this as we are blocking people from using .Tag for their own purposes, and replace with an attached property.

Either:
* Add
  *  ```ComboBoxAssist.HideItem : bool``` 
  * ```TreeViewAssist.HeightFactor : double```
* Or a single ```MaterialDesign.FrameworkTag : object```

I think I prefer the former, more verbose option, even though it creates more classes...

**Comment by l1pton17** [comment]
But treeview is using of inner scrollviewer's tag, that is not a part of open properties.
I mean template doesn't use TreeViewItem.Tag.

**Comment by ButchersBoy** [comment]
Sorry, my mistake...

But did you see https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/159 ?

**Comment by l1pton17** [comment]
@ButchersBoy yes, i will fix it in a few days

**Comment by ButchersBoy** [comment]
Cool, thanks, I'll mark as in progress and leave to you.
