### ISSUE TITLE
FloatingHint-Style for more controlls

### ISSUE THREAD

**Issue by FrTerstappen** [ButchersBoy/MaterialDesignInXamlToolkit#148]
The floating hint style seems to only exist for a small number of controlls.
I found one for the **TextBox** and the **ComboBox** but it seems for example to be unavailable for the **DatePicker** and **PasswordBox**.

I would really like to use this style but it looks not good if you mix it with controls that don't support this style. Is such a style planned? Is there a road map for such things? This would allow me to use it and wait for the missing styles if the are not so far away.

**Comment by ButchersBoy** [comment]
OK, yeah, can add that to the list.

**Comment by ButchersBoy** [comment]
- [ ] DatePicker
- [ ] TimePicker
- [ ] PasswordBox

**Comment by FrTerstappen** [comment]
I think it would also be nice to have this style for the textblock and the checkbox/radiobutton.

The Textblock looks kind of out of place at the moment if used next to texboxes to display unchangable data. The workaround is to use a disabled textbox.

Checkboxes and radiobuttons look also out of place because they need a top margin.
On this controls it would be enough to give them the same distance to the top like for example a textbox.

I believe having a Floating hint style for both would make it significant easier to use all these controlls in a single gui without the need to "move" some of them with margins.

**Comment by ButchersBoy** [comment]
@FrTerstappen 

Margin issues aside, I'm not sure I understand.  How do you envisage a radio/checkbox looking with an animated floating hint.  And a TextBlock?

Maybe you could post a screenshot/mock-up?

**Comment by FrTerstappen** [comment]
@ButchersBoy 
Okay i think i did not make my point clear. I made some screenshots to make it more clear.
Both controls are in a grid with row set to auto and colum width="*". 

This is a check box next to a text box on font size 16:
![old](https://cloud.githubusercontent.com/assets/4691028/11895274/b9a84aa8-a57d-11e5-8e04-b69cfc24834e.png)
The checkbox is clearly out of line. 
Beside that you can see the check box is not centered in front of the text on other font sizes.

I can fix this with a Margin="0,15,0,0" but this depends on the font size and is very annoying if you have a lot of controls.
![margintop](https://cloud.githubusercontent.com/assets/4691028/11895272/b9a093e4-a57d-11e5-9e52-25fa04538cb3.png)

The check box being not centered in front of its text can be fixed with VerticalContentAllignment="Center"
![margintopandverticalcontent](https://cloud.githubusercontent.com/assets/4691028/11895273/b9a6ea46-a57d-11e5-86d4-cd50155d4f58.png)

The floating hint style would in this case not include a floating hint. It would more be a BeInLineWithTheFloatingHintControls-Style.

The same goes for the text block except that the text block need to display a hint.

**Comment by ButchersBoy** [comment]
Bit more complicated than that, as we have validation (below) which also comes in two different forms; below and popup-below.  So if I was gonna cover all angles I'd end up with a lot of noise.  I'll have a think about it, but I suggest for now you use style inheritance based on of the MaterialDesignTheme.TextBlock.xaml styles, customize for your margin, and apply that in a local resource dictionary (for example Grid.ResourceDictionary).

**Comment by FrTerstappen** [comment]
@ButchersBoy 
Thanks for the suggestion but i think that this is not really applicable. The margin changes with the font size and i would end up with a few styles.

I can see that it would require you to cover many cases. The workaround is so easy that i think this is very low priority compared to the other controls.

**Comment by 4ipalino** [comment]
I have extended the PasswordBoxTheme based on the TextBoxTheme to support floating like the TextBox. Maybe i forgot something, but it was a quick workaround for me until this control is supported.



[FloatingPasswordBox.zip](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/files/67942/FloatingPasswordBox.zip)

**Comment by ButchersBoy** [comment]
@4ipalino if you want to open up a PR I'll code review it and we can pull it in?

**Comment by ButchersBoy** [comment]
@l1pton17 is working on a PR which will add the missing styles.

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/pull/303

**Comment by ericfeng8941** [comment]
Any FloatHint update on DatePicker?

**Comment by ButchersBoy** [comment]
Yeah it's in 2.0

**Comment by ericfeng8941** [comment]
Thanks a lot, any time to release to NuGet?

**Comment by ButchersBoy** [comment]
It's already there...use -pre (pre release)
