### ISSUE TITLE
Tidy up error and blackout styles on Calendar/DatePicker.

### ISSUE THREAD

**Issue by ButchersBoy** [ButchersBoy/MaterialDesignInXamlToolkit#15]

**Comment by SuicSoft** [comment]
Can you give more info on this

**Comment by ButchersBoy** [comment]
In the WPF calendar you have black out dates.  Take a look here: http://www.wpftutorial.net/Calendar.html#blackout

You'll see some dates have crosses through.  Basically, I never created a style for those crosses, so we need to "materialize" them.  Need to check Google's Material Design specs to see if they have a suggestion, otherwise take a look at some Google apps and see if they do this.  Lastly, just come up with something which looks good :)

**Comment by SuicSoft** [comment]
@ButchersBoy Now I get it. Maybe we can just gray them out instead of putting a X

**Comment by ButchersBoy** [comment]
Yeah, greying them would be cool.  I don't even know what it looks like at the moment...

**Comment by SuicSoft** [comment]
Here's an image i created in gimp by increasing the brightness on the text using your gifs. Will look better when in wpf :smiley: 
![snapshot](https://cloud.githubusercontent.com/assets/13938848/11148237/7d447ed0-8a41-11e5-902a-5c485651e864.png)
