### ISSUE TITLE
materialDesign:PopupBox Error

### ISSUE THREAD

**Issue by damosse31** [ButchersBoy/MaterialDesignInXamlToolkit#151]
Hi all !

I try to use PopupBox but everywhere I try to put this on my Xaml files, I have an error *"PopupBox doesn't exist in namespace"* only for this object.

In my App.xaml I have all ResourceDictionary mentioned in Starting guide 
```
<ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Lime.xaml" />
            </ResourceDictionary.MergedDictionaries>
```

I use Visual Studio 2015, C# WPF and have the latest stable version from NuGet.

Here, screenshot of my error (in french)
![screenshot_1](https://cloud.githubusercontent.com/assets/16171524/11611148/61a50cb0-9bbe-11e5-8c8b-c500f76953ec.png)

Best regards.
Dams

**Comment by ButchersBoy** [comment]
Hi, PopupBox is still pre release, so you need to get latest unstable from nuget.

**Comment by damosse31** [comment]
Hi,

thank you, glad to help if need !.
