### ISSUE TITLE
Opportunity to disable progess bar's loading animation

### ISSUE THREAD

**Issue by l1pton17** [ButchersBoy/MaterialDesignInXamlToolkit#161]
Could you please add the opportunity to disable progress bar's loading animation?
Maybe via some ProgressBarAssist

For example, when i use progress bar with tabcontrol it plays animation every time.

![progressbarloadingeffect](https://cloud.githubusercontent.com/assets/5460448/11779041/c4c201e8-a269-11e5-9c1a-987f2d272cfb.gif)

**Comment by ButchersBoy** [comment]
Ok

**Comment by ButchersBoy** [comment]
Got an interesting thing going on...I used the existing ```TransitionAssist.DisableTransitions ``` to try and keep the API streamlined.  The animation is started from trigger, so if this is set it runs a different animation to immediately scale to 100%.  Funny thing is, the attached property applies after the initial load, so the first load of the control causes the original animation to run.  The second time the control loads, ```TransitionAssist.DisableTransitions ``` is set, and you wont see the scale animation.

I guess this is what you want, although it's a little bit annoying as the behaviour of setting ```TransitionAssist.DisableTransitions ``` isn't strictly true to the name of the property as it happens for subsequent loads.

But on the other hand I have tried to do as much as possible with ```ProgressBar``` without consumers having to inherit etc, so we don't have much access to modify transitions etc.  So it seems to be a reasonable result...

**Comment by ButchersBoy** [comment]
Assuming OK, re-open if there's an issue.

**Comment by 4ipalino** [comment]
Is this fix already included in 1.3?

**Comment by ButchersBoy** [comment]
Yes...but read comments above...
