### ISSUE TITLE
Hamburger rotation position property

### ISSUE THREAD

**Issue by SuicSoft** [ButchersBoy/MaterialDesignInXamlToolkit#165]
Hi,
I think there should be a property on the hamburger toggle button for the position of the animation (0.3, 1.0, etc) so that we can maybe bind it to the flyout or something (like in Android apps). As you can see here https://www.google.com/design/spec/animation/delightful-details.html the hamburger position should be customizable

**Comment by SuicSoft** [comment]
@ButchersBoy Hi

**Comment by ButchersBoy** [comment]
This is probably gonna require a new control to be written...low priority right now.

**Comment by SuicSoft** [comment]
Are you sure we can't do anything with an attached property. Anyways I
think the hamburger anyways needs it s own control

On 16/01/2016, James Willock <notifications@github.com> wrote:
> This is probably gonna require a new control to be written...low priority
> right now.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/165#issuecomment-172045383


-- 
*Suicune WD*
The Studio/Software Dog
*suiciwd@gmail.com <suiciwd@gmail.com>*
