### ISSUE TITLE
Couldn't find error message in TextBox

### ISSUE THREAD

**Issue by SuplenC** [ButchersBoy/MaterialDesignInXamlToolkit#166]
I'm probably doing something wrong. How can I set error message on textbox from code (not xaml) whenever I want it?

**Comment by ButchersBoy** [comment]
It uses the standard WPF pattern for errors:

http://stackoverflow.com/questions/14023552/how-to-use-idataerrorinfo-error-in-a-wpf-program

**Comment by SuplenC** [comment]
That was fast. But where should I pass the ErrorContent

**Comment by ButchersBoy** [comment]
Typically what you provide in IDataErrorInfo.Error is what ends up displaying on the TextBox...this is a WPF feature, not a Material Design Toolkit feature; we just have a style for it.

So have you got your IDataErrorInfo setup correctly?  It might be worth you doing it in a blank WPF project to prove you have it working, then using it in Material Design.

**Comment by SuplenC** [comment]
Ok I did it. Just as you said implemented standard validation. I'm an idiot sorry for the spam.

**Comment by ButchersBoy** [comment]
np.
