### ISSUE TITLE
Cant Fint Property Related To Watermark

### ISSUE THREAD

**Issue by eleandro83** [ButchersBoy/MaterialDesignInXamlToolkit#169]
How Can i Set a Watermark In a TextBox? Im Not Finding Anything Related To It On TextBox Properties, Using Controls:TextBoxHelper Dont Work Because The Template Was Replaced... But i See Watermark In Your Videos. So, How Can i Do That? Sorry If i Ask In The Wrong Place. Iam New On Git...
![image](https://cloud.githubusercontent.com/assets/16366154/11915701/8625dd08-a6b3-11e5-9f9f-e8ac75e63c89.jpg)

**Comment by ButchersBoy** [comment]
As per demo:

```
<TextBox materialDesign:TextFieldAssist.Hint="Name"  />
```

**Comment by eleandro83** [comment]
Thanks 😅
