### ISSUE TITLE
I've download code, but I got errors when compiling it

### ISSUE THREAD

**Issue by quicoli** [ButchersBoy/MaterialDesignInXamlToolkit#17]
Error	6	The tag 'Clock' does not exist in XML namespace 'clr-namespace:MaterialDesignThemes.Wpf;assembly=MaterialDesignThemes.Wpf'. Line 57 Position 4.	D:\Paulo\Projetos\MaterialDesignInXamlToolkit-master\MaterialDesignColors.WpfExample\ProvingGround.xaml	57	4	MaterialDesignColors.WpfExample

Error	7	The property 'TextField.Hint' does not exist in XML namespace 'clr-namespace:MaterialDesignThemes.Wpf;assembly=MaterialDesignThemes.Wpf'. Line 58 Position 6.	D:\Paulo\Projetos\MaterialDesignInXamlToolkit-master\MaterialDesignColors.WpfExample\TextFields.xaml	58	6	MaterialDesignColors.WpfExample

Error	9	The property 'TextField.Hint' does not exist in XML namespace 'clr-namespace:MaterialDesignThemes.Wpf;assembly=MaterialDesignThemes.Wpf'. Line 61 Position 6.	D:\Paulo\Projetos\MaterialDesignInXamlToolkit-master\MahMaterialDragablzMashUp\TextFields.xaml	61	6	MahMaterialDragablzMashUp

Error	10	The name "Clock" does not exist in the namespace "clr-namespace:MaterialDesignThemes.Wpf;assembly=MaterialDesignThemes.Wpf".	D:\Paulo\Projetos\MaterialDesignInXamlToolkit-master\MaterialDesignColors.WpfExample\ProvingGround.xaml	57	3	MaterialDesignColors.WpfExample

Error	11	The name 'nameof' does not exist in the current context	D:\Paulo\Projetos\MaterialDesignInXamlToolkit-master\MaterialDesignThemes.Wpf\DateTimeEx.cs	11	57	MaterialDesignThemes.Wpf

Error	12	The name 'nameof' does not exist in the current context	D:\Paulo\Projetos\MaterialDesignInXamlToolkit-master\MaterialDesignThemes.Wpf\Converters\ClockItemIsCheckedConverter.cs	19	67	MaterialDesignThemes.Wpf

**Comment by ButchersBoy** [comment]
ahhh...looks like some C# 6.0 snuck back in.  I had removed C#6 features (for now) but I guess ReSharper was helping me out.

Look at error 11 & 12...get rid of the **nameof** operations.  Or of course download VS2015 CTP.

(Don't forget these packages are available via nuget too).

**Comment by ButchersBoy** [comment]
...i've removed the c#6.0 features...
