### ISSUE TITLE
Include font with material icons

### ISSUE THREAD

**Issue by Sergey-Terekhin** [ButchersBoy/MaterialDesignInXamlToolkit#171]
What do you think about including in the theme some icon fonts like:
https://github.com/google/material-design-icons/tree/master/iconfont

or extended community version:
https://github.com/Templarian/MaterialDesign-Webfont/tree/master/fonts

**Comment by ButchersBoy** [comment]
Hi, yeah, I will include @Templarian 's icons, hopefully early in the New Year.
