### ISSUE TITLE
Losting TextBox And PasswordBox Styles

### ISSUE THREAD

**Issue by eleandro83** [ButchersBoy/MaterialDesignInXamlToolkit#172]
When i Try To Add a New Property Value In a Style, i Lost Some Properties... I Have Tried To Make a Style BaseOn="{StaticResource {x:Type TextBox}}", Without Sucess, This Lost All The Control Style... If i Get The Control Template And Restyle, i Lost The Hint Property And The Control Still Without a Watermark. How Can i Solve It?

**Comment by ButchersBoy** [comment]
You have to base your style on the Material Design style, so something like:

```
<Style TargetType="{x:Type TextBox}" BasedOn="{StaticResource MaterialDesignTextBox}" />
```

If you want to see the names you should inherit from, look in [MaterialDesignTheme.Defaults.xaml](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Defaults.xaml).

**Comment by eleandro83** [comment]
. Thanks a Lot 😊
