### ISSUE TITLE
Cant Build MaterialDesignToolkit

### ISSUE THREAD

**Issue by eleandro83** [ButchersBoy/MaterialDesignInXamlToolkit#173]
Im Using Visual Studio 2012 And When i Try To Build MaterialDesignToolkit Source, i Receive a Lot Errors. Is Why Im Here Asking For Little Things, Because Im Unable To Understand How Its Work . XAML Is Not Find Some Resources And Getting Others Crazys Errors. I Just Extract The Zip And Open, Nothing More... How Can i Solve It?

**Comment by ButchersBoy** [comment]
To build the source you need VS2015.
