### ISSUE TITLE
SetLightDark crashes

### ISSUE THREAD

**Issue by 4ipalino** [ButchersBoy/MaterialDesignInXamlToolkit#174]
My Application crashes always when i call `new PaletteHelper().SetLightDark(isDark);` with an `System.InvalidOperationException`.

StackTrace:

    bei System.Uri.get_AbsolutePath()
    bei MaterialDesignThemes.Wpf.PaletteHelper.<>c.<SetLightDark>b__0_1(ResourceDictionary rd)
    bei System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
    bei MaterialDesignThemes.Wpf.PaletteHelper.SetLightDark(Boolean isDark)

**Comment by ButchersBoy** [comment]
Please retry on latest.

**Comment by ButchersBoy** [comment]
Merged your PR so closing.

**Comment by l4km47** [comment]
`
namespace MaterialDesignThemes.Wpf
{
    public class PaletteHelper
    {
        public virtual void SetLightDark(bool isDark)
        {
           //[...]
//remove this if fromPaletteHelperClass
    //if (existingResourceDictionary == null)
            //    throw new ApplicationException("Unable to find Light/Dark base theme in Application resources.");
`
