### ISSUE TITLE
Theme for default TabControl is missing

### ISSUE THREAD

**Issue by Sergey-Terekhin** [ButchersBoy/MaterialDesignInXamlToolkit#179]
Do you have any plans to implement theme for default TabControl (not 3d-party)?

**Comment by ButchersBoy** [comment]
No. I have Dragablz which had still not got to version 1, so I don't want any extra duplication/overhead.

**Comment by Sergey-Terekhin** [comment]
But if MaterialDesignInXamlToolkit project is considered as theme for "vanilla" wpf controls, it would be great to provide themes for all built-in controls
I can try to port one from Dragablz and create PR

**Comment by ButchersBoy** [comment]
I've already turned one PR down. The dragablz style isn't fully complete. Maybe when dragablz gets to version 1, at that point.

**Comment by Sergey-Terekhin** [comment]
Ok

**Comment by ButchersBoy** [comment]
...if you wanted to help push things along, bottom and right placement is missing in Dragablz...
