### ISSUE TITLE
ContextMenu Not Getting MaterialDesignMenu Style

### ISSUE THREAD

**Issue by eleandro83** [ButchersBoy/MaterialDesignInXamlToolkit#180]
I Have Implemented a Context Menu In a DataGrid And The ContextMenu Os Getting MahApps Default MenuStyle, i Dont Make Any Change On Resources.

. Other: MenuItem SubMenu Child Is Getting a Transparent Background. Whats Happening?

**Comment by ButchersBoy** [comment]
Context menu is pre release. Are you using pre release package?

**Comment by eleandro83** [comment]
. I Dont Know, How Can I See What Package Im Using?

**Comment by ButchersBoy** [comment]
Make sure you select "Include Pre Release" somewhere, in either the nuget UI or the nuget command line.

**Comment by eleandro83** [comment]
. Ok
