### ISSUE TITLE
Im Unable To Compile MaterialDesignSourceCode With VisualStudio 2015

### ISSUE THREAD

**Issue by eleandro83** [ButchersBoy/MaterialDesignInXamlToolkit#181]
Im Unable To Compile MaterialDesignSourceCode With VisualStudio 2015, i Dont almoedar Why... I Just Extract The Project, Open, And Try Compile. Im Getting a Lot Of Errors. Why?

**Comment by ButchersBoy** [comment]
Did you restore packages? What errors?

**Comment by eleandro83** [comment]
. No, I Did'nt... Is Necessary? Thats Source Dont Include All Files?

**Comment by eleandro83** [comment]
. The Namespace MahApps Could Not Be Founded
. The Namespace Xunit Could Not Be Founded
. The name InitializeComponent does not exists in the current context

. And Others 113 Errors And 28 Warning

**Comment by eleandro83** [comment]
. Now i Cant Restore Package: An Error Occure While Trying To Restore Packages: 4.2.1510.2205 of Package 'Moq'.

The Same Is Happen With Others Packages Like MahApps. Its Not a Network Problem

**Comment by ButchersBoy** [comment]
Nuget restore. Packages are needed for the mashup demo.

**Comment by ButchersBoy** [comment]
Maybe it's a nuget problem...nuget is like that..

**Comment by eleandro83** [comment]
. So, Can You Upload The Demos Project And Send Me Please?

**Comment by ButchersBoy** [comment]
No, sorry...Don't mean to be unhelpful, but a) it's Christmas, b) all the code is there. You need to investigate and resolve your nuget issues.  There are plenty of other people using the source without issue.

**Comment by ButchersBoy** [comment]
I've uploaded the demo as part of the latest release.

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/releases/tag/v1.3.0

You'll find it a lot easier though if you compile and explore the demo source.  Maybe your proxy is blocking nuget and you need to configure that?

**Comment by eleandro83** [comment]
Its Working Now, Was a NutGet Problem. Thanks
