### ISSUE TITLE
Disable system menu buttons while dialog display

### ISSUE THREAD

**Issue by takuya-takeuchi** [ButchersBoy/MaterialDesignInXamlToolkit#182]
Hi James.
I want to know correct or recommended implements to disable system menu buttons; close, minimum and maximum, while dialog is present.

Now, DialogHost class does not take care these buttons state.
So I wrote the following codes in xaml.

```xaml
<controls:MetroWindow x:Class="Sample.MainWindow"
                      Title="{Binding Title}"
                      Width="1200"
                      Height="800"
                      IsEnabled="{Binding ElementName=_DialogHost,
                                          Path=IsOpen,
                                          Converter={StaticResource BooleanReverseConverter}}"

...

    <materialDesign:DialogHost x:Name="_DialogHost" Identifier="RootDialog">
```

But I can not decide this xaml is good or bad.
Is there any good implements to carry out my requirement?

Thank you for your cooperation.

**Comment by ButchersBoy** [comment]
Probably as good as any method right now :)
