### ISSUE TITLE
Fix Height for ProgressBar

### ISSUE THREAD

**Issue by 4ipalino** [ButchersBoy/MaterialDesignInXamlToolkit#183]
Hi,

i tried to make my Progressbar a bit larger. After some research i found that it is a fix Value of 4:

```
<Grid x:Name="TemplateRoot" RenderTransformOrigin="0,0.5" Opacity="0" Height="4">
```

Could that be changed to be more flexible?

**Comment by ButchersBoy** [comment]
...yeah can probably fix that.

**Comment by ButchersBoy** [comment]
Hi, I'm considering this low priority right now.  Suggested workaround is to expand it via a ```ViewBox``` whilst you are waiting.

**Comment by ButchersBoy** [comment]
This is now supported.
