### ISSUE TITLE
Create a menu list control

### ISSUE THREAD

**Issue by SCKelemen** [ButchersBoy/MaterialDesignInXamlToolkit#184]
I'm looking for a control like a circle button (action button) with a '+' (addition sign ) that rotates into in × (multiplication sign or x) and flys out a list of menu items (per google, only 3-6 items)
https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button

**Comment by ButchersBoy** [comment]
1.3 has that...did you check the demo?

**Comment by SCKelemen** [comment]
I did, I didn't see it. I'll double check.

**Comment by SCKelemen** [comment]
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/raw/master/web/images/MultiFloatingActionButton.gif
