### ISSUE TITLE
Bug Display with TextBox ValidationRules in DialogBox

### ISSUE THREAD

**Issue by Irtovic** [ButchersBoy/MaterialDesignInXamlToolkit#187]
Hi and happy new year,

![dialogtextbox](https://cloud.githubusercontent.com/assets/16349426/12092005/d3b27916-b2fa-11e5-8f20-d61f534fed35.png)

I've bug when i try to make ValidationRule on DialogBox.
Any idea ?

Thanx

**Comment by ButchersBoy** [comment]
Have you set ```ValidationAssist.UsePopup="True" ```?

If so, you might want to turn it off in this scenario.

**Comment by Irtovic** [comment]
No, i just wrote this code in my usercontrol
```
<TextBox wpf:TextFieldAssist.Hint="Raison Sociale" Style="{DynamicResource MaterialDesignFloatingHintTextBox}" FontSize="16" Margin="0 0 0 0">
  <TextBox.Text>
    <Binding Path="Etablissement.RaisonSociale" UpdateSourceTrigger="PropertyChanged">
      <Binding.ValidationRules>
        <validation:NotEmptyValidationRule ValidatesOnTargetUpdated="True" />
      </Binding.ValidationRules>
    </Binding>
  </TextBox.Text>
</TextBox>
```

**Comment by ButchersBoy** [comment]
So you hit "Cancel" and the error stays?

**Comment by ButchersBoy** [comment]
Is your view model for the dialog the same as the parent view model?

**Comment by Irtovic** [comment]
for Cancel the error stays
and no, not the same view model
i try in my project and in MaterialDesignDemo and the display error is the same

**Comment by ButchersBoy** [comment]
OK

**Comment by Irtovic** [comment]
in sample 3, with extended method, there's no bug, just when the dialog open, sometime the red text is very little and when mouse over it will be displayed correctly (for all samples)

**Comment by ButchersBoy** [comment]
hmmm...i'm guessing the storyboard growing the dialog screen into view isn't playing nice with the validation display.  Could be problematic.  Could even be an issue with WPF.

Could you try disabling transitions, as described [here](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/Performance) and reporting back?

**Comment by Irtovic** [comment]
I try disable transition, same bug.

**Comment by ButchersBoy** [comment]
Should be fixed in latest pre-release:

https://www.nuget.org/packages/MaterialDesignThemes/1.3.2-ci424

**Comment by Irtovic** [comment]
Works fine, thanx for your fix.

**Comment by ButchersBoy** [comment]
:+1:
