### ISSUE TITLE
Run animation before action

### ISSUE THREAD

**Issue by Ashwani44** [ButchersBoy/MaterialDesignInXamlToolkit#190]
I am using material design xaml toolkit in my current WPF project.
I have one button, on click of that button a new window gets open
Everything is fine only problem i have is... on clicking the button the ripple effect of button is occurring after my window is loaded . i want to run the ripple effect on my button click  at least for 0.1 sec so that user can see that ripple effect on my button and then my window should get open. please suggest me .. how do i fix it ??

**Comment by ButchersBoy** [comment]
Your problem will be that the click happens on the dispatcher, and you are opening the Window on the dispatcher, effectively queuing the animation.

In your case your can probably do something like this to open the new window:

```
Task.Delay(TimeSpan.FromMilliseconds(100)).ContinueWith(t =>
            {
                
                //open Window here

            }, TaskScheduler.FromCurrentSynchronizationContext());
```

**Comment by Ashwani44** [comment]
Thank you so much it works...

**Comment by ButchersBoy** [comment]
:+1:
