### ISSUE TITLE
MaterialDesignThemes.MahApps VS MahApps Version

### ISSUE THREAD

**Issue by Pagina** [ButchersBoy/MaterialDesignInXamlToolkit#191]
I download MaterialDesignThemes.MahApps V0.0.3.0 and MahApps V1.1.3.257 from nuget and run my aplication It is OK, 
but when I use  MahApps V1.2.0, I always get exception
"Can not load MahApps.Metro HRESULT:0x80131040)":"MahApps.Metro, PublicKeyToken=null"，

I download source code from github and find MaterialDesignThemes.MahApps have a packages.config file use   
package id="MahApps.Metro" version="1.1.3-ALPHA177" targetFramework="net45" 

Is this problem?

**Comment by SCKelemen** [comment]
Are you using VS14.0?

**Comment by Pagina** [comment]
I use VS2013

**Comment by ButchersBoy** [comment]
Hi, are you targetting .net 4.0?

If so please see: https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/.Net-4.0-Compatibility 

Anyone who wants to help out on that branch would be welcome!

**Comment by WinnieDave** [comment]
Hi,I am just a beginning 14-years-old programmer,so I don't think I can help you with your project a lot.I am just starting to learn things like git and github,but those cool icons and user controls were very helpful in my first project(simplified email client).Gonna upload it to github soon,so you can check it out in a few days.




.

-------- Оригінальне повідомлення --------
Від: James Willock <notifications@github.com> 
Дата:08.01.2016  09:09  (GMT+00:00) 
Кому: ButchersBoy/MaterialDesignInXamlToolkit <MaterialDesignInXamlToolkit@noreply.github.com> 
Тема: Re: [MaterialDesignInXamlToolkit] MaterialDesignThemes.MahApps VS
  MahApps Version (#191) 

Hi, are you targetting .net 4.0?

If so please see: https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/.Net-4.0-Compatibility

Anyone who wants to help out on that branch would be welcome!

**Comment by ButchersBoy** [comment]
@WinnieDave good luck with your adventures!

@Pagina ..are you still having issues?  As this isn't strictly a bug I'm closing this issue.  If you need some help please ask on Gitter: https://gitter.im/ButchersBoy/MaterialDesignInXamlToolkit
