### ISSUE TITLE
Bug with floating hint

### ISSUE THREAD

**Issue by svstoichkov** [ButchersBoy/MaterialDesignInXamlToolkit#193]
Hello! I found a small bug.

This is how to the floating hint appears after switching views

http://i.imgur.com/Ku4ciro.png

**Comment by ButchersBoy** [comment]
Can you clarify what you mean by "switching views"?  Or post a sample please.

Thanks

**Comment by svstoichkov** [comment]
Using the flyout menu to go to another view and getting back to the one where the floating hints are

**Comment by ButchersBoy** [comment]
OK.  Can you post a small sample repo please?

**Comment by svstoichkov** [comment]
You can see the bug in action in your own demo app.

Go to Fields
write something in the first floating hint textbox
go to another view
go back to fields

you can see the bug now

**Comment by svstoichkov** [comment]
The second textbox with floating hint has initial text value set and doesn't have this problem

**Comment by svstoichkov** [comment]
ComboBox is still having the same problem

**Comment by ButchersBoy** [comment]
Ok...think it should be a quick fix
