### ISSUE TITLE
Use CacheMode="BitmapCache" for borders that include effects

### ISSUE THREAD

**Issue by xaviergonz** [ButchersBoy/MaterialDesignInXamlToolkit#197]
In order to improve rendering speed by a lot (since effects such as shadow effects are slow, consider changing stuff like this
                        <Border Background="{TemplateBinding Background}" 
                                x:Name="ShadowBorder"                                                                
                                Effect="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=(wpf:ShadowAssist.ShadowDepth), Converter={x:Static converters:ShadowConverter.Instance}}"/>

To this:
                        <Border Background="{TemplateBinding Background}" 
                                x:Name="ShadowBorder"                                                                
                                Effect="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=(wpf:ShadowAssist.ShadowDepth), Converter={x:Static converters:ShadowConverter.Instance}}" CacheMode="BitmapCache"/>

Note the addition of CacheMode="BitmapCache"

That way the effect itself will be cached on a texture on videoram and it wont need to be re-rendered with pixel shaders everytime (and also probably help a lot with the rendering lag on situations like on the demo app when you open the side menu)

**Comment by ButchersBoy** [comment]
OK; when I get chance I'll try this out on my laptop with QHD screen...it's a lot more taxing on the animations.

**Comment by xaviergonz** [comment]
I made a pull request with it implemented in case you want to try it out.
