### ISSUE TITLE
TimePicker : Set system hour

### ISSUE THREAD

**Issue by furiousbuilder** [ButchersBoy/MaterialDesignInXamlToolkit#20]
Hi, I'm trying to set at the startup of my application the system time to the TimePicker control.
I tryed TrainingTimePicker.SelectedTime = DateAndTime.Now (where TimePicker is my control) but it don't work, te field still empty. 
Can I know why please ? I'm in VB.Net

**Comment by ButchersBoy** [comment]
What's not displaying correctly? The text box or the main picker?

**Comment by furiousbuilder** [comment]
The textbox is empty, I still have "Select time" :/

**Comment by ButchersBoy** [comment]
Hi, I reproduced the issue...fix is just building, look-out for nuget package 0.0.0.65.  Let me know if it solves it in your code base.

**Comment by furiousbuilder** [comment]
Thanks, I'll try this tomorrow and I say if it's corrected :) 
Another issue on timepicker : changing the Foreground isn't changing the color of the number so if I set Black theme on MahApps, I can't read the numbers, even with the line "TimePicker.Foreground = Brushes.Black" like in the screenshot
![capture d ecran 64](https://cloud.githubusercontent.com/assets/10899984/7672169/bbc0948c-fce8-11e4-866a-d4ec9cec5fdb.png)

**Comment by ButchersBoy** [comment]
re. "Select time".  I'll get that added to the TextField.Hint thing so you can change it. I've added a new issue so you can track: https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/21 

re. Colours...I've documented how to get MahApps using a Material Design palette, but I'll need to have a look at a nice way of making sure Material Design controls work nicely when using Mah Apps light/dark accents.

**Comment by furiousbuilder** [comment]
Every thing is working fine now ! Thank you so much, your work is amazing ! :D Where can I find the documentation to change the foreground of your controls ? DatePicker is working fine with DatePicker.Foreground = Brushes.Black but not the TimePicker

**Comment by ButchersBoy** [comment]
OK...if DatePicker is working butTimePicker not, I should be able to fix it easy.  Log another issue so I don't forget and I'll get to it.
