### ISSUE TITLE
Assembly 'x' is not referenced by this project

### ISSUE THREAD

**Issue by SuplenC** [ButchersBoy/MaterialDesignInXamlToolkit#210]
I started a new project using your dll for 4.0. So I added references on already created project and it gives me these errors in App.xaml:
    Assembly 'MaterialDesignThemes.Wpf' is not referenced by this project
    Assembly 'MaterialDesignColors' is not referenced by this project

after adding all resource dictionaries.
And right now after searching for an issue I have no clue what to do.

**Comment by ButchersBoy** [comment]
You references definitely setup properly?  What's you app.xaml look like?

![image](https://cloud.githubusercontent.com/assets/658107/12325962/b0436dfa-bac5-11e5-99f9-9f9b4609bf67.png)

**Comment by SuplenC** [comment]
![application](https://cloud.githubusercontent.com/assets/14072225/12326008/6a600560-bace-11e5-9512-ce31dc99a085.PNG)
![app](https://cloud.githubusercontent.com/assets/14072225/12326009/6a60d490-bace-11e5-89d2-251d5a7b1bce.PNG)

**Comment by ButchersBoy** [comment]
Does it actually run?  (Particularly after Cleaning you build etc)

**Comment by SuplenC** [comment]
I was updating my comment just now. Yes it does launch without any problem and when I launch it, it does work normally. Material Design Style with colors applies normally. But it gives that error and it doesn't work on preview.

**Comment by ButchersBoy** [comment]
...which .dlls are these?  You might be best to manually compile the latest from the net40 branch...just looking the last time I released compiled .Net 4.0 .dlls whas version 1.1

**Comment by ButchersBoy** [comment]
"preview"  That's Visual Studio, WPF, and XAML for you...

:)

**Comment by SuplenC** [comment]
I did downloaded this dlls from branch today. I think the latest 4.0 version is 1.2 but I'm not sure.

**Comment by SuplenC** [comment]
I saw that there are .pdb files in there. Maybe I should include them in some way?

**Comment by ButchersBoy** [comment]
You shouldn't have to.

**Comment by SuplenC** [comment]
Ok I did it. I did like you said. Downloaded branch and compiled it on my PC. After this it works now correctly. Thanks for the help!

**Comment by ButchersBoy** [comment]
:+1:
