### ISSUE TITLE
Hide underline in textbox

### ISSUE THREAD

**Issue by JamesIrish** [ButchersBoy/MaterialDesignInXamlToolkit#212]
Hi James,

Can we please have a `TextFieldAssist` property or template(s) that hide the underline from textboxes.   This would smarten the appearance of the textfield when used within a Colour Zone.  e.g. see 3rd colour zone in the the demo app.   

It would match more closely to the search fields used with various Google applications - Maps,  Inbox etc.

Many thanks

**Comment by ButchersBoy** [comment]
...yeah...been meaning to do that one.  Now you've made it official...

**Comment by ButchersBoy** [comment]
The TextBox styles adhere to the Border property.  Therefore usage will be:
```
<TextBox materialDesign:TextFieldAssist.DecorationVisibility="Hidden" BorderThickness="0" />
```
