### ISSUE TITLE
Floating hint not floating

### ISSUE THREAD

**Issue by barucAlmaguer** [ButchersBoy/MaterialDesignInXamlToolkit#218]
I found an issue in the MaterialDesignDemo,
In the Fields View, when you start writing in a TextBow with floating hint it looks great:
![Floating](http://i.imgur.com/zrpijIA.png)
But when you change to another view and go back to Fields, the hint is not floating (It stays in the same place as the text, so it's hard to read):
![Not floating](http://i.imgur.com/BM9ZJdq.png)

The problem fixes when you modify the text, as the animation to float the hint begins.

**Comment by ButchersBoy** [comment]
This is a duplicate, closing.

**Comment by ButchersBoy** [comment]
P.S make sure your are running latest

**Comment by barucAlmaguer** [comment]
Yes, I am now running with the latest version (With the icon pack) and it's fixed, 
thank you

**Comment by ButchersBoy** [comment]
Closing as this is not an issue, but a query, and we have a discussion on SO: http://stackoverflow.com/questions/34830946/wpf-material-design-dragablz-tabitem-header-style/34838515#34838515
