### ISSUE TITLE
Link to Universal Example is broken since it was deleted.

### ISSUE THREAD

**Issue by MizzleMo** [ButchersBoy/MaterialDesignInXamlToolkit#22]
Can't follow the documentation.

**Comment by itechy21** [comment]
+ One this needs a fiz

**Comment by ButchersBoy** [comment]
UWP will return...

**Comment by abbottdev** [comment]
@ButchersBoy  is there a breakdown you can give for the UWP work? I'm happy to contribute if you could share some info. I had a look and looks like there's outstanding merge conflicts?

**Comment by ButchersBoy** [comment]
@abbottdev thanks for the offer...I'm just getting the UWP version off the ground and really want to make sure I'm happy with the structure and direction.  I think part of the success of the WPF version is that it's easy for people to use and has good conventions.  And in a selfish manner I'm also using it as an opportunity to learn some new stuff. 

Once I'm happy with how the UWP stuff is going I'll divvy out some tasks.  Probably smaller ones at first as I'm a bit of a control freak, and I want my baby :baby: to grow to be a healthy citizen.

The WPF stuff is further along and there are some very specific jobs that I want sorted which I can tag up...

(The merge mess is now sorted)

**Comment by SuicSoft** [comment]
How about removing the universal example from ReadMe.md and replacing it with the UWP example to prevent confusion

**Comment by ButchersBoy** [comment]
Yeah removed it completely for now; it will return when I make more progress on UWP.
