### ISSUE TITLE
Flyout header not collapsed properly

### ISSUE THREAD

**Issue by mgnslndh** [ButchersBoy/MaterialDesignInXamlToolkit#220]
Changing the following attributes on the flyout in the demo will cause it to render the header when it should be collapsed:

    TitleVisibility="Collapsed" CloseButtonVisibility="Collapsed" Background="Red"

![image](https://cloud.githubusercontent.com/assets/1139118/12387101/5f937adc-bdca-11e5-8fdc-ac66d042d9c2.png)

I would have expected the whole flyout being red since there should not be any close button or header visible.

**Comment by mgnslndh** [comment]
I will investigate if this is an issue using MahApps only.

**Comment by mgnslndh** [comment]
Using the same attributes with plain MahApps I do get a completely red background:

![image](https://cloud.githubusercontent.com/assets/1139118/12387629/20a21c30-bdce-11e5-98f5-944522a8494b.png)

**Comment by ButchersBoy** [comment]
And the vanilla MahApps left flyout?

**Comment by ButchersBoy** [comment]
You can use ```mahApps:FlyoutAssist.HeaderColorMode``` on the Flyout to control that whitespace colour...presuming you set the Background to a standard colour from the Material Design palette so that you can get a match.

The problems is the title and close button are in a dock panel which never collapses.  This is true in vanilla MahApps and Material Design.  The difference is in Material Design is that the dock panel is wrapped in a ```ColorZone```...

**Comment by mgnslndh** [comment]
Left flyout also works in vanilla MahApps:

![image](https://cloud.githubusercontent.com/assets/1139118/12387924/0a4a5342-bdd0-11e5-923c-8d343d725fe2.png)

**Comment by mgnslndh** [comment]
I tried to apply the visibility of TitleVisibility to the colorzone and it gives me a whole red background. Plus bit more whitespace than I would expect, not sure why though. 

![image](https://cloud.githubusercontent.com/assets/1139118/12387952/33456a70-bdd0-11e5-8727-91e73b413b32.png)

**Comment by ButchersBoy** [comment]
Have you tried something like this?
```
<ns1:Flyout TitleVisibility="Collapsed" CloseButtonVisibility="Collapsed" Background="{DynamicResource PrimaryHueLightBrush}" ns2:FlyoutAssist.HeaderColorMode="PrimaryLight" />
```

Make sure you set *ns1* and *ns2* according to your code base.

**Comment by mgnslndh** [comment]
I am using the flyout for a snackbar with a custom color.

![image](https://cloud.githubusercontent.com/assets/1139118/12388133/56477f08-bdd1-11e5-9910-e3ac282b7ceb.png)

The properties are set from code like this:

```
if(viewModel is SnackbarViewModel)
{                                
                flyout.Focusable = false;
                flyout.FocusVisualStyle = null;
                flyout.FocusedElement = null;
                flyout.AllowFocusElement = false;                
                flyout.Background = (SolidColorBrush)flyout.FindResource("MaterialDesignSnackbarBackground");
                flyout.Foreground = (SolidColorBrush)flyout.FindResource("MaterialDesignSnackbarForeground");
}
```

I guess could do what you suggest from code as well.

**Comment by mgnslndh** [comment]
This works and give me a nice snackbar using the dark primary colour:

```
MaterialDesignThemes.MahApps.FlyoutAssist.SetHeaderColorMode(flyout, MaterialDesignThemes.Wpf.ColorZoneMode.PrimaryDark);
flyout.Background = (SolidColorBrush)flyout.FindResource("PrimaryHueDarkBrush");
```
![image](https://cloud.githubusercontent.com/assets/1139118/12388488/77acd7fe-bdd3-11e5-921a-1193098ad375.png)

I would however like to use a blackish/greyish snackbar. I will try to find the brush that correlate to the enum `ColorZoneMode.Dark`

**Comment by ButchersBoy** [comment]
Hint on brushes here: 

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/Generic.xaml#L411

As discussed I guess some better documentation would help around all brush names.

**Comment by mgnslndh** [comment]
I guess this problem boils down to using a custom background on the flyout that is not part of the `ColorZoneMode` brushes? Perhaps this should be mentioned in the wiki. 

Something like this perhaps:

Using a custom background on the flyout when no title or close button is visible limits you to the brushes corresponding to the `ColorZoneMode`

**Comment by ButchersBoy** [comment]
To be exact, it limits you to your Material Design palette.  Which isn't necessarily a bad thing...

**Comment by ButchersBoy** [comment]
Note also, a custom snack bar control may arrive at some point, as this is in the Google spec.

**Comment by mgnslndh** [comment]
I added this to the wiki:

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/MahApps.Metro-integration#known-issues-1

Nice to have a snack bar control included in the toolkit!

**Comment by ButchersBoy** [comment]
Thanks.
