### ISSUE TITLE
Brush resources for ColorZoneMode.Light and ColorZoneMode.Dark

### ISSUE THREAD

**Issue by mgnslndh** [ButchersBoy/MaterialDesignInXamlToolkit#221]
There are four hardcoded brushes used for `ColorZoneMode` that would be nice to have available for easier styling and reuse.

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/Generic.xaml:

```
<Trigger Property="Mode" Value="Light">
    <Setter Property="Background" Value="#FFfafafa" />
    <Setter Property="Foreground" Value="#DD000000" />
</Trigger>
<Trigger Property="Mode" Value="Dark">
    <Setter Property="Background" Value="#FF37474f" />
    <Setter Property="Foreground" Value="#DDFFFFFF" />
</Trigger>
```

Suggested names are (not sure if the clash with anything):

- MaterialDesignLightBackground
- MaterialDesignLightForeground
- MaterialDesignDarkBackground
- MaterialDesignDarkForeground

In my specific case It would be nice to have these brushes as resources since I need to style a flyout with a dark color and need to use a brush from the `ColorZoneMode` (see #220)

**Comment by ButchersBoy** [comment]
These will get added to ```MaterialDesignTheme.Defaults.xaml``` as this is the only common dictionary.
