### ISSUE TITLE
Storyboard issue in the ProgressBar templates

### ISSUE THREAD

**Issue by spiegelp** [ButchersBoy/MaterialDesignInXamlToolkit#224]
The debugger logs the following message if the style MaterialDesignCircularProgressBar is used:

System.Windows.Media.Animation Warning: 6 : Unable to perform action because the specified Storyboard was never applied to this object for interactive control.; Action='Remove'; Storyboard='System.Windows.Media.Animation.Storyboard'; Storyboard.HashCode='18055228'; Storyboard.Type='System.Windows.Media.Animation.Storyboard'; TargetElement='System.Windows.Controls.ProgressBar Minimum:0 Maximum:100 Value:0'; TargetElement.HashCode='4391366'; TargetElement.Type='System.Windows.Controls.ProgressBar'

**Comment by ButchersBoy** [comment]
Thinking back, this was all very tricky, and kind of stretching styling to the limit using the ProgressBar without any kind of inheritance (or assist).  There were some cases where the animations just weren't triggering or switching over, so I had to add a "belt and braces" removal of one of the story boards.

So I think we just have to live with this for now.

**Comment by julesx** [comment]
gahhh! that spam output drives me crazy!
