### ISSUE TITLE
Changing DialogHost's FontFamily won't work

### ISSUE THREAD

**Issue by hshahdoost** [ButchersBoy/MaterialDesignInXamlToolkit#226]
Card element within **DialogHost** uses **MaterialDesignFont** directly, Which makes **DialogHost** **FontFamily** property useless. If the property was set on the element's style and used by **TemplateBinding** it would be possible to change the font on **DialogHost**.
It would look something like this

```xaml
<Style TargetType="{x:Type local:DialogHost}">
	<Setter Property="FontFamily" Value="MaterialDesignFont" />
	<Setter Property="Template">
		<Setter.Value>
			<ControlTemplate TargetType="local:DialogHost">
			...
				<local:Card x:Name="PART_PopupContentElement" 
						...
						FontFamily="{TemplateBinding FontFamily}"
```

**Comment by ButchersBoy** [comment]
Without testing we have to consider that DialogHost is in fact a ContentControl.  So what that in fact refers to is the tree inside the DialogHost, not what is displayed in the dialog itself.

**Comment by hshahdoost** [comment]
I think the normal behavior is to set the FontFamily on the ContentControl (which is now DialogHost) to set it for all child elements.
Plus that way the user should either assign the FontFamily on every content in the DialogHost or use DialogContentTemplate to set the FontFamily
