### ISSUE TITLE
"Could not load file or assembly" error after after nuget upgrade

### ISSUE THREAD

**Issue by HalidCisse** [ButchersBoy/MaterialDesignInXamlToolkit#229]
```Could not load file or assembly 'MahApps.Metro, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)```

After adding : 
```
<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.MahApps;component/Themes/MaterialDesignTheme.MahApps.Flyout.xaml" />
```

MahApps.Metro 1.2.4 installed

**Comment by evilz** [comment]
+1

**Comment by GorelH** [comment]
+1

**Comment by ButchersBoy** [comment]
Updated the package to 0.0.4...please test and report back.

https://www.nuget.org/packages/MaterialDesignThemes.MahApps/0.0.4

**Comment by HalidCisse** [comment]
Fixed !!
