### ISSUE TITLE
Add TextFieldAssist.HintFontSize

### ISSUE THREAD

**Issue by mgnslndh** [ButchersBoy/MaterialDesignInXamlToolkit#230]
The size of a `TextBox` hint is hardcoded to 10 ([see example](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/b21355c18820a8058527a966ad2294ce15376465/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml#L127))

 It would be nice to be able to control this size through an attached property like this:

```
<TextBlock mdt:TextFieldAssist.Hint="Name" mdt:TextFieldAssist.HintFontSize="18" FontSize="24"/>
```

**Comment by ButchersBoy** [comment]
...I wonder if it should actually driven from the normal FontSize??

**Comment by FireNero** [comment]
I think that attached property is more flexible solution and it's also easy to use. 
Or even better if the hint font size will be driven from normal FontSize until attached property is specified.

**Comment by mgnslndh** [comment]
I agree with @FireNero. Default should derive from normal `FontSize` until overridden by `TextFieldAssist.HintFontSize`

**Comment by sagevpremium** [comment]
Hi, is something new with this case?

**Comment by ButchersBoy** [comment]
@sagevpremium still outstanding i think
