### ISSUE TITLE
Dialog/Drawer Host does not receive focus.

### ISSUE THREAD

**Issue by amoamare** [ButchersBoy/MaterialDesignInXamlToolkit#232]
If a DialogHost or a DrawerHost is shown and the user moves to another application and it loses focus, when they return to the application it does not get focus anymore and you can not type how ever the buttons do work except the app still does not get focus. You must click on the top bar to regain focus on the application to be able to interface with it.

**Comment by ButchersBoy** [comment]
Fixed for dialog.  Couldn't repro' for drawer.  But there are some little drawer improvements in the pipeline.
