### ISSUE TITLE
DialogHost on focus buttons not enabled.

### ISSUE THREAD

**Issue by amoamare** [ButchersBoy/MaterialDesignInXamlToolkit#235]
Can be repeated in demos app Dialogs -> Sample 1
Click on add to add a new fruit. If you leave application to another application and return focus directly to add a new fruit it works fine. 

If you click some where else in the application and the host loses focus the buttons do not get enabled. Opening a new host dialog say pass view will enable the buttons but they interact with pass view dialog. 

![focus](https://cloud.githubusercontent.com/assets/15149902/12624560/94476754-c4e4-11e5-81f4-c1e46b0ff7f7.PNG)

![focus2](https://cloud.githubusercontent.com/assets/15149902/12624569/9e800fdc-c4e4-11e5-97f4-b953e9105be1.PNG)

**Comment by ButchersBoy** [comment]
Wierd :confused:

**Comment by ButchersBoy** [comment]
Think I got it.
