### ISSUE TITLE
Toggle buttons for exclusive and multiple selection

### ISSUE THREAD

**Issue by mgnslndh** [ButchersBoy/MaterialDesignInXamlToolkit#236]
Implement control/style for toggle buttons that can be used for exclusive and multiple selection as per Googles [guidelines](https://www.google.com/design/spec/components/buttons.html#buttons-toggle-buttons)

@ButchersBoy suggested a style for the `ListBox` control.

## Exclusive selection

![image](https://cloud.githubusercontent.com/assets/1139118/12629125/bb0d2bf0-c546-11e5-8828-de13735030f0.png)

## Multiple selection

![image](https://cloud.githubusercontent.com/assets/1139118/12629130/c28392a2-c546-11e5-83a5-d7d23335d0de.png)

**Comment by ButchersBoy** [comment]
Incoming...

![image](https://cloud.githubusercontent.com/assets/658107/15632660/62a9d3f4-2591-11e6-8917-9a3aace547da.png)

No drop down component as of yet.

**Comment by ButchersBoy** [comment]
Gonna tweak at some point cos it can be a pixel out, but marking as done.
