### ISSUE TITLE
Close/cancel dialog by clicking in background overlay

### ISSUE THREAD

**Issue by tempywritescode** [ButchersBoy/MaterialDesignInXamlToolkit#238]
It would be a nice addition to the dialog API to allow clicks or taps on the gray overlay that's displayed behind a dialog to be interpreted as cancel or close. Basically what the drawer does.

**Comment by GorelH** [comment]
+1

**Comment by ButchersBoy** [comment]
New ```CloseOnClickAway``` property added.
