### ISSUE TITLE
PopupBox.StaysOpenOnEdit doesn't seem to work

### ISSUE THREAD

**Issue by koffmoff** [ButchersBoy/MaterialDesignInXamlToolkit#241]
A PopupBox with StaysOpenOnEdit=true and StaysOpen=true, containing a CheckBox does not stay open when the CheckBox is clicked.

I just modified the PopupBox from MaterialDesignDemo so it looks like this:

```xaml
<materialDesign:PopupBox DockPanel.Dock="Right" PlacementMode="BottomAndAlignRightEdges" StaysOpenOnEdit="True" StaysOpen="True">
    <StackPanel>
        <Button Content="Hello World" Click="MenuPopupButton_OnClick"/>
        <Button Content="Nice Popup" Click="MenuPopupButton_OnClick"/>
        <Button Content="Goodbye" Click="MenuPopupButton_OnClick"/>
        <CheckBox>Check me</CheckBox>
    </StackPanel>
</materialDesign:PopupBox>            
```

But the PopupBox closes immediately when the CheckBox is clicked.

Have I misunderstood anything or is this a bug?

**Comment by ButchersBoy** [comment]
Probably a bug.

**Comment by ButchersBoy** [comment]
```StaysOpenOnEdit``` marked as obsolete (damnit, first time I've had to do that).

Prefer ```StaysOpen```
