### ISSUE TITLE
Can you create outlookNavBarControl?

### ISSUE THREAD

**Issue by valeravorobjev** [ButchersBoy/MaterialDesignInXamlToolkit#247]

**Comment by ButchersBoy** [comment]
Which one?

**Comment by valeravorobjev** [comment]
For example http://docs.telerik.com/devtools/wpf/controls/radoutlookbar/overview
This control isnt standart

**Comment by ButchersBoy** [comment]
This isn't strictly part of Material Design.

I'll do it for cold hard cash :wink:

**Comment by Ch4rg3r** [comment]
IIRC if found an Outlook styled navbar on search a few weeks ago. Not sure if it's WPF compatible, but if, you only need to template it. Should be possible with the source of MaterialDesignInXAML

**Comment by SCKelemen** [comment]
I'll do it for cold hard cash, too.
