### ISSUE TITLE
Please add some sort of LED bool control.

### ISSUE THREAD

**Issue by bebenins** [ButchersBoy/MaterialDesignInXamlToolkit#253]
Basically a checkBox but instead it should be round and no check mark inside.  IMO would be very useful for those who work on HW controls.
Thanks!

**Comment by beto-rodriguez** [comment]
@bebenins I think you need to include an image of your control, and dont forget this library is based on material design https://www.google.com/design/spec/material-design/introduction.html, I think that control should only be included if it is in material design docs.

**Comment by bebenins** [comment]
![capture](https://cloud.githubusercontent.com/assets/16761301/12958250/c59a8e24-cffe-11e5-8f60-62fec70a51ce.PNG)

Something like this.,
I know that the library is based on MD and it's an amazing library but I don't believe MD prohibits more controls.  I mean, it's a simple control and does not go against anything in MD.  I simply doesn't exist because mobile devices don't really have the need for "status" LED.
I would love to use MD for Windows application that controls HW and a status LED is a must have.
