### ISSUE TITLE
4.0 Update

### ISSUE THREAD

**Issue by SuplenC** [ButchersBoy/MaterialDesignInXamlToolkit#259]
Could you update the 4.0 version? It lacks of some things (ex. Shadow Depth0) and it has some really minor bugs. I'm using it for a bit important project.

**Comment by ButchersBoy** [comment]
See: https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/.Net-4.0-Compatibility-&--Visual-Studio-Versions#net-40

I haven't got the capacity to maintain it.  I would happily accept a pull request if anyone wants to fix it up.
