### ISSUE TITLE
NullReference Exception in DialogHost.Show

### ISSUE THREAD

**Issue by ruslanfedoseenko** [ButchersBoy/MaterialDesignInXamlToolkit#261]
when I call await DialogHost.Show(someVM, DialogHostIdentity) I've gat an agregation exception with NullReferenceException in it
full stactrace
```
System.AggregateException: One or more errors occured. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   in MaterialDesignThemes.Wpf.DialogHost.IsOpenPropertyChangedCallback(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs dependencyPropertyChangedEventArgs)
   in System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   in System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   in System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   in System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   in System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   in System.Windows.DependencyObject.SetCurrentValue(DependencyProperty dp, Object value)
   in MaterialDesignThemes.Wpf.DialogHost.<Show>d__24.MoveNext()


```
The call is made from UI thread (command execute handler. I think it should be UI thread)
someVM has a datatemplate
```
<DateTemplate TargetType="{x:Type SomeVMType}">
<SomeVmView DataContext={Binding}/>
</DateTemplate>
```

**Comment by ButchersBoy** [comment]
Hey, do you have a repo to reproduce this?

**Comment by ruslanfedoseenko** [comment]
No problem from your side. 
Exception occured due to redefined style for DialogHost(Redefined it to disable shadowdepth as it has no effect, only cause load). In redefied template there is no element with name "PART_PopupContentElement" so _popupContentControl field is null. This cause the eception
But I think you could validate a template to have required data in ApplyTemplate.

**Comment by ButchersBoy** [comment]
OK.

I can probably get DialogHost to use ShadowAssist to save you re-templating.  If you desire raise an issue, cos it seems a reasonable requirement to help with performance.

**Comment by ruslanfedoseenko** [comment]
May be you understand me incorrectly. I removed the ShadowAssist.ShadowDepth. 
As the bacground is already shadowed and transparent.

**Comment by ButchersBoy** [comment]
OK.
