### ISSUE TITLE
TabControl and TabItem Styles

### ISSUE THREAD

**Issue by devriesb13** [ButchersBoy/MaterialDesignInXamlToolkit#263]
Can you please add a TabControl and TabItem style into the MaterialDesignThemes.WPF assembly?

**Comment by SuicSoft** [comment]
Have you tried Dragablz

**Comment by devriesb13** [comment]
Yes but it's not what i'm after in this instance. If i'm using the material design theme from NuGet, i think that styling within it should cover all std controls.

**Comment by SuicSoft** [comment]
It will then be a clone of Dragablz

**Comment by Sergey-Terekhin** [comment]
See the same issue #179 - it was closed by @ButchersBoy

**Comment by stefanofalasca** [comment]
Same problem

**Comment by ronnieoverby** [comment]
Agree that having to pull in dragablz is kind of a pain.

**Comment by david2020** [comment]
Same problem

**Comment by radoslawkosinski** [comment]
Is there any solution for this? Dragablz is cool but it would be really nice to have it included MaterialDesignInXaml
