### ISSUE TITLE
Unable to run Application even when following the user guide

### ISSUE THREAD

**Issue by GamingSabre** [ButchersBoy/MaterialDesignInXamlToolkit#268]
I have been following the [Getting Started](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/Getting-Started) guide and am able to run the application up to the point when I have to add the **_Primary_** and **_Accent_** colour into the App.xaml. When I add the Primary and Accent colour I get the following error when trying to run the application.
`"Set property 'System.Windows.ResourceDictionary.Source' threw an exception."`

The inner exception says this.

`"Could not load file or assembly 'MaterialDesignColors, Culture=neutral' or one of its dependencies. The system cannot find the file specified.":"MaterialDesignColors, Culture=neutral"`

I followed the exact steps and must have done it somewhat correct as it was able to compile the application but not run it. I hope someone has an idea what the problem could be and any solutions.

Thanks!

**Comment by SuicSoft** [comment]
@GamingSabre What is your target framework

**Comment by GamingSabre** [comment]
@SuicSoft I am using .Net 4.5

**Comment by ButchersBoy** [comment]
You definitely got the nuget packages installed, and you can see the references in your Solution Explorer?

**Comment by GamingSabre** [comment]
Yes I Have. I Jumped onto another machine and did the setup again and this time have been successful. I might have a problem specifically to my visual studio, so I guess I will fight on with that on my own. Just a quick question how do I change my window style to be like the one on your demo?

**Comment by ButchersBoy** [comment]
OK.  Closing this issue.  Please feel free to enter the chat room for more general questions: https://gitter.im/ButchersBoy/MaterialDesignInXamlToolkit

The main demo is just a normal Window (with a few XAML attributes applied)...the MashUp Demo is a MahApps MetroWindow.
