### ISSUE TITLE
Expander.Header doesn't inherit MaterialDesignTheme.Dark color changes

### ISSUE THREAD

**Issue by bebenins** [ButchersBoy/MaterialDesignInXamlToolkit#274]
If you have a card with Expander.Header and MaterialDesignTheme.Dark setting, this is what it looks like:

![capture](https://cloud.githubusercontent.com/assets/16761301/13402274/90823f78-dedd-11e5-9e79-2c4981344a26.PNG)

**Comment by SuicSoft** [comment]
👍

**Comment by lizarazu77** [comment]
nice
