### ISSUE TITLE
There's no focus animation when navigating to ComboBox via Tab button on the keyboard

### ISSUE THREAD

**Issue by bebenins** [ButchersBoy/MaterialDesignInXamlToolkit#277]
TextBox has that nice underline "explosion" going on.  Nothing happens to ComboBox line even though it's receives the focus.

**Comment by LoRdPMN** [comment]
This would be nice to have

**Comment by quicoli** [comment]
I'll take a look on it tomorrow
Em 20/04/2016 20:25, "Paulo Morábito Neto" <notifications@github.com>
escreveu:

**Comment by quicoli** [comment]
I believe the expected was this:

![combobox in action](http://g.recordit.co/rKqKCT8U2l.gif)

**Comment by bebenins** [comment]
Yes looks awesome!  Thanks
