### ISSUE TITLE
Issue with the Dialog host

### ISSUE THREAD

**Issue by sonyraj** [ButchersBoy/MaterialDesignInXamlToolkit#278]
Hi, thank you for sharing this awesome lib. I'm having problems with the "DialogHost" as it is closing the  dialog even if it is cancelled(e.Cancel()) and e.Handled = true. here is the "DialogClosingEventHandler" 

`private async void dialogClosingEventHandler(object sender, DialogClosingEventArgs e)
        {
            if ((bool) e.Parameter)
            {
                if (NewVehicle.isValid)
                {
                    if (await _vehicleDataAccessManager.checkVehiclesAsync(NewVehicle.vehicleName))
                    {
                        **e.Cancel();
                        e.Handled = true;
                        ErrorMessage = "vehicle with the name : " + NewVehicle.vehicleName + " already exists.";**
                        return;
                    }
                    if (SaveCommand.CanExecute(NewVehicle != null && (IsNewEntry || IsInEditMode)))
                    {
                        SaveCommand.Execute(null);
                    }
                }
                else
                {
                    e.Cancel();
                    e.Handled = true;
                    ErrorMessage = "Please fill the details.";
                }
            } else
            {
                if (CancelCommand.CanExecute(IsNewEntry || IsInEditMode))
                {
                    CancelCommand.Execute(null);
                }
            }
        }`

please look at that highlighted (bold) part. it is causing problems.

**Comment by ButchersBoy** [comment]
Looks to  me like you are running the event handler async, and therefore the internal flag that gets caught by calling ```.Cancel()``` is never noted, and the dialog continues to close.

**Comment by sonyraj** [comment]
yes i have to :-( is there any way to solve the issue. at present i'm showing an error dialog after the dialog is closed and then recreating the create dialog again with the same data entered before. (as a work around)

**Comment by ButchersBoy** [comment]
Hi, 

If the event is handled async, there is no way the lib can know that you called ```.Cancel()```

So, this is not a bug, you'll have to find a different way to do what you want to do.

**Comment by sonyraj** [comment]
@ButchersBoy Thnx man, again for the lib. I'll continue using the workaround
