### ISSUE TITLE
MaterialDesign Window Theme unavaliable ?

### ISSUE THREAD

**Issue by AshkoreDracson** [ButchersBoy/MaterialDesignInXamlToolkit#280]
I downloaded this package from Nuget to a new VS WPF project and did the standard setup.
The controls have the theme, but not the window itself, how do I add it to the window ?

**Comment by SuplenC** [comment]
The window style in the example is MahApps window. If you want to use it download [MahApps](https://github.com/MahApps/MahApps.Metro) and go to [Wiki](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/MahApps.Metro-integration) section to make it Material Design themed
