### ISSUE TITLE
Styles Intellisense

### ISSUE THREAD

**Issue by royben** [ButchersBoy/MaterialDesignInXamlToolkit#281]
Hi. Great Library!
What is the recommended way of getting the auto complete support for the library static resources while in xaml designer (VS2013)?

e.g: Style="{StaticResource MaterialDesignRaisedButton}"

Currently, I have to dig up in the source code.. Thanks!

**Comment by patchandthat** [comment]
Including these in App.xaml merged dictionaries sorted it for me.  Not sure if this is the accepted practice or whether there are performance pitfalls or whatever, but it works.  This is also probably not an exhaustive list.

```
<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.ComboBox.xaml" />
<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Slider.xaml" />
<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.TextBox.xaml" />
<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Button.xaml" />
<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.CheckBox.xaml" />
<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.ListBox.xaml" />
<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.RadioButton.xaml" />
<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.ToggleButton.xaml" />
```

**Comment by royben** [comment]
Thank you for the response. I have already included those lines in my app.xaml. The only way I was able to get Intellisense is when I installed Resharper..  What VS version are you using?

**Comment by patchandthat** [comment]
2015, enterprise and community, with Resharper 10 on both machines.

**Comment by royben** [comment]
That figures.. ;)

**Comment by ButchersBoy** [comment]
Hi, closing, as this is a Visual Studio concern not a library issue.
