### ISSUE TITLE
Validation error template is missing from ComboBox

### ISSUE THREAD

**Issue by sindilevich** [ButchersBoy/MaterialDesignInXamlToolkit#284]
While a `TextBox` uses a nice stylized validation error template, `ComboBox` would display the standard validation error indication: a red rectangle surrounding the `ComboBox`.

I would suggest `ComboBox` using the same validation error styling, as say `TextBox`.

**Comment by sindilevich** [comment]
I think the issue was not completely resolved. Take a `TextBox` for example: when it is _invalid_ and _unfocused_ it is underlined with a **thin** red line, in addition to the validation error message. When it is _invalid_ and _focused_ it is underlined with a **thick** red line, in addition to the validation error message.

In version 1.5, however, a `ComboBox` only has the validation error message, but no thin/thick red underline when it is unfocused/focused.

**Comment by ButchersBoy** [comment]
@sindilevich thanks for pointing out.

**Comment by BartekDuszynski** [comment]
Solved in pull request #447
