### ISSUE TITLE
Ripple color (feedback) is often un-modifiable (e.g., for buttons)

### ISSUE THREAD

**Issue by jdf3** [ButchersBoy/MaterialDesignInXamlToolkit#289]
Taking a peek at source, it looks like in many styles' templates, `Ripple.Feedback` is usually set to `"{DynamicResource MaterialDesignFlatButtonRipple}"`, with no template binding (e.g., ripple in `ControlTemplate`s of button styles).  I'd really like some control over this.

Here's a simple case: I'm stealing the colors from the albums and putting the album cover on a card that's that "stolen" color (excuse the debugging color bars on the bottom...):

![image](https://cloud.githubusercontent.com/assets/838256/13733758/d608dc0a-e964-11e5-9099-36649682e234.png)

So there's some UI logic going on here to make sure we don't put dark text on dark backgrounds.  It's all accommodated quite nicely, aside from ripple - since I'm using the Light theme, I seem to be stuck with Light-themed ripple, even on dark backgrounds (yes, there's ripple feedback there!):

![image](https://cloud.githubusercontent.com/assets/838256/13733824/74cf3d66-e965-11e5-903d-bfb00b9a5c92.png)

I don't believe there's a sane workaround, but there's a possibility I missed something.  I don't think the expectation here should be that I load the light/dark themes as needed, per-card...

**Comment by jdf3** [comment]
Will tidy up #227 - attached property to manage ripple feedback color.

**Comment by xaviergonz** [comment]
I'm glad it could serve as inspiration :+1:
