### ISSUE TITLE
Get PaletteHelper to correctly work with selected Light/Mid/Dark hues when changing palette, and provide information as to the hues used in the current swatch/palette

### ISSUE THREAD

**Issue by bebenins** [ButchersBoy/MaterialDesignInXamlToolkit#290]
This way you can programatically reference a color in case you are programatically changing it and then want to go back to default.

**Comment by ButchersBoy** [comment]
Two new methods incoming on ```PaletteHelper ``` :

```.QueryPalette() ```

Queries the current palette, providing the primary and accent swatch, and the index of each hue used.

```.ReplacePalette() ```

Allows you to replace the entire palette in a single call, including specifying specific hues.

Also, when using ```.ReplacePrimaryColor() ``` and ```.ReplaceAccentColor() ``` the index of the hues of the current palette will be used to determine the specific hues in the new colour.
