### ISSUE TITLE
Card template TextFormattingMode=Display

### ISSUE THREAD

**Issue by JamesIrish** [ButchersBoy/MaterialDesignInXamlToolkit#295]
Hi James,

Any reason why the default Card template specifies `TextFormattingMode` = `Display`?  e.g. [line 37](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Card.xaml#L37)  
Any text hosted within the card inherits this value and renders without anti-aliasing.

(not the best example..)

`Display`
![excel_2016-03-16_12-34-23](https://cloud.githubusercontent.com/assets/608370/13812356/9ad24b7e-eb73-11e5-8760-50289ba4f551.png)

`Ideal`
![excel_2016-03-16_12-35-09](https://cloud.githubusercontent.com/assets/608370/13812361/9f14381e-eb73-11e5-812d-c27c4d522bda.png)

Any chance we can drop that line?

Thanks,
James

**Comment by ButchersBoy** [comment]
Yeah...looks a bit :hankey:
