### ISSUE TITLE
entering decimal value in DataGrid

### ISSUE THREAD

**Issue by ericfeng8941** [ButchersBoy/MaterialDesignInXamlToolkit#306]
`<DataGridTextColumn Header="Price" Width="Auto" Binding="{Binding Path=Price, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" EditingElementStyle="{StaticResource MaterialDesignDataGridTextColumnEditingStyle}"/>`

the DataGrid is binding to the DataTable, the Price is money in SQL (decimal in DataTable), I am able to enter 1.23 when adding a new row, to change the existing row to 1.23 will get 123, the dot cannot be entered into the cell. 
copy 1.23 from notepad and paste will work.
change the price to string it works.
create a new project without MD it works.

**Comment by jdf3** [comment]
You can't use `UpdateSourceTrigger=PropertyChanged` with a decimal/float/double value the way you describe.  The moment you enter a period, `PropertyChanged` fires and updates the value - so if you entered `5` and then `5.`, this `5.` is converted to a decimal/float/double with value `5` (which is obviously the same value as `5.`.)

I don't know why you think this works for vanilla `DataGrid`s outside of MDinXAML - this doesn't have anything to do with `DataGrid`s.

**Comment by ericfeng8941** [comment]
Thank you jdf3, anyway, it works without Material Design is my test result.

**Comment by jdf3** [comment]
What I am saying is that it *doesn't* work, even in your case.

In your case, `UpdateSourceTrigger=PropertyChanged` is *ignored*.  Put a breakpoint on your decimal property - it will only update on `LostFocus`.  Isn't that *more* broken?

If you want that (broken) behavior in MDinXAML, just remove "`UpdateSourceTrigger=PropertyChanged`" from your binding declaration.

**Comment by ericfeng8941** [comment]
Thank you again, that works.

**Comment by ButchersBoy** [comment]
Hi @ericfeng8941 , please close this if you don't have an issue.
