### ISSUE TITLE
MaterialDesign DialogHost issue with FluentRibbon

### ISSUE THREAD

**Issue by chrisklepeis** [ButchersBoy/MaterialDesignInXamlToolkit#307]
After my issue posted here https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/299 , I tried just using a global DialogHost ("RootDialog") that wraps my entire application, in my main xaml window file.

When using this with Fluent Ribbon, the main menu button does not work properly - it looks like it gets clicked but the menu doesn't slide out using the Office 2013 theme in Fluent Ribbon.I'm not sure if the issue is with MaterialDesign or Fluent Ribbon but I will be posting this issue in both places.

Sample project attached.

[MaterialRibbonDemo.zip](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/files/185915/MaterialRibbonDemo.zip)

**Comment by ButchersBoy** [comment]
Can you post your zip as a full GitHub repo?

**Comment by chrisklepeis** [comment]
https://github.com/chrisklepeis/MaterialRibbonDemo

**Comment by ButchersBoy** [comment]
See my remarks on https://github.com/fluentribbon/Fluent.Ribbon/issues/285

**Comment by batzen** [comment]
It's a ribbon issue. Can be closed here.
