### ISSUE TITLE
ValidationRule Stays after Transition

### ISSUE THREAD

**Issue by bjornjacobs** [ButchersBoy/MaterialDesignInXamlToolkit#313]
![registerone](https://cloud.githubusercontent.com/assets/17616368/14060785/42dd190e-f36f-11e5-8d6d-06d70abd3889.PNG)
![registertwo](https://cloud.githubusercontent.com/assets/17616368/14060786/42f123ea-f36f-11e5-816d-39ebcd81f36e.PNG)

The ValidationRule stays visibile after a transition.

**Comment by ButchersBoy** [comment]
Hi, can you try adding an AdornerDecorator around your slide content and see if that resolves the issue and report back?  It might then be that I add one as default into the control templates.

**Comment by bjornjacobs** [comment]
That fixed it. Thx
