### ISSUE TITLE
TimePicker: SelectedTimeProperty not synced back as null

### ISSUE THREAD

**Issue by anthonyliao** [ButchersBoy/MaterialDesignInXamlToolkit#316]
TimePicker allows for nullable SelectedTime, but a null value is not synced back on the property if a user removes the time value in the text field

e.g.
`<TimePicker SelectedTime={Binding ViewModel.SelectedTime}/>`

1. My view model sets SelectedTime = null
2. TimePicker displays nothing in text box, which is correct
3. I change the value for TimePicker from the UI, and set it to 11:45PM
4. View model's SelectedTime is now 11:45PM, which is correct
5. If I now delete the value for TimePicker from the UI, the view model's SelectedTime is still 11:45PM - I expect this to be null (WPF's DatePicker works the same way)

**Comment by anthonyliao** [comment]
Hi - any update/thoughts?

**Comment by ButchersBoy** [comment]
Sorry, haven't got around to looking at this one yet.

**Comment by ButchersBoy** [comment]
Fixed.

**Comment by ButchersBoy** [comment]
Just retested on latest, and seems OK.
