### ISSUE TITLE
VS Live Visual Tree  stuck at DialogHost

### ISSUE THREAD

**Issue by negue** [ButchersBoy/MaterialDesignInXamlToolkit#317]
If you try the picker it selects the DialogHost, but not any control of its content

**Comment by ButchersBoy** [comment]
Yeah. It's getting stuck oh the overlay grid, but it's hit test invisible, so the visual tree explorer should ignore it, like Snoop does...might be one to take to the Visual Studio Team...

**Comment by negue** [comment]
I could "fix" it when I set `Background="{x:Null}"` on the Grids `PART_ContentCover` (DrawerHost) and `ContentGrid` (DialogHost), still looking for a good way to set those again for the animations^^

**Comment by ButchersBoy** [comment]
Turned out easy then; thanks.
