### ISSUE TITLE
DataGrid Style

### ISSUE THREAD

**Issue by l1pton17** [ButchersBoy/MaterialDesignInXamlToolkit#32]
Is there any way to use material design for data grid?

**Comment by ButchersBoy** [comment]
Yeah, should be able to do this: http://www.google.co.uk/design/spec/components/data-tables.html

Can't give you an ETA at the moment.  Toolbars will be next...among various other things!

**Comment by ButchersBoy** [comment]
Early version is in.  Still to improve text editing to provide the popup in the Google sepecification, but this is fully use-able.

![mdgrid](https://cloud.githubusercontent.com/assets/658107/8911584/57ada726-3485-11e5-8945-29d5d15d3139.gif)

**Comment by ButchersBoy** [comment]
![griddemo](https://cloud.githubusercontent.com/assets/658107/9170600/25cc275a-3f5c-11e5-99a8-d1c8954498e6.gif)
