### ISSUE TITLE
Validation for TimePicker

### ISSUE THREAD

**Issue by lobin-z0x50** [ButchersBoy/MaterialDesignInXamlToolkit#325]
I have been using Material for our Product since version 1.2, I have just tried version 1.5.
But I have one problem for `TeimePicker`.

The problem I am having is I can not be apply my Validations to 'TimePicker'.
Because the `TimePicker` is automatically jump back to the previous good value when an invalid value is entered.
For example, if input 'A' in `TimePicker`, then it should be to state to validation error..

Does anyone have an idea?

**Comment by ButchersBoy** [comment]
hmmmm. I guess you are seeing the affect of: https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/pull/266

I think we can open it up a bit so your validation kicks in instead of it reverting.

**Comment by lobin-z0x50** [comment]
I will try it.
Thank you !
