### ISSUE TITLE
ToggleButtons are broken

### ISSUE THREAD

**Issue by TheSylence** [ButchersBoy/MaterialDesignInXamlToolkit#326]
The _MaterialDesignActionLightToggleButton_, _MaterialDesignActionToggleButton_, _MaterialDesignActionDarkCheckBox_ and _MaterialDesignActionAccentToggleButton_ styles are broken in version 1.5 and 2.0. Version 1.4.1 works as expected.

Steps to reproduce:
- Download the source code from Github release 1.5.0 and 1.4.1.
- Open the MaterialDesignToolkit.Wpf Solution
- Build and start the MaterialDesignDemo project
- Go to "Buttons & Toggles"
- Look ;)

See attached image for comparison
![materialdesign](https://cloud.githubusercontent.com/assets/5342047/14260069/0085e9c2-faaa-11e5-8ee2-5cc6201c4bf0.png)

**Comment by ButchersBoy** [comment]
I'm looking at this...

![image](https://cloud.githubusercontent.com/assets/658107/14260226/6a8d911a-faa2-11e5-9ed3-536c6604b884.png)

**Comment by ButchersBoy** [comment]
I did re-write the template for those buttons though...but can't reproduce your issue...

**Comment by mgnslndh** [comment]
![image](https://cloud.githubusercontent.com/assets/1139118/14307327/63fb9de2-fbce-11e5-9fa5-4fd71fbfa72e.png)

**Comment by ButchersBoy** [comment]
@TheSylence @mgnslndh are you guys seeing any warning being spat out in the Output window?

I think it must be something to do with the clipping starting here https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ToggleButton.xaml#L107

I've tried this on two PCs and I don't have the issue.

Could you guys start replacing the bindings, one by one, with the value 32, and tell me which line(s) bring them back.

In bother the OnGrid and OffGrid there are EllipseGeometry RadiusX and RadiusY bindings, and a multi binding on EllipseGeometry.Center.

I'm thinking maybe there is a timing thing and the clip is getting generated by a zero width or something...

**Comment by mgnslndh** [comment]
I get this binding error in the Output window:
```
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=UncheckedEllipse'. BindingExpression:Path=RenderedGeometry; DataItem=null; target element is 'Grid' (Name=''); target property is 'Clip' (type 'Geometry')
```
Probably because of this line:

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ToggleButton.xaml#L47

**Comment by ButchersBoy** [comment]
What happens if you remove that Clip property?

**Comment by mgnslndh** [comment]
Removing that binding does not seem to affect anything. 
Changing RadiusX and RadiusY to 32 does indeed show the ToggleButton but of course, not looking like it should. For both OffGrid and OnGrid.

**Comment by TheSylence** [comment]
Yep same here. 
I have the same Binding Error in the Output Window and changing the Radius properties to 32 brings back the content (although not as an ellipse but rather as an rectangle, but I guess I would have to tweak the values to get the ellipse back)

**Comment by ButchersBoy** [comment]
OK...I'll try and get on some other PCs and see if I can reproduce...I wonder if .Net fx versions could affect it...know what exact versions you are running?

**Comment by TheSylence** [comment]
I found the problem in the MathConverter. 
I have a german system and the ConverterParameter "2.0" is parsed as 20 resulting in a Radius of 1.6 instead of 16.

Using the InvariantCulture in the TryParse call fixes this.

**Comment by ButchersBoy** [comment]
Excellent!   Can your raise a PR?

**Comment by ButchersBoy** [comment]
@TheSylence thank you, and welcome to the contributors list
