### ISSUE TITLE
DialogHost covering open dialogs

### ISSUE THREAD

**Issue by hshahdoost** [ButchersBoy/MaterialDesignInXamlToolkit#327]
New dialogs don't cover the dialogs which are already open, even if it's higher in the visual tree. something like this happens:

![dialoghost](https://cloud.githubusercontent.com/assets/1842220/14271116/a13d6ca4-fb0a-11e5-9d81-35b3b7440da8.png)

This feature is very important for cases which we want to have a message box in our application. It's important for the messagebox to be above everything even other dialogs (and not be limited to the size of containing dialog)

**Comment by CarHel** [comment]
To reproduce this, just launch the demo -> Dialogs. Click on the add button of fruit Bowl then on pass view. Add fruit shouldn't be accessible.

**Comment by ButchersBoy** [comment]
To be honest managing layers of dialogs isn't something I will go into lightly, I envisage a whole heap of issues potentially weakening the toolkit API.

In such use cases, I suggest updating the dialog content, either via your own XAML, or using the ``` DialogSession.Update() ``` method (or possibly even the ``` Transitioner ``` for nice effects).  These are techniques I use in similar situations.
