### ISSUE TITLE
Make it possible to disable ripple effects

### ISSUE THREAD

**Issue by mgnslndh** [ButchersBoy/MaterialDesignInXamlToolkit#328]
Add a property to RippleAssist that can be used to turn off ripple effects. Controls can query this property to figure out if they should render a ripple or not.

Possible names for the property:
- IsRippleEnabled
- IsRippleDisabled
- UseRippleEffect

**Comment by Keboo** [comment]
Should this issue be closed? It looks like the PR has been merged.

**Comment by jmwhitmire** [comment]
It seems that something has broken this fix. I cannot remove the Ripple from a CheckBox in a ListBoxItem, and the Ripple effect gets applied to the entire ListBoxItem, not just the CheckBox.
