### ISSUE TITLE
Color zone for WPF

### ISSUE THREAD

**Issue by insightmobiledata** [ButchersBoy/MaterialDesignInXamlToolkit#339]
I'm trying to use the ColorZone options for overwriting the primary and accent colors of a TabablzControl only. When attempting to use the colorZone tag, it says that Color Zone is not supported for a WPF project. Is this something that will be available in the near future?

If not, is there a way to overwrite the primary and accent color on the tab control only?

Thanks in advance.

**Comment by ButchersBoy** [comment]
If it can't find the tag it probably means either the Material Desighn assembly isn't refefernced, or you don't have the namespace declared in your XAML.  If you are using ReSharper it would probably give you the option to add this, otherwise look at:

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/ColorZones.xaml#L6

**Comment by insightmobiledata** [comment]
It appears I forgot to reference it unlike the other forms I've already used. Thanks!

Unfortunately, my understanding of a ColorZone must have been incorrect because the style of the TabablzControl is unchanged. Is there any way to overwrite that style. I can post this on the Dagablz project if needed. Thanks in advance

**Comment by ButchersBoy** [comment]
You know there are two material styles for Dragablz, right?  Are either of these what you are after?

**Comment by insightmobiledata** [comment]
Essentially, I would like to have a Transparent color instead of the PrimaryColor and use the PrimaryColor as the Accent (only for this control).

While gathering enough information to ask the question, I was able to answer is as well:

<Style TargetType="{x:Type dragablz:TabablzControl}" BasedOn="{StaticResource MaterialDesignTabablzControlStyle}">
                <Style.Resources>
                    <SolidColorBrush x:Key="PrimaryHueMidBrush" Color="Transparent"/>
                    <SolidColorBrush x:Key="SecondaryAccentBrush" Color="{StaticResource Primary500}"/>
                </Style.Resources>
            </Style>


Thanks again for your help and this awesome library!
