### ISSUE TITLE
Expander inside of a ScrollViewer cancelling scroll event

### ISSUE THREAD

**Issue by quicoli** [ButchersBoy/MaterialDesignInXamlToolkit#342]
I have a scrollviewer. Inside of it many other controls including a closed  Expander. While expander is closed, my scrollviewer scroll, is working. When I open the Expander, move mouse over it and try scrolling, the scrollviewer doesn't scroll. Moving over out of Expander and trying a scroll again,  ScrollViewer is back working.

Looks like Expander is capture scroll event and canceling it. See this issue in action here:  http://recordit.co/MCsnhSMQFE

**Comment by campersau** [comment]
I think this is already fixed. See #334

**Comment by ButchersBoy** [comment]
Yep, closing as duplicate.
