### ISSUE TITLE
The position of the error message is not aligned

### ISSUE THREAD

**Issue by lobin-z0x50** [ButchersBoy/MaterialDesignInXamlToolkit#343]
If the Width of the Control is large, the position of the error messages is shifted.
I think there should aligned regardless its width.

My guess is that because MaxWidth=250 of TextBlock of MaterialDesignValidationErrorTemplate.
Is there any way to aligned position of the error messages?

![error_message_positions](https://cloud.githubusercontent.com/assets/11419109/14603191/4f5a5ed6-05a7-11e6-8b17-ff1fde94fd66.png)

**Comment by ButchersBoy** [comment]
(Notes: Probably need to bind the MaxWidth of the validation content to the ActualWidth of the target control, or similar, and align left.)

**Comment by ButchersBoy** [comment]
Hi @lobin-z0x50 , please close if fixed after @mgnslndh PR.

**Comment by lobin-z0x50** [comment]
@ButchersBoy Yes sir!

**Comment by lobin-z0x50** [comment]
:+1: verified, thanx.
