### ISSUE TITLE
Combo box Tab out focus

### ISSUE THREAD

**Issue by amoamare** [ButchersBoy/MaterialDesignInXamlToolkit#347]
In latest prerelease 2.0.0-ci531 and ci553 when using the combo box if you attempt to tab out the focus goes to the label instead of tabbing to next control. (Note having to tab 3 times to move to next control)

![image](https://cloud.githubusercontent.com/assets/15149902/14643022/ac25d398-0601-11e6-85f6-c31c36dc4646.png)

In stable release 1.5.0.523 tabbing out works as expected.

**Comment by bebenins** [comment]
Would be awesome if this was fixed as well.  Very hard to tell when ComboBox is in focus.
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/277
Thanks

**Comment by quicoli** [comment]
@ButchersBoy 

I believe  #277 is about the animation. I added it here.
![implementation](http://g.recordit.co/rKqKCT8U2l.gif)
