### ISSUE TITLE
TimePicker's Foreground

### ISSUE THREAD

**Issue by furiousbuilder** [ButchersBoy/MaterialDesignInXamlToolkit#35]
Hi, 

Like you said me here : https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/20#issuecomment-103192198
I create another topic for TimePicker foreground.
TimePicker.Foreground = Brushes.Black is not working. VS say that he can't convert "Brushes" to "Brushes".
DatePicker.Foreground = Brushes.Black is working perfectly for DatePicker.

Thanks, 
Clément.

**Comment by furiousbuilder** [comment]
Any news for this bug ?

**Comment by ButchersBoy** [comment]
Hey, not yet, but I've cleaned a lot of other issues in my queue so I'll look at this one next, hopefully in the next couple of days.

**Comment by furiousbuilder** [comment]
I updated to the last Alpha, I've not the error "can't convert "Brushes" to "Brushes"" but the TimePicker's foreground don't change, it's still unreadable :/

**Comment by ButchersBoy** [comment]
OK, will have a look shortly...one question, are you using a MahApps palette or a Material Design palette?

**Comment by furiousbuilder** [comment]
I have both MahApps and Material Design in my Application.XAML to change App Theme to light or dark and have a great color integration in your controls

**Comment by ButchersBoy** [comment]
OK, the time picker now looks a lot better in dark mode; let me know if it's better for you.

Please note that the time readout on the clock will not be updated by setting TimePicker.Foreground.  The time is laid over a coloured background, and thus the foreground needs to be set according to the Material Design specifications to ensure it is legible. Effectively, this part of the control renders with the same colours whether in light or dark mode.

**Comment by furiousbuilder** [comment]
Same problem with the 0.0.0.88, 
![screenshot 17](https://cloud.githubusercontent.com/assets/10899984/9310327/516ff982-450f-11e5-8588-9fd874470e6f.png)
But with the DatePicker the problem is the same but I can change the foreground so it's not important for it

**Comment by furiousbuilder** [comment]
Oh ! I found the problem ! In fact, the bug come from that I let the choice to the user to change app theme to light or dark. If I change the theme in Application.XAML to dark, it's great, but if it is set to light, then I do a MahApps.Metro.ThemeManager.ChangeAppTheme(Application.Current, "BaseDark"), the problem is here

**Comment by ButchersBoy** [comment]
Ok, then I think I need to look at providing dynamic theme switching in code, as per your other issue, then check the whole thing plays nice with MahApps. Leave it with me a little while...

**Comment by mhn23** [comment]
Lurking for a themechanger with mahapps Support

**Comment by ButchersBoy** [comment]
Okay okay I get it! 😉 I will start work on it...

**Comment by furiousbuilder** [comment]
Good luck :)

**Comment by ButchersBoy** [comment]
See update on this thread: https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/36

Get back to me and let me know where you're at.

**Comment by ButchersBoy** [comment]
Dealing with under https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/36
