### ISSUE TITLE
DialogHost is already open

### ISSUE THREAD

**Issue by QewQew** [ButchersBoy/MaterialDesignInXamlToolkit#357]
Using a PopupBox with StaysOpen set to true, you can still click on buttons when when a DialogHost is already open, causing the program to try to launch another. Doing so will throw an exception stating "DialogHost is already open."

**Comment by ButchersBoy** [comment]
I am going to argue that this is not a bug.  I'm turning StaysOpen off on the demo home page.  If you use StaysOpen, but call into DialogHost you should probably manually close  the popup.  The DialogHost is protected itself by throwing that error.

**Comment by QewQew** [comment]
How about giving DialogHost a higher z-index so that you can't click on the PopupBox entries if the DialogHost is still open? I'm not sure why you'd want to be able to still click on PopupBox entries if the DialogHost modal is going to be blocking everything else.

**Comment by ButchersBoy** [comment]
Not that easy, dialogs and pop up boxes both have pop-up Windows...outside of the usual visual tree
