### ISSUE TITLE
NullReferenceException in designer MaterialDesignThemes.Wpf.SmartHint

### ISSUE THREAD

**Issue by amoamare** [ButchersBoy/MaterialDesignInXamlToolkit#359]
In latest pre-release when using Hint a null reference exception is thrown and the designer crashes out. A quick modification to a the xaml will redraw the designer until next build or swapping between windows. 

NullReferenceException: Object reference not set to an instance of an object.
StackTrace:
 at MaterialDesignThemes.Wpf.SmartHint.<>c__DisplayClass29_0.<RefreshState>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ButchersBoy** [comment]
Can you define steps to reproduce?  I don't use the designer but have had a play and can't immedietly reproduce.

**Comment by JamesIrish** [comment]
I had something similar yesterday, confess I didn't catch the specifics of the error but in case it occurred during what I'm assuming was the Unloaded event as I had a control that contained the hint hosted within another ContentControl.  From memory it was NullRef error in Refresh_State() method?  Will attempt to reproduce later this evening, or perhaps tomorrow as it is Game of Thrones night you understand..

**Comment by ButchersBoy** [comment]
Yes.  Winter is coming.

**Comment by amoamare** [comment]
Okay took a few mins but i figured out what the issue is in this case. 
It happens on a combobox that has a null list and selecteditem binding. With data context set in xaml.
MainWindow.xmal
`<Window x:Class="WpfApplicationTests.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:local="clr-namespace:WpfApplicationTests"
        xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
        Title="MainWindow" >
    <Window.DataContext>
        <local:MainViewModel/>
    </Window.DataContext>
    <StackPanel>
        <ComboBox Width="300" materialDesign:HintAssist.Hint="Please select one" ItemsSource="{Binding TestList}" SelectedItem="{Binding SelectedTestItem}" />
    </StackPanel>
</Window>
`
MainViewModel
` public class MainViewModel : INotifyPropertyChanged
    {
        public MainViewModel()
        {
            TestList = new List<string>();
        }

        private List<string> _testList;

        public List<string> TestList
        {
            get { return _testList; }
            set
            {
                _testList = value;
                OnPropertyChanged();
            }
        }

        private string _selectedTestItem;

        public string SelectedTestItem
        {
            get { return _selectedTestItem; }
            set
            {
                _selectedTestItem = value;
                OnPropertyChanged();
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;

        [NotifyPropertyChangedInvocator]
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }`

**Comment by amoamare** [comment]
TestList = new List<string>();
Forgot to say delete this line to produce the error

**Comment by amoamare** [comment]
Another example. In this case it's not using a hint at all. 

MainWindow.xaml

```
<Window x:Class="WpfApplicationTests.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:local="clr-namespace:WpfApplicationTests"
        Title="MainWindow" >
    <Window.DataContext>
        <local:MainViewModel/>
    </Window.DataContext>
    <StackPanel>
        <TextBox Text="{Binding TestReadOnly, Mode=OneWay}"/>
    </StackPanel>
</Window>
```

MainViewModel.cs

```
 public class MainViewModel : INotifyPropertyChanged
    {
        
        public MainViewModel()
        {
        }

        public string TestReadOnly => SomeOtherClass.TestReadOnly;

        public event PropertyChangedEventHandler PropertyChanged;

        [NotifyPropertyChangedInvocator]
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
```

SomeOtherClass.cs

```
    internal class SomeOtherClass
    {
        internal static string TestReadOnly { get; }

        static SomeOtherClass()
        {
            TestReadOnly = "Some information";
        }
    }

```

**Comment by l1pton17** [comment]
@amoamare i've made a PR #360, couble you be so kind to test it?
