### ISSUE TITLE
Button error when using PackIcon as Content after update to 2.0.0-ci572 version.

### ISSUE THREAD

**Issue by rogamaral** [ButchersBoy/MaterialDesignInXamlToolkit#368]
After update to 2.0.0-ci572 my buttons, that use PackIcon as Content, breaks with this error:
 
>The local property "Kind" can only be applied to types that are derived from "PackIconBase`1".

```
<Button HorizontalAlignment="Left"
             Style="{DynamicResource MaterialDesignFloatingActionDarkButton}"
             Visibility="{Binding TvSerie.IsSynopsisLoaded, Converter={StaticResource InvertedBoolToVisibility}}"
             ToolTip="Ler sinopse">
    <materialDesign:PackIcon Kind="CommentTextOutline"/>
</Button>
```

**Comment by ButchersBoy** [comment]
I don't think this is a bug, more like some kind of VS/designer issue.

Please clean your solution VS caches and retry.

**Comment by rogamaral** [comment]
You were right, it was a problem of the designer, I apologize for posting.

**Comment by GioviQ** [comment]
I am using the last version of Visual Studio 2017 and I experience the same issue.
I clean the solution, but the above error remains.

**Comment by Keboo** [comment]
@GioviQ there is an issue with the Visual Studio designer where it does not handle generics well. These designer errors only show up when you have the designer (xaml files) open. The project should still compile.

**Comment by GioviQ** [comment]
Ok
