### ISSUE TITLE
ComboBox background color should allow transparent

### ISSUE THREAD

**Issue by arc95** [ButchersBoy/MaterialDesignInXamlToolkit#369]
The new version of Material Design XAML Toolkit applies a background color to the ComboBox control which can be an issue when displayed in a ListView which has alternating row colors: 

![dr](https://cloud.githubusercontent.com/assets/2144909/15047655/da36d2c8-12b3-11e6-82db-ed013d8913e3.jpg)

It would be great to have a way to toggle the background to transparent on ComboBoxes, so the background color is not applied. Thanks.

**Comment by l1pton17** [comment]
@arc95 you can set ComboBox background property

**Comment by arc95** [comment]
@l1pton17 That's not going to address it, as I just tried it. I only want the box to be transparent when it's closed. This makes it transparent also when the user clicks to open it, letting the background bleed through all the items.

**Comment by l1pton17** [comment]
@arc95 sorry, made a mistake. You can manually set background color of comobobox according to panel background.

**Comment by arc95** [comment]
@l1pton17 How do you do that in a ListView with alternating row color and keep the color from also affecting all the items in the dropdown?

**Comment by l1pton17** [comment]
@arc95 With RelativeSource <ComboBox Background="{Binding RelativeSource={RelativeSource Mode=FindAncestor, AncestorType={x:Type ListViewItem}}, Path=Background}">

**Comment by l1pton17** [comment]
@arc95 but i agree with you, transparent mode need a fix :smile:

**Comment by arc95** [comment]
Thanks, @l1pton17. If I knew more about WPF, I would implement what you're suggesting. For now, I'll wait for a fix from the experts :smile:

**Comment by ButchersBoy** [comment]
What's status on this? Do we still have an issue?

**Comment by l1pton17** [comment]
@ButchersBoy i think so.
I suppose i will do a PR in a few days. Sorry, i had a vacation.

**Comment by hansmaad** [comment]
> @ButchersBoy i think so.
> I suppose i will do a PR in a few days. Sorry, i had a vacation (spent in Czech).

So with this PR the popup background in the original example of this issue is sometimes white and sometimes blue? I don't think that this is exactly what we always want. I don't see even a way to override this "auto" background.
