### ISSUE TITLE
Icon Toggle (flat)

### ISSUE THREAD

**Issue by JamesIrish** [ButchersBoy/MaterialDesignInXamlToolkit#37]
Hi James,
Is there support for flat icon toggles? https://www.google.co.uk/design/spec/components/buttons.html#buttons-other-buttons 
Similar to those used throughout the toolbar on Google's "Inbox".
Thanks

**Comment by ButchersBoy** [comment]
Not currently, but I'll add it to the TODO list...

**Comment by JamesIrish** [comment]
Awesome. Great project by the way, nice work. :+1:

**Comment by ButchersBoy** [comment]
Re-opening this to keep track of it.

**Comment by ButchersBoy** [comment]
Added two new styles: MaterialDesignFlatToggleButton & MaterialDesignFlatPrimaryToggleButton.  Both can be seen in use in MaterialDesignColors.WpfExample demo app.

Cheers,

James
