### ISSUE TITLE
How can I add the material design style to Datagrid from Extended WPF toolkit

### ISSUE THREAD

**Issue by rohit3d2003** [ButchersBoy/MaterialDesignInXamlToolkit#374]
I am trying to apply the material styles to the datagrid control defined in Extended WPF toolkit and I am not sure how to do it

**Comment by rohit3d2003** [comment]
Never mind, I was able to do it. Closing this issue now

**Comment by bebenins** [comment]
This is actually database to record issues that have to be fixed.
If you need help, you can ask questions in the forum:
https://gitter.im/ButchersBoy/MaterialDesignInXamlToolkit
