### ISSUE TITLE
The type 'materialDesign:Chip' was not found   in v1.5.0.523  installed from nuget

### ISSUE THREAD

**Issue by edmundorobles** [ButchersBoy/MaterialDesignInXamlToolkit#378]
I have been working  with  MaterialDesignThemes with no problems until I tried to use  'Chip' and got the next issue:

**The type 'materialDesign:Chip' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.**

Then,  I  check in Object  browser and  the Chip type  does not exists! :(

![2016-05-16 14_13_44-cerbero - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/19395118/15300932/d1c3d940-1b70-11e6-8301-3e296664513e.jpg)

I have installed  version 1.5.0.523 from  nuget package manager. 

By the way,  I tried to reference the dll  compiled from de source in  github but i can't, I got similiar messages of  missing references. Could you  give instructions to install from source?

**Comment by ButchersBoy** [comment]
Hi, this is coming in version 2.0, so you'll need to use the -pre version of the nuget.

**Comment by edmundorobles** [comment]
thanks, i will installed. By the way, MaterialDesign is  great  a lot!
