### ISSUE TITLE
Feature request : Contact Chips

### ISSUE THREAD

**Issue by HalidCisse** [ButchersBoy/MaterialDesignInXamlToolkit#382]
see https://material.angularjs.org/latest/demo/chips
![screen shot 2016-05-22 at 12 36 25](https://cloud.githubusercontent.com/assets/6313791/15453780/fb6e8954-2019-11e6-8b97-25114cdbb14b.png)

**Comment by ButchersBoy** [comment]
These are already in the v2 preview.
