### ISSUE TITLE
Chip control removed in 1.5 ?

### ISSUE THREAD

**Issue by RafPe** [ButchersBoy/MaterialDesignInXamlToolkit#396]
Hey I was working on getting application of my own based on the demo app. I noticed really cool feature which is the "Chip" 

                    <materialDesign:Chip Content="Example Chip"
                                 IsDeletable="True"
                                 ToolTip="This is an example chip"
                                 Margin="0 0 4 4">
                </materialDesign:Chip>

However in my application I have the 1.5.* Materialdesign Assembly which seems to not have this control anymore. 

Have I miseed something ? Any info appreciated here :)

**Comment by amoamare** [comment]
Similar question as 
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/378

Chips control is available in the pre release of 2.0 which can be installed from Nuget.

**Comment by RafPe** [comment]
Thanks for info @amoamare ! I will get that version!
