### ISSUE TITLE
Dragablz.Dockablz 设置方向

### ISSUE THREAD

**Issue by tkggusraqk** [ButchersBoy/MaterialDesignInXamlToolkit#398]
TabablzControl 的 TabItem 只能出现在  顶部  ，能不能出现在左边，右边，或者下边

**Comment by amoamare** [comment]
"TabablzControl of TabItem only appear at the top , can not appear in the left, right , or bottom"

**Comment by tkggusraqk** [comment]
不可以做到这样吗？http://v2.freep.cn/3tb_160604100934c8qf512293.jpg @amoamare

**Comment by tkggusraqk** [comment]
想达到的效果就是类似QQ这样的聊天窗口的效果，http://v1.freep.cn/3tb_1606041013113hq9512293.jpg @amoamare

**Comment by AuroraDysis** [comment]
There is a demo in samples.

**Comment by tkggusraqk** [comment]
@AuroraDysis    As long as it has to change the direction of the

**Comment by AuroraDysis** [comment]
@ButchersBoy You can close this issue, I guess. It's not for this project.

**Comment by ButchersBoy** [comment]
Currently Dragablz supports left alignment for Material, and Standard styles.
