### ISSUE TITLE
Create cool style for RangeSlider

### ISSUE THREAD

**Issue by QuantumDeveloper** [ButchersBoy/MaterialDesignInXamlToolkit#40]
Hello. Could you please create cool style for range slider, which is present in MA.Metro library?

**Comment by ButchersBoy** [comment]
Glad you asked :smile: 

To achieve this properly a new cross-over assembly referencing MahApps is probably the way to go, and something I'm definitely up for.  It would be great for the ecosystem, and give WPF desktop developers the ability to use all of the MahApps features with the choice of either Metro/Modern Design or Material Design.  We're already part of the way there, with good cohesion between MahApps, Material, and also Dragablz.

I've already had a chat with @punker76 about it doing this; we're both quite busy, but maybe this will could be the springboard to get us started at some point...

**Comment by QuantumDeveloper** [comment]
@ButchersBoy Greate to hear that.
If you also could add community edition of xceed controld and AvalonDock (free version) in particular and fix its awful design + with community help, fix its issues, it would be greate start for new WPF life, I think.

**Comment by ButchersBoy** [comment]
That's a lot of work :smile: 

For me personally I'd rather focus my time on improving Dragablz than themeing Avalon.

As for the other xceed stuff...hadn't thought about that.  I noticed the other day they have added a few Material Design things to the Plus Edition.  For the free version I'd be happy to support anyone's attempts to use Material Design in XAML Toolkit to make that bridge, but my priority right now is the core Material Design in XAML Toolkit and Dragablz, as I try and bring both of these to a version "1".

Good food for thought though...

**Comment by QuantumDeveloper** [comment]
OK, if Dragablz could support datatemplate/templateselectors and make possible to dock windows like Visual Studio, it will be greate. Because For complex applications like editors there is no alternative to the VS-like control design. 

Is it in your plans or you dont want to add new features?

**Comment by ButchersBoy** [comment]
Dragablz already supports some docking & floating toolbars.  It was initially created to make tab tearing, and simple docking easy for developers, and the docking was designed to be a more end-user friendly system.  VS style docking is great for us techies, but often too much for typical end users.  That's not to say it can't implement more features and in the future though.  But right now I need to lock down the functionality that is already there.  The MDI/Layout stuff still needs some finishing off.

So this is the kinda rough plan I have in my head now:

1.0 - Finalised tab/tearing.
1.1 - Finalised "splitting" (the basic docking/layout)
1.2 - Finalised MDI/toolbars
1.3 - Dragable wrap panel

2.0 - More advanced docking????

**Comment by QuantumDeveloper** [comment]
for version 2.0 I suggest more docking features like docking to the sides in hide mode (left, right, bottom as I desperately need this) and also maybe adding scrollbar for tabs not to made them too narrow, but left them normal width. The same for toolbars. 

Also for me, as I am developing complex application, I would like to see, maybe, upgraded docking system (more complex) for cases when I have too much open toolboxes and I want, for ex. 2/3 toolbars to be available at the same time and this could be achieved only in VS like design when you have left, right, top and bottom sides.

this could give greate impact when using this control on high resolution display - more space for displaying several toolboxes inside ONE window without need to drag them out of the main window.

This is my humble opinion.

**Comment by ButchersBoy** [comment]
Your humble opinion is appreciated.  :smile:

**Comment by QuantumDeveloper** [comment]
Thanks :)
Could you please say do you have some estimations for your plans?

**Comment by ButchersBoy** [comment]
Honestly, between the day job, wife, kids, watching violent action movies...if I can get Material Design Toolkit and Dragablz both to version 1.0 by the end of this year that will be a result...

**Comment by QuantumDeveloper** [comment]
Heh, I understand you quite well)

**Comment by QuantumDeveloper** [comment]
@ButchersBoy BTW, one more question regarding dragablz - does it could serialize/deserialize or somehow save and restore its tabs by buit-in mechanism? 
If no, I think, you should include this ti featire list too)

**Comment by ButchersBoy** [comment]
Good question.

Yes, it needs to help save/restore state, but I am very keen to avoid serialization.  Serialization is brittle, and I have seen too many projects implement a layout system, save using serialization, and then encounter problems further down the line.  A great example is refactoring...suddenly all users layouts are broken, unless XML transformation takes place; and usually that is a major headache.

The type of systems I work on (typically trading systems where a user may have 6+ monitors), saving complicated layouts is a common requirement and I want to encourage my own - proven & successful - techniques in dragablz.  Namely, being able to "walk" a layout to provide a sequence of steps, which can then be used to restore a layout.  This avoids large serialized dumps, allows easier upgrades of individual ViewModels, allows the consumer to store the layout separately from ViewModels, and use whatever storage mechanism they like, be it XML or a database etc.  And it avoids a single point of failure, meaning for example of you refactor one view model and forget to upgrade its state in your backing store, the layout can still restore, albeit with a single failed view.

So far I have the "query" code in place, but not the "restore" code.  So the restore code will be part of version 1.0 and 1.1.  My intent is to provide a good working example of how to use this.

**Comment by QuantumDeveloper** [comment]
Good to hear that you planning to implement some restoring layout algorithm. :+1:

**Comment by ButchersBoy** [comment]
Just checked in, v0.1 https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/commit/a64889091f10900f14db0d87ba9fc0d3dcde7c80

See the MashUp demo.

Nuget to follow over next few days (see https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/86 )

**Comment by QuantumDeveloper** [comment]
Looking nice. Thanks

**Comment by ButchersBoy** [comment]
https://www.nuget.org/packages/MaterialDesignThemes.MahApps
