### ISSUE TITLE
Add a section to the wiki on how to use custom color palettes

### ISSUE THREAD

**Issue by kjeremy** [ButchersBoy/MaterialDesignInXamlToolkit#407]
How do we specify custom color palettes?  It's not clear in the wiki how one would do that.

For instance in my Android app I use:

```
<style name="AppTheme.Base" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="colorAccent">@color/colorAccent</item>
     ...
```

Where the color's are specified as 
```
<resources>
  <color name="colorPrimary">#607D8B</color>
  <color name="colorPrimaryDark">#455A64</color>
  <color name="colorAccent">#FF5252</color>
</resources>
```

It's not obvious to me how to achieve a similar effect if not using the recommended swatches.

**Comment by ButchersBoy** [comment]
Have a look at https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/Advanced-App.xaml

**Comment by ButchersBoy** [comment]
Renamed article.

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/Custom-Palette-Hues
