### ISSUE TITLE
TreeView: Bug with scrolling

### ISSUE THREAD

**Issue by avrAhituv** [ButchersBoy/MaterialDesignInXamlToolkit#409]
hello,
I have a problem.
I use with TreeView for SideMenu in my app.
But when I scrolling the mouse over the children elements; he did not do anything.
How I fix do?

**Comment by ButchersBoy** [comment]
Inside a DrawerHost?

**Comment by avrAhituv** [comment]
What is DrawerHost?

**Comment by ButchersBoy** [comment]
What version are you running, 1.5 or (pre release) 2.0?

**Comment by avrAhituv** [comment]
1.5.0.523
Thanks!

**Comment by avrAhituv** [comment]
Thank you very very much!!!
I changed version to pre-release 2.0 and all worked out!!
