### ISSUE TITLE
The ShowMessageAsync of MahApps.Metro won't show the message dialog

### ISSUE THREAD

**Issue by imgen** [ButchersBoy/MaterialDesignInXamlToolkit#41]
When I tried the MahApps sample, I wanted to show a message dialog, so I followed the documentation and called ShowMessageAsync to do that. But unfortunately this doesn't work, the window will dim out, but the message will not show up. Can you help me with this?

**Comment by imgen** [comment]
Another strange thing is that if I try it in my own project using the latest nuget packages (MahApps.Metro 1.1.3-ALPHA152, MaterialDesignThemes 0.0.0.92, MaterialDesignColors 1.0.0) instead of the source code, I get a null exception, the cause is that MahApps.Metro complains theme is null, how does this happen? Maybe I should use the latest source code instead of the latest nuget package?

**Comment by ButchersBoy** [comment]
OK...because when you open a MahApps dialog, it looks up the MahApps theme, but there is no MahApps theme, as the App.xaml is configured a bit differently for Material Design Toolkit.  Bang.

...looking into a solution...

**Comment by imgen** [comment]
Thanks, looking forward to the solution

**Comment by ButchersBoy** [comment]
Raised a PR with MahApps: https://github.com/MahApps/MahApps.Metro/pull/2087

**Comment by imgen** [comment]
Wooo! That was fast! Thanks for the quick response!

**Comment by ButchersBoy** [comment]
:zap: :wink:

**Comment by ButchersBoy** [comment]
Keep your eye on the MashUp demo project, because I'm making some other changes so we can pass Material Themeing through to MahApss for the dialogs.  Currently, even when the fix is in it shows Metro styling.

**Comment by imgen** [comment]
Cool. Will do just that.

**Comment by ButchersBoy** [comment]
In bizness.

![image](https://cloud.githubusercontent.com/assets/658107/9505557/1c890cbc-4c3b-11e5-8df7-ecd2ad886ef7.png)

You'll need to update to the latest alphas of both MahApps and Material.  You can see the above example in the MahMaterialDragablzMashUp demo app.

You need to pass a few options into the dialog, but it's pretty easy:

```
private void InputDialog()
{
    var metroDialogSettings = new MetroDialogSettings
    {
        CustomResourceDictionary =
            new ResourceDictionary
            {
                Source = new Uri("pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.MahApps.Dialogs.xaml")
            },
        NegativeButtonText = "CANCEL",                
        SuppressDefaultResources = true
    };

    DialogCoordinator.Instance.ShowInputAsync(this, "MahApps Dialog", "Using Material Design Themes", metroDialogSettings);
}
```

**Comment by punker76** [comment]
@ButchersBoy it's like chocolate or a praline :-P

**Comment by ButchersBoy** [comment]
Ha, we should do some Photoshop image of a box of chocolates with the different flavours :smile:
