### ISSUE TITLE
Roboto Condensed bold is not used

### ISSUE THREAD

**Issue by picrap** [ButchersBoy/MaterialDesignInXamlToolkit#414]
Hi,

have you noticed that when using Roboto Condensed instead of Roboto, using
```xaml
<FontFamily x:Key="MaterialDesignFont">pack://application:,,,/MaterialDesignThemes.Wpf;component/Resources/Roboto/#Roboto Condensed</FontFamily>
```
the bold variant of the font is never used (the font is always regular, whatever the requested weight)?

Strange, isn't it?

I know this is not your fault, but I'm looking for ideas to investigate on it, since the WPF font management is a bit opaque.

**Comment by ButchersBoy** [comment]
...uhm yeah...I had various issues back in the early days...but I can't really remember...just that it's a pain...
