### ISSUE TITLE
[ThemeManager] Problems while defining Colors 

### ISSUE THREAD

**Issue by furiousbuilder** [ButchersBoy/MaterialDesignInXamlToolkit#42]
Hi, 

Like you said to me, I created another issue.
For now, I just found a bug using the PaletteHelper : the Flyout (even with theme "Accent") is White or Dark. Here is a sample project : http://www.mediafire.com/download/6mfzie0arh7o4s2/MaterialTemplateProject.zip

Have a nice day,
Clément.

**Comment by ButchersBoy** [comment]
Cool.  Just got MahApps dialogs working with the help of MahApps guys, so will come to this soon.

**Comment by furiousbuilder** [comment]
Great ! I forgot to try dialogs :/

**Comment by furiousbuilder** [comment]
I'm sorry but I got another bug in my other Project with Dragablz... When I set a theme like here : 
![screenshot 33](https://cloud.githubusercontent.com/assets/10899984/9526596/84c0a57e-4cea-11e5-813f-1f042f5d04e2.png)
and then when I pull the tab to create another window, it reset the theme : 
![screenshot 34](https://cloud.githubusercontent.com/assets/10899984/9526601/94fdddd0-4cea-11e5-85bd-9bdaec8cd5e4.png)

**Comment by ButchersBoy** [comment]
Don't be sorry, you are helping me sort the bugs! :smile:

**Comment by furiousbuilder** [comment]
Of course ^^ 
So as I said in my "EDIT", the bug don't really come from you, it's because my UserControl is reloaded :/

**Comment by ButchersBoy** [comment]
@furiousbuilder do we still have an issue here?
