### ISSUE TITLE
DialogHost in 1024 x 768 screen

### ISSUE THREAD

**Issue by ericfeng8941** [ButchersBoy/MaterialDesignInXamlToolkit#420]
I have a UserControl size is 800 x 700, I am using MaterialDesignThemes.Wpf.DialogHost.Show() to display it which work normally on bigger size screen. but when I run the program for the screen size 1024 x 768, the bottom part of the Content cut off. I tried on 5 different computers all same, I also changed my wide screen to 1024 x 768 same result. can you help me on this?

**Comment by ButchersBoy** [comment]
There is padding to account for the shadow...are you seeing that at the top edge?

**Comment by ericfeng8941** [comment]
I can see all edge, actually the popup is smaller than it supposed to be. I did not measure, it looks like 800 x 500.

**Comment by ButchersBoy** [comment]
Screenshot?

**Comment by ericfeng8941** [comment]
![1024](https://cloud.githubusercontent.com/assets/18011948/16172479/5b1dcc7c-353f-11e6-8383-31966418c8f1.png)
![original](https://cloud.githubusercontent.com/assets/18011948/16172481/5fa6fb42-353f-11e6-9238-b8d7d0702b47.png)

**Comment by ericfeng8941** [comment]
any chance to fix in next 4 weeks? I am not pushing you, just want to have a time line.

**Comment by ButchersBoy** [comment]
You can now set ``` DialogMargin ```, and ``` ShadowAssist.Depth ``` on a ``` DialogHost ```.  By default they are 22 and Depth5.  I am guessing that by reducing the margin, and optionally reducing the shadow, you will gain those few extra pixels back.  Please test and report back.

**Comment by ericfeng8941** [comment]
![image](https://cloud.githubusercontent.com/assets/18011948/16424783/7368a14c-3d16-11e6-8ee9-7adfab5f15e6.png)

**Comment by ericfeng8941** [comment]
it does not fix the problem, the parent's actual height is smaller than UserControl's actual height.
is there a way I can specify the height for the popup?

**Comment by ButchersBoy** [comment]
OK, check my last check-in...I screwed up and missed a bit.  Please retry with DialogMargin=0.

**Comment by ericfeng8941** [comment]
it is same result.

**Comment by ericfeng8941** [comment]
2.0.1-ci644 works ok. Thank you very much.
