### ISSUE TITLE
Could not load file or assembly 'MaterialDesignThemes.Wpf, PublicKeyToken=null' 

### ISSUE THREAD

**Issue by GorelH** [ButchersBoy/MaterialDesignInXamlToolkit#427]
Installed Material Design Themes through nuget in WPF control library.
Then got this error when referenced it in a UserControl.

`Could not load file or assembly 'MaterialDesignThemes.Wpf, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.`

My package.config :

`<package id="MaterialDesignColors" version="1.1.2" targetFramework="net461" />
  <package id="MaterialDesignThemes" version="1.5.0.523" targetFramework="net461" />`

Any help is greatly appreciated

**Comment by SCKelemen** [comment]
Do you have .NET 4.6.1 installed?

**Comment by GorelH** [comment]
@SCKelemen  Yes, it's a part of others projects, all using .NET 4.6.1

**Comment by SCKelemen** [comment]
Did you install from Nuget?

**Comment by GorelH** [comment]
Yes

**Comment by ButchersBoy** [comment]
OK, I just went through what I think was the same process as you:

* Create new WPF Project
* Add new WPF Control Library
* Install MD into the __Control Library__ ``` Get-Project WpfControlLibrary1 | Install-Package MaterialDesignThemes ```
* Add a ``` Card ``` into ``` UserControl1 ```
* Add ``` UserControl1 ``` into ``` MainWindow ```
* Compile, run > it __fails__

### Why?

Take a look at the bin folder, the .dll's aren't copied over:

![image](https://cloud.githubusercontent.com/assets/658107/16444525/4e56bafe-3dd6-11e6-8d4b-761d832978a1.png)

Either reference the packages from your .exe, or do something like this to make the build process think the .dlls need to come over:

```
    public partial class UserControl1 : UserControl
    {
        public UserControl1()
        {
            InitializeComponent();
            ShadowAssist.SetShadowDepth(this, ShadowDepth.Depth0);
        }
    }
```

**Comment by GorelH** [comment]
The solution above will copie `MaterialDesignThemes.Wpf.dll` but not `MaterialDesignThemes.Wpf.dll`
have to copy manually.
Thanks
