### ISSUE TITLE
Textbox Hint

### ISSUE THREAD

**Issue by AlanLopez22** [ButchersBoy/MaterialDesignInXamlToolkit#434]
I have the same issue like issue reported in "Possible bug using TextBox hints #251"
and the other issue in the group box showed in modal popup the text of the hint and value are in white color, i attach two images with the issue

![hint text issue](https://cloud.githubusercontent.com/assets/20330525/16641023/9d225ed2-43b1-11e6-8ace-72fe54e4ae21.png)
![hint text issue2](https://cloud.githubusercontent.com/assets/20330525/16641056/d195da0e-43b1-11e6-95d0-a83fd3019a6c.png)

**Comment by ButchersBoy** [comment]
What version you on?

**Comment by AlanLopez22** [comment]
The latest version (MaterialDesignThemes 2.0.0.638), i installed from nuget packages

**Comment by AlanLopez22** [comment]
The problem was solved, I thought I had the latest version installed but it was not, I update and resolved, but now also shows the drop down like the image below, also would like to know how to change the background color from dark/light to blue or to another color

![dropdown issue](https://cloud.githubusercontent.com/assets/20330525/16709809/5782e826-45d0-11e6-918e-17c5767daad2.png)
