### ISSUE TITLE
No loaded DialogHost instances

### ISSUE THREAD

**Issue by GuillaumeB17** [ButchersBoy/MaterialDesignInXamlToolkit#436]
Hi,

I want to display a dialog when I open my application in the main window.
I have the following code:

MainWindow.xaml:
<Window x:Class="MyApp.MainWindow"
        
	xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
	

        <materialDesign:DialogHost Identifier="RootDialog">
              <Grid>
              
             </Grid>
        </materialDesign:DialogHost>
</Window>

MainWindow.xaml.cs:
private async void Window_Loaded(object sender, RoutedEventArgs e)
        {
            var view = new ProgressDialog {  };
            var result = await DialogHost.Show(view, "RootDialog", ClosingEventHandler);
        }

        private void ClosingEventHandler(object sender, DialogClosingEventArgs eventArgs)
        {
            throw new NotImplementedException();
        }

But the program generates an exception: No instances loaded DialogHost

**Comment by ButchersBoy** [comment]
Just move your code to the DialogHost loaded event.

**Comment by GuillaumeB17** [comment]
It works, thank you

**Comment by jcummings2** [comment]
> Just move your code to the DialogHost loaded event.

For example in your XAML:

```XAML
<Window>
    <materialDesign:DialogHost Loaded="DialogHost_Loaded">
          <Grid>
          <!--...-->
         </Grid>
    </materialDesign:DialogHost>
</Window>
```

Then in the code behind:

```C#
async void DialogHost_Loaded(object sender, RoutedEventArgs e)
{
    var view = new MyView();
    var result = await DialogHost.Show(view);
    // process result
}
```
