### ISSUE TITLE
Support for tabcontrol and listview in wpf?

### ISSUE THREAD

**Issue by JEpifanio90** [ButchersBoy/MaterialDesignInXamlToolkit#443]
HI!

First of all, great package! I love it so much. I just have this question, ¿do you have support for the tabcontrol and the listview for wpf?

Thanks!

**Comment by ButchersBoy** [comment]
Tab: yes, via Dragablz.  See the "MashUp" demo project in the source code, and https://github.com/ButchersBoy/Dragablz

List: standard style yes, currently grid view, no.
