### ISSUE TITLE
Blank togglebutton with style MaterialDesignActionToggleButton ( also with [Accent] [Dark] )

### ISSUE THREAD

**Issue by bouazaoui** [ButchersBoy/MaterialDesignInXamlToolkit#444]
**Version :** MaterialDesignThemes.1.5.0.523

There is an issue with style MaterialDesignActionToggleButton
I can't see the togglebutton

![togglebutton](https://cloud.githubusercontent.com/assets/17064603/16800378/50c6f824-48f5-11e6-817a-51902f5f7405.PNG)

![togglebutton2](https://cloud.githubusercontent.com/assets/17064603/16800424/84af438a-48f5-11e6-9004-e79e20e18323.PNG)

![togglexaml](https://cloud.githubusercontent.com/assets/17064603/16800556/34d39306-48f6-11e6-93c0-28f08c8ce41c.PNG)

![toggledesign](https://cloud.githubusercontent.com/assets/17064603/16800595/53a2ab64-48f6-11e6-9ae0-83d593764e33.PNG)
**Application.xaml ** 
`                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.Grey.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Lime.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Button.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.PopupBox.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.TextBlock.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.ListBox.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.ToggleButton.xaml" />`

**usercontrol :** 
   ```
<ToggleButton Grid.Column="2" Margin="5" 
                Style="{StaticResource MaterialDesignActionToggleButton}"
                          ToolTip="MaterialDesignActionLightToggleButton">
                <ToggleButton.Content>
                    <materialDesign:PackIcon Kind="ArrowExpand"   Width="24" Height="24"/>
                </ToggleButton.Content>
                <materialDesign:ToggleButtonAssist.OnContent>
                    <materialDesign:PackIcon Kind="ArrowCollapse" Width="24" Height="24"/>
                </materialDesign:ToggleButtonAssist.OnContent>
            </ToggleButton>
```

**Comment by ButchersBoy** [comment]
UserControl XAML and App.XAML snippets?  What version are you using?

**Comment by ButchersBoy** [comment]
...even better, post a small demo repo...

**Comment by bouazaoui** [comment]
Version : MaterialDesignThemes.1.5.0.523

**Comment by bouazaoui** [comment]
I updated the package , it works now
MaterialDesignColors.1.1.3
MaterialDesignThemes.2.0.0.638
