### ISSUE TITLE
Expander Button should be on the right side

### ISSUE THREAD

**Issue by jlesp** [ButchersBoy/MaterialDesignInXamlToolkit#449]
As per google's [design](https://material.google.com/components/expansion-panels.html), Expansion Panels should have the expand button to the right of the header. Perhaps this could be configurable so the user could choose to have it on either the right or left side?

**Comment by ButchersBoy** [comment]
![expanders](https://cloud.githubusercontent.com/assets/658107/17944594/5eed024a-6a38-11e6-8105-3adc13d07ecc.gif)
