### ISSUE TITLE
progressbars and progress indicators

### ISSUE THREAD

**Issue by n3R0d0T** [ButchersBoy/MaterialDesignInXamlToolkit#45]

**Comment by ButchersBoy** [comment]
Will get basic bar in for version 1.0, then hopefully some more options for a later version.

**Comment by ButchersBoy** [comment]
Got the standard linear progress bar in.  More to come later.

**Comment by ButchersBoy** [comment]
![progressbar](https://cloud.githubusercontent.com/assets/658107/9617384/a20f6dd2-50f9-11e5-8be7-282cfd783f64.gif)

**Comment by ButchersBoy** [comment]
circular progress now in latest beta/demo
