### ISSUE TITLE
 Set property threw an exception.

### ISSUE THREAD

**Issue by mostafa901** [ButchersBoy/MaterialDesignInXamlToolkit#450]
Hi
bottom line: I am receiving this error only if used materialdesign wpf for a wpf window inside a class library:

> Set property 'System.Windows.ResourceDictionary.Source' threw an exception.' Line number '14' and line position '14'.

long story:
I am working on a dll library where it contains some methods as well as a wpf window. code as shown below:
Window Xaml Code

`
<Window x:Class="WpfApplication10.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"        
         xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
        mc:Ignorable="d"
        Title="MainWindow" Height="350" Width="525">

    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.DeepPurple.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Lime.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Window.Resources>

    <Grid>
        <materialDesign:Card Padding="32" Margin="16">
            <TextBlock Style="{DynamicResource MaterialDesignTitleTextBlock}">My First Material Design App</TextBlock>
        </materialDesign:Card>
    </Grid>
</Window>
`

Code behind 

`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace WpfApplication10
{
    /// <summary>
    /// Interaction logic for Window1.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }
    }
}
`

The calling class:

`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using Autodesk.Revit.Attributes;

namespace WpfApplication10
{
    [Transaction(TransactionMode.Manual)]
    class test1 : IExternalCommand
    {
        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            MainWindow main = new MainWindow();
            main.Show();

            return Result.Succeeded;
        }
    }
}
`

as soon as the initialization statement starts and hitting Resource dictionary in the xaml it threw the above mentioned exception.

but if i tried the same for a wpf application and not a library it works like charm. any clues? 

by the way Well don with this library you all are really fascinating.

**Comment by ButchersBoy** [comment]
Hi, ...a test repo would be helpful

**Comment by mostafa901** [comment]
Hi
i have created a repo here
[https://github.com/mostafa901/MaterialDesignTest]

**Comment by ButchersBoy** [comment]
If you examine the exception, the message is: 

{"Could not load file or assembly 'MaterialDesignThemes.Wpf, Culture=neutral' or one of its dependencies. The system cannot find the file specified.":"MaterialDesignThemes.Wpf, Culture=neutral"}

As you are "indirectly" referencing the dlls, you will see they are not gettting copied to WpfApplication1\bin\Debug as part of the build...

So reference them, or add a build step to copy them...

**Comment by EmadERagheb** [comment]
I Face The Same Issue

**Comment by Cazorlas** [comment]
I got them same issue
