### ISSUE TITLE
MaterialDesignThemes.MahApps: Incompatibility with MahApps.Metro 1.3.0 Alpha

### ISSUE THREAD

**Issue by dgadelha** [ButchersBoy/MaterialDesignInXamlToolkit#451]
The `MaterialDesignThemes.MahApps` is incompatible with `MahApps.Metro` 1.3.0 Alpha.

The issue is that `MaterialDesignThemes.MahApps/Themes/MaterialDesignTheme.MahApps.Flyout.xaml` throws the following exception:
```
Set property 'System.Windows.ResourceDictionary.DeferrableContent' threw an exception.
```
A workaround is to remove the
```
<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.MahApps;component/Themes/MaterialDesignTheme.MahApps.Flyout.xaml" />
```
from `App.xaml` in the `<!--  Material Design: MahApps Compatibility  -->` section.

**Comment by ButchersBoy** [comment]
I hope this is resolved by changes Paket changes made by @punker76  a little while back.  Closing.  Please re-open if you still have an issue.
