### ISSUE TITLE
MaterialDesignColors all text is black

### ISSUE THREAD

**Issue by madfrog54321** [ButchersBoy/MaterialDesignInXamlToolkit#452]
I do not know if you have already fixed this, but I just updated MaterialDesignColors from 1.1.2 to the new 1.1.3. After updating, all the text on my interface was black. Even the text on very dark backgrounds. I was unable to find an issue displaying this problem. If you need any more information please let me know. If I just need to edit a file to get the text colors to work again please let me know.

Here are two images showing the difference:
![normalcolors](https://cloud.githubusercontent.com/assets/9935183/16973013/1d8ccc2a-4ded-11e6-8394-9c3c857f3125.png)
![darkcolors](https://cloud.githubusercontent.com/assets/9935183/16973016/228131da-4ded-11e6-8d83-4af3277c8eb4.png)

The only difference in the application is that I updated MaterialDesignColors from 1.1.2 to 1.1.3.

**Comment by ButchersBoy** [comment]
OK. Someone else reported something similar... Not good. I suggest roll back to 1.2 until I get a fix (there's not much difference).

**Comment by ButchersBoy** [comment]
What type of app.xaml config are you using?  Please post snippet.

**Comment by madfrog54321** [comment]
Here is the entire app.xaml file from my project:

<Application x:Class="-------.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:---------"
             xmlns:dragablz="clr-namespace:Dragablz;assembly=Dragablz"
             xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
             StartupUri="MainWindow.xaml"
             ShutdownMode="OnMainWindowClose">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                
                
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />

                
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.Cyan.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Yellow.xaml" />

                
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.MahApps;component/Themes/MaterialDesignTheme.MahApps.Defaults.xaml "/>

                
                <ResourceDictionary Source="pack://application:,,,/Dragablz;component/Themes/materialdesign.xaml"/>

                <ResourceDictionary Source="pack://application:,,,/CustomControls.xaml"/>

            </ResourceDictionary.MergedDictionaries>

            
            <SolidColorBrush x:Key="HighlightBrush" Color="{DynamicResource Primary700}"/>
            <SolidColorBrush x:Key="AccentColorBrush" Color="{DynamicResource Primary500}"/>
            <SolidColorBrush x:Key="AccentColorBrush2" Color="{DynamicResource Primary400}"/>
            <SolidColorBrush x:Key="AccentColorBrush3" Color="{DynamicResource Primary300}"/>
            <SolidColorBrush x:Key="AccentColorBrush4" Color="{DynamicResource Primary200}"/>
            <SolidColorBrush x:Key="WindowTitleColorBrush" Color="{DynamicResource Primary700}"/>
            <SolidColorBrush x:Key="AccentSelectedColorBrush" Color="{DynamicResource Primary500Foreground}"/>
            <LinearGradientBrush x:Key="ProgressBrush" EndPoint="0.001,0.5" StartPoint="1.002,0.5">
                <GradientStop Color="{DynamicResource Primary700}" Offset="0"/>
                <GradientStop Color="{DynamicResource Primary300}" Offset="1"/>
            </LinearGradientBrush>
            <SolidColorBrush x:Key="CheckmarkFill" Color="{DynamicResource Primary500}"/>
            <SolidColorBrush x:Key="RightArrowFill" Color="{DynamicResource Primary500}"/>
            <SolidColorBrush x:Key="IdealForegroundColorBrush" Color="{DynamicResource Primary500Foreground}"/>
            <SolidColorBrush x:Key="IdealForegroundDisabledBrush" Color="{DynamicResource Primary500}" Opacity="0.4"/>

            
            <Style TargetType="{x:Type dragablz:TabablzControl}" BasedOn="{StaticResource MaterialDesignTabablzControlStyle}" />
        </ResourceDictionary>
    </Application.Resources>
</Application>

**Comment by ButchersBoy** [comment]
This isn't actually a bug.

The mid colour (500) for cyan, which is the default button colour uses black text as per the current Google specs: https://material.google.com/style/color.html#color-color-palette

Looks like you are using the MahApps Window.  The style for that looks like iit uses the MahApps brush named BlackBrush.  So you could try tweaking that (to a White), but I dunno what effect that would have on the rest of your app).  I'd like to at a future point re-write the MapApps Window title style to use all the Material icons...but thats not there yet.
