### ISSUE TITLE
Calendar language

### ISSUE THREAD

**Issue by sagevpremium** [ButchersBoy/MaterialDesignInXamlToolkit#453]
Hi,
how can i change calendar language? I'm talking about header, where you can find shortcut with day of week, but in English, between arrow (< >) too...

**Comment by quicoli** [comment]
Hi,  in App.cs  override OnStartup(StartupEventArgs e) and write (the following set to Brazilian:

System.Threading.Thread.CurrentThread.CurrentUICulture = new CultureInfo("pt-BR");
System.Threading.Thread.CurrentThread.CurrentCulture = new CultureInfo("pt-BR");
FrameworkElement.LanguageProperty.OverrideMetadata(typeof(FrameworkElement), new 
                FrameworkPropertyMetadata(
                         XmlLanguage.GetLanguage(CultureInfo.CurrentCulture.IetfLanguageTag)));

**Comment by sagevpremium** [comment]
Thank You! It's working!
https://www.youtube.com/watch?v=AXwGVXD7qEQ :dancers:
