### ISSUE TITLE
Header in Card

### ISSUE THREAD

**Issue by kumailhdr** [ButchersBoy/MaterialDesignInXamlToolkit#455]
Please add something like header in the card

**Comment by uPloraX** [comment]
For what reason? The Card is a generic control / layout of material design. If you want it with a header don't be too lazy to implement it by yourself.

**Comment by bebenins** [comment]
There are also a couple of Group Box controls.... One of them is basically a card with a header and you can change the header style yourself

**Comment by ButchersBoy** [comment]
Yes, Card is totally generic. Adding a Header is inappropriate here.
