### ISSUE TITLE
MaterialDesignThemes 2.0 bug

### ISSUE THREAD

**Issue by tkggusraqk** [ButchersBoy/MaterialDesignInXamlToolkit#456]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		XML 命名空间“http://materialdesigninxaml.net/winfx/xaml/themes”中不存在属性“TextFieldAssist.Hint”。

**Comment by ButchersBoy** [comment]
Please see breaking changes:

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/Version-2.0.0---Breaking-Changes
