### ISSUE TITLE
Can't use left mouse on popup!!!

### ISSUE THREAD

**Issue by baothanh591** [ButchersBoy/MaterialDesignInXamlToolkit#457]
I dont' have the wheel mouse (middle) so I think this problem shoulbe be fix...
If you don't think so, then teach me how to fix it for my application. 
Thanks alot
![untitled](https://cloud.githubusercontent.com/assets/8986785/17083498/09130640-51cd-11e6-9e4a-045f5047c2e4.png)

**Comment by uPloraX** [comment]
On the `PopupBox` you can set `StaysOpen="True"`.
The demo closes the Hamburger Menu after a click automatically, so that could be fixed.

**Comment by baothanh591** [comment]
combobox doesn't have StaysOpen, and it's bug
`James Willock @ButchersBoy Jul 24 19:02
@baothanh591 yeah, known bug`
But he didn't say how to fix T___T

**Comment by ButchersBoy** [comment]
Hi, currently no fix in the Drawer itself, but I have added something in the demo to show you how you can handle this:

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/MainWindow.xaml.cs#L24
