### ISSUE TITLE
Resources can't be resolved.

### ISSUE THREAD

**Issue by SCKelemen** [ButchersBoy/MaterialDesignInXamlToolkit#458]
The resource "MetroStatusBarSeparator" could not be resolved.

For some reason, after I've updated the nuget packages, all references to the MDT cannot be found. I don't think this is necessarily related to the update, but I'm not sure what I am missing. Can you guys please suggest a place to start looking for issues. The themes Generic.xaml, App.xaml, solution and project files are all unchanged. I should also note that it when I build it, everything looks correct. Just the design time has a bunch of errors and warnings about unresolved resources and the designer doesn't render any of the styles.

![image](https://cloud.githubusercontent.com/assets/4325375/17140009/cfc8ac48-5314-11e6-83ef-3d0a78828b7a.png)
![image](https://cloud.githubusercontent.com/assets/4325375/17140084/1d0e18e4-5315-11e6-8be7-8a138b96d3ce.png)

**Comment by ButchersBoy** [comment]
..full clean (including VS caches), rebuild...often does the trick...
