### ISSUE TITLE
Create a hard named swatch for each color.

### ISSUE THREAD

**Issue by ButchersBoy** [ButchersBoy/MaterialDesignInXamlToolkit#46]

**Comment by ButchersBoy** [comment]
@CCRed95 There's a beta build of the Colors assembly with hard named swatches:

https://www.nuget.org/packages/MaterialDesignColors/1.1.0-beta

Example ResourceDictionary name: ```MaterialDesignColor.Blue.Named.xaml```

Example content:

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/Themes/MaterialDesignColor.Blue.Named.xaml

**Comment by CCRed95** [comment]
thank you, thats awesome! i will look into this tonight or tomorrow.
