### ISSUE TITLE
Increasing the font on a TextBox messes up floating label

### ISSUE THREAD

**Issue by redcurry** [ButchersBoy/MaterialDesignInXamlToolkit#465]
I want to have a large TextBox (like this: https://material.google.com/components/text-fields.html#text-fields-labels), but when I increase the size of the text (FontSize) within the TextBox, the floating label overlaps with the text. It looks like the floating label size is scaled with the TextBox size. In the link above, however, it looks like the label size is constant regardless of the TextBox size.

**Comment by mgnslndh** [comment]
I've also experienced this as a problem for me. 

The current implementation allows for arbitrary content in the hint (label) and use scaling and offsetting to position the hint when it is floating. Previous to 2.0 I think it only allowed text and used a smaller font size or something similar.

I've made a PR #469 that allow you to override the default scale and offset to make floating hints look better on text boxes with larger font size.
