### ISSUE TITLE
HintAssist can't find problem

### ISSUE THREAD

**Issue by tycallen** [ButchersBoy/MaterialDesignInXamlToolkit#467]
Sorry it's a stupid question but how can I solve this problem
![image](https://cloud.githubusercontent.com/assets/3022000/17882885/d081db58-6941-11e6-951b-053ebb4518b1.png)

**Comment by ButchersBoy** [comment]
Have you recently upgraded to 2.0?  If so a full clean and rebuild might fix it...

**Comment by ButchersBoy** [comment]
Closing this as it's not a bug.  If you want help please hit up the gitter channel.
