### ISSUE TITLE
Watermarks for Inputs

### ISSUE THREAD

**Issue by mhn23** [ButchersBoy/MaterialDesignInXamlToolkit#47]

**Comment by ButchersBoy** [comment]
Anything in particular? We already have them on text/combo boxes. Check the demo. Note it uses a different member than standalone MahApps.

**Comment by ButchersBoy** [comment]
Also, see  https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/11

**Comment by mhn23** [comment]
Ah i see it now, i was still using the mahapps helper!

thx bud
