### ISSUE TITLE
DialogHost's height seems to be capped at about 75% of the screen height

### ISSUE THREAD

**Issue by redcurry** [ButchersBoy/MaterialDesignInXamlToolkit#470]
When large content (such an image in an Image control) is displayed using a dialog, the dialog's height seems to go only up to about 75% of the screen's height. The width extends almost the whole screen's width, but not the height. It would be nice to be able to configure what this maximum limit should be.

**Comment by ButchersBoy** [comment]
Just re-tested this and by setting DialogMargin to zero I can hit the full height of the screen?  Do you still have an issue?

**Comment by redcurry** [comment]
I still have an issue, but it looks like the dialog height is not the problem. I need to investigate further and potentially open a different issue. Thanks.

**Comment by emanuelebellini** [comment]
Same problem here. I forked your repo [here](https://github.com/emanuelebellini/MaterialDesignInXamlToolkit), then added a test project with a window which should be full size, but it isn't. In fact, the dialog height is less than the screen. Setting DialogMargin to zero doesn't help. Why is the height limited? Is it possible to have a full-sized dialog window?

**Comment by ButchersBoy** [comment]
I just did a test, I set created a border of height 1200 in my DialogContent, and set DialogHost.DialogMargin="0"...it went full screen...

**Comment by emanuelebellini** [comment]
Sorry, the test solution was corrupted. I'm going to see if it depends on the parent control (i.e. ContentControl), or on some settings in the hierarchy. Then, if I manage to get it full-screen, I'll let you know. Thanks very much.

**Comment by emanuelebellini** [comment]
I've found in [a discussion](http://stackoverflow.com/questions/2633129/cant-create-a-fullscreen-wpf-popup) that the issue could be related to a limitation in size of the popup control, which is 75% of the screen.
The feature of a full-screen popup would be useful if I had to implement a [parent-to-child navigational pattern](https://material.io/guidelines/patterns/navigational-transitions.html#navigational-transitions-parent-to-child), but I'll use another control if I want the content to be sized full-screen.
So I was wondering if you have a counterexample in which you managed to get the popup covering the whole screen. Might it be the same example as mine, having a different behaviour on your computer? Or did you use different settings?

**Comment by ButchersBoy** [comment]
...even better, why don't you post a repo....and let me have a play with it, see whats what...

**Comment by emanuelebellini** [comment]
Yes of course, [here it is](https://github.com/emanuelebellini/MaterialDesignInXamlToolkit). You can open my MaterialDesignPlayground solution.

**Comment by alvarotf** [comment]
I have the same issue. If you set the height of the content in XAML it works fine but If you set it in code behind it goes to 75% max. @ButchersBoy @emanuelebellini

**Comment by emanuelebellini** [comment]
Dear Alvaro,
	yes! But we’ve seen that it isn’t a bug actually, since that component is derived from another one for which that behaviour was intended.
I wanted to use it to implement the mentioned parent-child behaviour, but it isn’t suitable for it. If I wanted, I would have had to choose another component. Maybe it could be possible to suppress that limit with newer releases of the WPF Framework.
Regards,

				Emanuele
