### ISSUE TITLE
ComboBox (within PopupBox) closed when scrolling after value highlighted

### ISSUE THREAD

**Issue by SJMakin** [ButchersBoy/MaterialDesignInXamlToolkit#471]
When ComboBoxes that are placed within PopupBox are scrolled, after a value has been highlighted by the MouseOver, it closes on the MouseUp without changing the value.  

I have tried specifying the StaysOpenOnEdit property but it doesn't seem to have an affect.   

This can be recreated in the Demo by adding some additional items, on the Buttons & Toggles page:

![combo popup bug](https://cloud.githubusercontent.com/assets/13466643/17968585/830fddb8-6ac5-11e6-935a-90c48a9ae57b.gif)

I'm not sure what else to try. Any ideas?

**Comment by SJMakin** [comment]
The problem is due to the logic in lines 650-670 of PopopBox.cs.  Still not sure how to resolve the issue though.

**Comment by ButchersBoy** [comment]
Yes, we've the same issue in the Drawer, so I need tom come up with a common-ish solution.

**Comment by SJMakin** [comment]
Found a solution! See new line below with my initials...

Have given it a decent test and cant see any problems.  Please let me know if you want me to create a pull.

```
                if ((Mouse.Captured as DependencyObject).GetVisualAncestry().Contains(popupBox._popup.Child))
                {
                    // Take capture if one of our children gave up capture (by closing their drop down)
                    if (!popupBox.IsPopupOpen || Mouse.Captured != null || GetCapture() != IntPtr.Zero) return;

                    Mouse.Capture(popupBox, CaptureMode.SubTree);
                    e.Handled = true;
                }
                else
                {
                    if (popupBox.StaysOpen && popupBox.IsPopupOpen)
                    {            
                        // ComboBox fix - SJM           
                        if (GetCapture() != IntPtr.Zero) return;

                        // Take capture back because click happend outside of control
                        Mouse.Capture(popupBox, CaptureMode.SubTree);
                        e.Handled = true;
                    }
                    else
                    {
                        popupBox.Close();
                    }
                }
```

**Comment by ButchersBoy** [comment]
@SJMakin Yes, raise a PR and I will test.
