### ISSUE TITLE
Hello, Is Toast message features can be added ?

### ISSUE THREAD

**Issue by mummyildiz** [ButchersBoy/MaterialDesignInXamlToolkit#476]
Is Toast message features can be added ?

Thank you for the work you do .

**Comment by ButchersBoy** [comment]
There is a snackbar hopefully coming in the next version

**Comment by ButchersBoy** [comment]
Keep your eye in this: https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/pull/404
