### ISSUE TITLE
Checkboxes throw exception in nested DataGrid

### ISSUE THREAD

**Issue by AlanLopez22** [ButchersBoy/MaterialDesignInXamlToolkit#477]
Hi,

I have an issue with DatagridCheckboxColumn only when the datagrid have an inner datagrid in rowdetailtemplate, when i click in DatagridCheckboxColumn the application throw an error, i attached you the error. in one file have the stack trace of the error, another file the error in code in DatagridAssist.cs file and other the example view.

Sorry for my English, i am mexican

![error](https://cloud.githubusercontent.com/assets/20330525/18035897/144fb884-6d14-11e6-97fa-078ff063b2db.PNG)
[StackTrace.txt](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/files/441282/StackTrace.txt)
![view](https://cloud.githubusercontent.com/assets/20330525/18035896/144df170-6d14-11e6-92bb-e638bda8ce9b.PNG)

**Comment by ButchersBoy** [comment]
... Please extract and post the full exception stack trace...

**Comment by ButchersBoy** [comment]
Ignore that comment :)

**Comment by AlanLopez22** [comment]
Hi

any update for this?

**Comment by ButchersBoy** [comment]
Hi, please provide a sample GitHub repo where this can be reproduced.

**Comment by AlanLopez22** [comment]
Hi
In this repository has example project with the issue

https://github.com/AlanLopez22/ExampleDataGridIssue/tree/ExampleBranch

**Comment by AlanLopez22** [comment]
Hi, any update?

**Comment by ButchersBoy** [comment]
There's no code in your repo...

**Comment by AlanLopez22** [comment]
Check again please

**Comment by AlanLopez22** [comment]
New link https://github.com/AlanLopez22/ExampleDataGridIssue

**Comment by AlanLopez22** [comment]
The problem was solved but, do you published the solution to nuget? or i need to copy the dll directly?

**Comment by ButchersBoy** [comment]
You can install from nuget, but you need to select from pre release.
