### ISSUE TITLE
multicolumnCombobox request

### ISSUE THREAD

**Issue by jigneshBadrakhiya** [ButchersBoy/MaterialDesignInXamlToolkit#479]
# This is a place for issues.  Questions are better asked in the Gitter chat room.

# Seriously consider creating and linking to a test repo which takes absolutely minimal setup to illustrate how reproduce the problem.

**Comment by ButchersBoy** [comment]
How does this releate specifically to Material Design?  Is this not something you can build yourself with a standard ComboBox and a DataTemplates, or with the MD Toolkit PopupBox?
