### ISSUE TITLE
Side panels implementation for Dragablz

### ISSUE THREAD

**Issue by QuantumDeveloper** [ButchersBoy/MaterialDesignInXamlToolkit#48]
Just leave it here for the version 1.2, for ex. regarding to waht we descussed earlier.

**Comment by ButchersBoy** [comment]
Wrong project  :) , just having a clean-up

**Comment by QuantumDeveloper** [comment]
Should I open the same in Dragablz projects?

**Comment by ButchersBoy** [comment]
plz
