### ISSUE TITLE
Can't view various demo .xaml files in designer due to exceptions

### ISSUE THREAD

**Issue by woodlandhunter** [ButchersBoy/MaterialDesignInXamlToolkit#485]
As the subject says, getting some exceptions when trying to view .xaml files in the designer

I'm using Visual Studio 2015 Community

 - I pulled down a fresh clone of master (I also tried with the last release, same results)
 - Opened MaterialDesignToolkit.Wpf.sln
 - I selected Build Solution (which 100% succeeded)
 - I attempted to open each .xaml file in the MaterialDesignDemo project

These were the results:

**Buttons.xaml, MenusAndToolBars.xaml, Pickers.xaml:**
```
ArgumentException: 'True' is not a valid value for the 'MaterialDesignThemes.Wpf.ComboBoxAssist.ShowSelectedItem' property on a Setter.`
<large stack trace omitted>
```

**Expander.xaml, Trees.xaml:**
```
InvalidCastException: Specified cast is not valid.
Stacktrace
at System.Windows.Media.Animation.DoubleAnimationBase.GetCurrentValue(Object defaultOriginValue, Object defaultDestinationValue, AnimationClock animationClock)
   at System.Windows.Media.Animation.AnimationStorage.GetCurrentPropertyValue(AnimationStorage storage, DependencyObject d, DependencyProperty dp, PropertyMetadata metadata, Object baseValue)
   at System.Windows.Media.Animation.AnimationStorage.OnCurrentTimeInvalidated(Object sender, EventArgs args)
InnerException: None
```

**IconPack.xaml:**
```
Invalid Markup
The property "DesignData" does not exist in the "http://schemas.microsoft.com/expression/blend/2008" namespace
```

If it's not a problem with the code/projects and it's an issue with my VS install or something of that nature, tips on how to correct it would be great..

**Comment by ButchersBoy** [comment]
Did you restore all nuget packages?

**Comment by punker76** [comment]
@ButchersBoy NuGet packages should be automatically restored by paket if you run Rebuild solution...

**Comment by ButchersBoy** [comment]
@punker76 Oh.  :)  I was just giving a default answer :)

**Comment by punker76** [comment]
@ButchersBoy 🐙

**Comment by woodlandhunter** [comment]
I did try right clicking on the solution and clicking "Restore NuGet Packages" but nothing seemed to happen. 
```
PM> Get-Package
No packages installed.
```

Are there any dependencies handled by nuget for the demos and related assemblies? Seems like paket is used.

(I only see a packages.config in the mdresgen folder which does seem to be included in the solution)

**Comment by punker76** [comment]
@woodlandhunter As I had already said, you need only `Rebuild Solution` to get all NuGet packages restored. `Paket` uses this dependency file https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/paket.dependencies to get all packages.

But you said `I selected Build Solution (which 100% succeeded)`... so maybe there is something other wrong?

**Comment by ButchersBoy** [comment]
Project runs OK?

**Comment by woodlandhunter** [comment]
@punker76 I am just telling you guys that I did for good measure. However, I don't see any nuget packages, which is why i was asking what nuget packages I should expect to be restored/see.

> Project runs OK?

The projects all build and the demo runs perfectly. It just viewing those specific .xaml files in the designer that is still not working.

I may just try blowing up my VS install and starting from scratch if you can confirm my repro steps aren't  giving you guys problems.

**Comment by ButchersBoy** [comment]
In all honesty, I rarely use the designer, only when people report issues, so if it compiles and runs, then yeah, you may be experiencing a common designer issue. I will have a look when I get chance.

**Comment by mgnslndh** [comment]
I've seen this exception in my designer as well. Only for the demo project, never for my own projects. Looks like an animation that blows up at design time. 

@woodlandhunter You don't have to reinstall VS. Just live with it. Or submit PR for better design time experience :) I usually modify the XAML and run the demo to see the effects of my changes.

**Comment by woodlandhunter** [comment]
@punker76 That's great. I was able to figure out it was related to those by commenting until no exception occurred but I didn't know the best way to correct it.

Did you have any insight into the other exception?

Thanks again

**Comment by ButchersBoy** [comment]
- [ ] Buttons.xaml, MenusAndToolBars.xaml, Pickers.xaml
- [ ] Expander.xaml, Trees.xaml
- [ ] IconPack.xaml

**Comment by ButchersBoy** [comment]
Designer opens, can't say it looks great though :)
