### ISSUE TITLE
Dependancy issue Unable to find dependancy "MATERIAL DESIGN COLOURS"

### ISSUE THREAD

**Issue by itechy21** [ButchersBoy/MaterialDesignInXamlToolkit#49]
(Signature='(null)' Version='0.0.0.102') of assembly 'MaterialDesignThemes.Wpf.dll'
when trying to create a deployment wizard. And when run it fails to load properly. I don't think this is a local issue as it used to work before I updated...

**Comment by ButchersBoy** [comment]
@itechy21 what version of Visual Studio are you using?

**Comment by itechy21** [comment]
2013 Pro

**Comment by ButchersBoy** [comment]
Using the InstallSheild thingy?

**Comment by itechy21** [comment]
The [Microsoft Visual Studio 2013 Installer Projects Extension thingy]https://visualstudiogallery.msdn.microsoft.com/9abe329c-9bba-44a1-be59-0fbf6151054d)
I avoided Install-shield as I prefer this one :grinning:

**Comment by ButchersBoy** [comment]
Oh _that_ thingy!

**Comment by ButchersBoy** [comment]
Had to try on the VS2015 version on the current box I am on, but selected "Deployment Wizard" > ... > "Primary Output" and it seemed to detect the Colors assembly fine.  Are you not seeing what I'm seeing below?

![image](https://cloud.githubusercontent.com/assets/658107/9679212/897a6316-52e4-11e5-87f5-c91fdf476840.png)

![image](https://cloud.githubusercontent.com/assets/658107/9679216/9238a4d6-52e4-11e5-9a11-7e457922dd27.png)

**Comment by itechy21** [comment]
exactly what I am seeing pretty much. Apart from the fact that they aren't detected automatically as dependency

**Comment by ButchersBoy** [comment]
But I think selecting Primary Output is the correct way to do it, which picks them up.  So is there an issue?

**Comment by itechy21** [comment]
Don't really think there was an issue so. Just thought that there might have been :sweat:
