### ISSUE TITLE
Help with textbox

### ISSUE THREAD

**Issue by sagevpremium** [ButchersBoy/MaterialDesignInXamlToolkit#495]
Hi, i have problem with textbox hint.

When font is small everythink is ok, but when i use largest font the hint in on my text. i tried use code from demo 
`<TextBox Grid.Row="6" Grid.Column="3" materialDesign:HintAssist.IsFloating="True"
                 materialDesign:HintAssist.Hint="Large Font"

```
             materialDesign:HintAssist.FloatingScale="0.50"                 
             Text="Some Text"

             FontSize="24"/>`
```

But it's still the same.

**Comment by ButchersBoy** [comment]
Which version are you using? Latest pre release?

**Comment by sagevpremium** [comment]
Yes

**Comment by ButchersBoy** [comment]
Please post a sample repo.

**Comment by sagevpremium** [comment]
`<Controls:MetroWindow x:Class="Test.LoginPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
        xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro" 
        xmlns:local="clr-namespace:Test"
        mc:Ignorable="d"
        Title="Login page" Height="1220" Width="900" WindowState="Maximized" Background="#FFE8C215">

    <materialDesign:DialogHost Identifier="RootDialog">
        <ScrollViewer VerticalScrollBarVisibility="Auto" Background="White">
            <Grid>
                ...
                    <TextBox x:Name="loginText" materialDesign:HintAssist.FloatingScale="1" Style="{StaticResource MaterialDesignFloatingHintTextBox}" materialDesign:TextFieldAssist.TextBoxViewMargin="1 0 1 0" Margin="0,350,0,0" materialDesign:HintAssist.IsFloating="True" HorizontalAlignment="Center" VerticalAlignment="Top" Width="400" FontSize="36" Height="100" Background="White" Padding="6,0,0,2">
                        <materialDesign:HintAssist.Hint>
                            <StackPanel Orientation="Horizontal" Margin="0 0 0 0">
                                <materialDesign:PackIcon Kind="Account" Width="50" Height="50" />
                                <TextBlock Padding="5,0,0,0">Enter login</TextBlock>
                            </StackPanel>
                        </materialDesign:HintAssist.Hint>
                    </TextBox>
            </Grid>
        </ScrollViewer>
    </materialDesign:DialogHost>
</Controls:MetroWindow>`

**Comment by ButchersBoy** [comment]
Try tweaking FloatingOffset:

```
materialDesign:HintAssist.FloatingScale=".56" 
materialDesign:HintAssist.FloatingOffset="1,-42"
```

![image](https://cloud.githubusercontent.com/assets/658107/18346462/2e3c99f4-75b8-11e6-8dd0-583fdcdb1f89.png)

**Comment by sagevpremium** [comment]
Just amazing! Thx You so much :)

**Comment by sagevpremium** [comment]
Ok one more question haha :) The same issue but with passwordbox

**Comment by ButchersBoy** [comment]
Might need to update the style...

**Comment by AmyrRamirez** [comment]
Hello, how can I change the border color of the text box when it receives the focus ... the purple color that brings by default

**Comment by Shreyasj96** [comment]
Why doesn't clear button in the textbox doesn't bring focus back to the textbox after clearing the contents?
