### ISSUE TITLE
Textbox Context Menu and Spell Check

### ISSUE THREAD

**Issue by jamesakadamingo** [ButchersBoy/MaterialDesignInXamlToolkit#497]
I have come accross a problem with the context menu changes to TextBoxes. In the code (MaterialDesignTheme.TextBox.xaml) on line 27 is a comment "cludge the default context menu". It seems this "cludge" is preventing the normal spell check menu from displaying.

Sorry for not adding code examples; but I don't have access at the moment and I wanted to submit the bug before I forgot!

**Comment by jherbert** [comment]
Pretty sure this behavior is expected. See https://msdn.microsoft.com/en-us/library/bb613557(v=vs.110).aspx on how to implement spell checking with a custom context menu.
