### ISSUE TITLE
Change icon when application is running

### ISSUE THREAD

**Issue by sagevpremium** [ButchersBoy/MaterialDesignInXamlToolkit#498]
Hi,

I have somethink like that:

`<materialDesign:PackIcon x:Name="testIcon" Kind="{Binding iconToChange}" Height="56" Width="56" Foreground="{Binding iconColor}" Background="{x:Null}" HorizontalAlignment="Center" VerticalAlignment="Center" />`

and i want to change this icon, and foreground later in application on button click:

` public string iconToChange { get; set; }
        public string iconColor { get; set; }`

`iconToChange = "CheckboxMarkedOutline";
                iconColor = "#FF0FB01E";  `

But nothing changed, i think the layout must be reloaded? Or i'm wrong?

**Comment by ButchersBoy** [comment]
Have you tried using the correct types in your DataContext/ViewModel? PackIconKind and Brush?

**Comment by sagevpremium** [comment]
This, what i have is working but only when i use it after InitializeComponent();

**Comment by ButchersBoy** [comment]
???

**Comment by sagevpremium** [comment]
I changed to:

`public PackIconKind iconCashRegister { get; set; }
iconCashRegister = PackIconKind.Octagon;`

But it's only working in main function after InitializeComponent();

**Comment by sagevpremium** [comment]
But how to change icons in my own function? :D

**Comment by ButchersBoy** [comment]
You have to post more code.

**Comment by sagevpremium** [comment]
It's my sample application :)
[WpfApplication1.zip](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/files/471624/WpfApplication1.zip)

**Comment by sagevpremium** [comment]
Ok You can close it :) I'm too tired and make so easy mistakes haha :)
