### ISSUE TITLE
Menus

### ISSUE THREAD

**Issue by ButchersBoy** [ButchersBoy/MaterialDesignInXamlToolkit#5]

**Comment by AdilVirani** [comment]
Subscribed :+1:

**Comment by ButchersBoy** [comment]
...making a start...

**Comment by AdilVirani** [comment]
Sweet!!! Thanks a bunch man

**Comment by ButchersBoy** [comment]
Baddaboom!

![materialdesignmenuitems](https://cloud.githubusercontent.com/assets/658107/8557564/1ab7f69e-24f6-11e5-8e0a-d47e61d04caf.jpg)
