### ISSUE TITLE
wpf:TextField.HintOpacity not working on TextBox

### ISSUE THREAD

**Issue by JamesIrish** [ButchersBoy/MaterialDesignInXamlToolkit#50]
Hi James,

The attached property wpf:TextField.HintOpacity works correctly on ComboBox but does not on TextBox.  I'm using version 0.93. 

```xaml
<ComboBox Grid.Column="0" Grid.Row="0" HorizontalAlignment="Right" Style="{StaticResource EnvCombo}" wpf:TextField.Hint="Source" wpf:TextField.HintOpacity="0.4"/>
<TextBox Grid.Column="1" Grid.Row="0" HorizontalAlignment="Stretch" Style="{StaticResource MaterialDesignTextBox}" wpf:TextField.Hint="Query" wpf:TextField.HintOpacity="0.4" VerticalAlignment="Center"/>
<ComboBox Grid.Column="2" Grid.Row="0" HorizontalAlignment="Left" Style="{StaticResource EnvCombo}" wpf:TextField.Hint="Target" wpf:TextField.HintOpacity="0.4"/>
```

Many thanks,

James

**Comment by ButchersBoy** [comment]
OK...as an aside I will probably make the default darker...can't remember my reasoning on them being so light, but just checked the latest Google guidelines and they are darker.

**Comment by ButchersBoy** [comment]
Just tested on the latest version in the test project...works.  But I have made the default darker.

**Comment by ButchersBoy** [comment]
FYI, there will be a small breaking change soon. TextField will become TextFieldAssist. Want to line up all the APIs before v1.

**Comment by JamesIrish** [comment]
Thanks, I've just updated our app to the newer version and it's fixed the problem.  No worries regarding the breaking change - our project is still reasonably small at the moment.
