### ISSUE TITLE
Textbox in material design dialog loses focus automatically sometimes while typing, or something without doing anything.

### ISSUE THREAD

**Issue by sdhakal** [ButchersBoy/MaterialDesignInXamlToolkit#502]
I have a textbox inside material design dialog  (well, several textboxes) that are behaving improperly. When I set my focus to the textbox (with or without typing anything), after some time that particular textbox loses its focus automatically. It happens fast for some textboxes whereas slow for some but occurs in all. Its killing me for last 3 days but couldn't find anything. Its just a normal textbox. Please help.

**Comment by ButchersBoy** [comment]
It's not a behaviour I have seen.  Please post a sample repo where the issue can be easily reproduced.

**Comment by ButchersBoy** [comment]
Closing.  If you can provide a sample repo please re-open.
