### ISSUE TITLE
WPF native web browser issue

### ISSUE THREAD

**Issue by swingfox** [ButchersBoy/MaterialDesignInXamlToolkit#512]
I have a program that uses WPF web browser. However, when I use Materialize dialogs. The web browser part could not be greyed out unlike the other controls. 

I tried replacing my web browser element to a button and when I open a Materialize dialog the button is now part of the greyed portion of the window. Is this because of the native web browser of WPF?

Thanks :)

**Comment by ButchersBoy** [comment]
Hi, this might help: https://github.com/MahApps/MahApps.Metro/wiki/FAQ

**Comment by swingfox** [comment]
Thanks for the quick response. I tried Solution #2 in the first question and it works. :)

However when I went back to the Visual Studio XAML designer every WPF Design I created has turned back to native graphical design, like WinForms. When I highlight some errors in the designer (For example, a Style property ToggleButton in WPF. It says the MaterialDesignHamburgerToggleButton could not be resolved.

This is now harder than I thought. All of my designs was converted to native WinForms and I cannot continue unless I get back to the original WPF design of my application.

**Comment by ButchersBoy** [comment]
But do they work at run-time?

**Comment by swingfox** [comment]
Yes, WPF controls shows during run time but when I went back to the designer everything turned into old windows style and all of my design prototypes are not in the same place anymore. I removed all of the references about that dll and rebuild my project yet it still remains the same.
