### ISSUE TITLE
Button automatically disabled while opening Dialog

### ISSUE THREAD

**Issue by furiousbuilder** [ButchersBoy/MaterialDesignInXamlToolkit#515]
Hi, I'm trying to implement a dialog from a button but I can't click the button as soon as I add Command="{x:Static materialDesign:DialogHost.OpenDialogCommand}" inside.
![screenshot 8](https://cloud.githubusercontent.com/assets/10899984/19247015/69b4f578-8f29-11e6-8020-97e93e3425c9.png)
Do you know  why ? 
Thank you !

**Comment by ButchersBoy** [comment]
``` DialogHost.OpenDialogCommand ``` is a routed command. It  must operate inside a ``` DialogHost ``` , which typically you have near to the root of your application (see the demo/source).

**Comment by furiousbuilder** [comment]
I'm searching in the demo but I don't see where is the command associated with that. I'm sorry, I'm trying to learn C#, before I was using Material Design Toolkit in VB.Net

**Comment by ButchersBoy** [comment]
You need a  ``` DialogHost ``` at the root of your application: https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/MainWindow.xaml#L38
