### ISSUE TITLE
Does not build in Visual Studio 2013

### ISSUE THREAD

**Issue by wildblue** [ButchersBoy/MaterialDesignInXamlToolkit#516]
1>------ Neues Erstellen gestartet: Projekt: MaterialDesignColors.Wpf, Konfiguration: Debug Any CPU ------
1>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MaterialDesignColors.Wpf\Swatch.cs(43,32,43,34): error CS1002: ; erwartet.
1>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MaterialDesignColors.Wpf\Swatch.cs(43,49,43,50): error CS1519: Ungültiges Token '(' in Klasse, Struktur oder Schnittstellenmemberdeklaration.
1>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MaterialDesignColors.Wpf\SwatchesProvider.cs(103,17,103,18): error CS1056: Unerwartetes Zeichen '$'.
2>------ Neues Erstellen gestartet: Projekt: MaterialDesignThemes.Wpf, Konfiguration: Debug Any CPU ------
3>------ Neues Erstellen gestartet: Projekt: MaterialDesignColors.Wpf.Tests, Konfiguration: Debug Any CPU ------
2>  Paket version 3.3.6.0
2>  0 seconds - ready.
2>CSC : warning CS1691: 'CS1591' ist keine gültige Warnungsnummer.
2>CSC : error CS0006: Die Metadatendatei 'c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MaterialDesignColors.Wpf\bin\Debug\MaterialDesignColors.dll' konnte nicht gefunden werden.
3>  Paket version 3.3.6.0
3>  packages folder is locked by paket.exe (PID = 1660). Waiting...
3>  1 second - ready.
3>CSC : error CS0006: Die Metadatendatei 'c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MaterialDesignColors.Wpf\bin\Debug\MaterialDesignColors.dll' konnte nicht gefunden werden.
4>------ Neues Erstellen gestartet: Projekt: MaterialDesignThemes.MahApps, Konfiguration: Debug Any CPU ------
5>------ Neues Erstellen gestartet: Projekt: MaterialDesignDemo, Konfiguration: Debug Any CPU ------
6>------ Neues Erstellen gestartet: Projekt: MaterialDesignThemes.Wpf.Tests, Konfiguration: Debug Any CPU ------
5>  Paket version 3.3.6.0
5>  0 seconds - ready.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\Buttons.xaml(41,22): error MC3074: Das Tag "PackIcon" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 41 Position 22.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\Cards.xaml(18,10): error MC3074: Das Tag "Card" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 18 Position 10.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\Chips.xaml(18,18): error MC3074: Das Tag "Chip" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 18 Position 18.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\ColorZones.xaml(14,14): error MC3074: Das Tag "ColorZone" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 14 Position 14.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\Domain\SampleMessageDialog.xaml(22,17): error MC3050: Der Typ "DialogHost"wurde nicht gefunden. Beachten Sie, dass bei Typnamen die Groß- und Kleinschreibung berücksichtigt wird.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\Expander.xaml(50,10): error MC3074: Das Tag "Card" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 50 Position 10.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\Dialogs.xaml(42,18): error MC3074: Das Tag "DialogHost" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 42 Position 18.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\Domain\Sample4Dialog.xaml(13,18): error MC3072: Die Eigenschaft "HintAssist.Hint" ist im XML-Namespace "clr-namespace:MaterialDesignThemes.Wpf;assembly=MaterialDesignThemes.Wpf" nicht vorhanden. Zeile 13 Position 18.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\Domain\SampleDialog.xaml(21,18): error MC3072: Die Eigenschaft "HintAssist.Hint" ist im XML-Namespace "clr-namespace:MaterialDesignThemes.Wpf;assembly=MaterialDesignThemes.Wpf" nicht vorhanden. Zeile 21 Position 18.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\Grids.xaml(20,23): error MC3072: Die Eigenschaft "DataGridAssist.CellPadding" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 20 Position 23.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\GroupBoxes.xaml(34,132): error MC3072: Die Eigenschaft "ShadowAssist.ShadowDepth" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 34 Position 132.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\Home.xaml(34,25): error MC3050: Der Typ "DrawerHost"wurde nicht gefunden. Beachten Sie, dass bei Typnamen die Groß- und Kleinschreibung berücksichtigt wird.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\IconPack.xaml(47,26): error MC3074: Das Tag "PackIcon" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 47 Position 26.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\MainWindow.xaml(38,6): error MC3074: Das Tag "DialogHost" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 38 Position 6.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\MenusAndToolBars.xaml(14,26): error MC3074: Das Tag "PackIcon" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 14 Position 26.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\PaletteSelector.xaml(31,71): error MC3066: Von dem Typverweis kann kein öffentlicher Typ mit dem Namen "Swatch" gefunden werden. Zeile 31 Position 71.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\Pickers.xaml(27,82): error MC3072: Die Eigenschaft "HintAssist.Hint" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 27 Position 82.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\Progress.xaml(34,49): error MC3072: Die Eigenschaft "TransitionAssist.DisableTransitions" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 34 Position 49.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\ProvingGround.xaml(35,18): error MC3074: Das Tag "PackIcon" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 35 Position 18.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\Shadows.xaml(16,21): error MC3072: Die Eigenschaft "ShadowAssist.ShadowDepth" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 16 Position 21.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\TextFields.xaml(39,126): error MC3066: Von dem Typverweis kann kein öffentlicher Typ mit dem Namen "PackIcon" gefunden werden. Zeile 39 Position 126.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\TransitionsDemo\Slide1_Intro.xaml(11,6): error MC3074: Das Tag "ColorZone" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 11 Position 6.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\TransitionsDemo\Slide2_Intro.xaml(9,6): error MC3074: Das Tag "ColorZone" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 9 Position 6.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\TransitionsDemo\Slide3_Intro.xaml(9,6): error MC3074: Das Tag "ColorZone" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 9 Position 6.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\TransitionsDemo\Slide4_CombineTransitions.xaml(10,6): error MC3074: Das Tag "ColorZone" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 10 Position 6.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\TransitionsDemo\Slide5_TransitioningContent.xaml(17,10): error MC3074: Das Tag "TransitioningContent" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 17 Position 10.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\TransitionsDemo\Slide6_MVVM.xaml(10,6): error MC3074: Das Tag "ColorZone" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 10 Position 6.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\TransitionsDemo\TransitionsDemoHome.xaml(18,10): error MC3074: Das Tag "Transitioner" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 18 Position 10.
5>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MainDemo.Wpf\Trees.xaml(113,14): error MC3074: Das Tag "PopupBox" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 113 Position 14.
6>  Paket version 3.3.6.0
6>  0 seconds - ready.
6>CSC : error CS0006: Die Metadatendatei 'c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MaterialDesignThemes.Wpf\bin\Debug\MaterialDesignThemes.Wpf.dll' konnte nicht gefunden werden.
4>  Paket version 3.3.6.0
4>  packages folder is locked by paket.exe (PID = 14408). Waiting...
4>  1 second - ready.
4>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MaterialDesignThemes.MahApps\Themes\MaterialDesignTheme.MahApps.Flyout.xaml(11,10): error MC3074: Das Tag "ColorZone" ist im XML-Namespace "clr-namespace:MaterialDesignThemes.Wpf;assembly=MaterialDesignThemes.Wpf" nicht vorhanden. Zeile 11 Position 10.
4>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MaterialDesignThemes.MahApps\Themes\MaterialDesignTheme.MahApps.WindowCommands.xaml(10,133): error MC3066: Von dem Typverweis kann kein öffentlicher Typ mit dem Namen "PopupBox" gefunden werden. Zeile 10 Position 133.
7>------ Neues Erstellen gestartet: Projekt: MahAppsDragablzDemo, Konfiguration: Debug Any CPU ------
7>  Paket version 3.3.6.0
7>  1 second - ready.
7>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MahMaterialDragablzMashUp\MainWindow.xaml(24,14): error MC3074: Das Tag "PopupBox" ist im XML-Namespace "http://materialdesigninxaml.net/winfx/xaml/themes" nicht vorhanden. Zeile 24 Position 14.
7>c:\\SDK\MaterialDesignInXamlToolkit-2.1.0\MahMaterialDragablzMashUp\PaletteSelector.xaml(33,71): error MC3066: Von dem Typverweis kann kein öffentlicher Typ mit dem Namen "Swatch" gefunden werden. Zeile 33 Position 71.
========== Alles neu erstellen: 0 erfolgreich, 7 fehlerhaft, 0 übersprungen ==========

**Comment by ButchersBoy** [comment]
Hi, the **source** (including the demo) will not build in anything less than VS2015.  I suggest if you can't get it you try the VS Community Edition.

However, **you can use the nuget package** to develop in VS2013; you just wont have the demo to refer to.
