### ISSUE TITLE
TextBox : space between text and line

### ISSUE THREAD

**Issue by Spoelle** [ButchersBoy/MaterialDesignInXamlToolkit#519]
Is it possible to decrease the space between text and line?
Thank you.

![image](https://cloud.githubusercontent.com/assets/19902865/19436387/0f091fae-9470-11e6-9373-cfe7e50951b0.png)

**Comment by ButchersBoy** [comment]
Currently, without you restyling the template, no.

**Comment by Spoelle** [comment]
Ok, thank you for your quick answer.

**Comment by Spoelle** [comment]
Found solution:
I my style for the textbox I set the Padding Property = 0,0,0,**-2**

![image](https://cloud.githubusercontent.com/assets/19902865/19439402/38b738fa-947e-11e6-8f91-ed89a78dd600.png)


![image](https://cloud.githubusercontent.com/assets/19902865/19439444/5b63026c-947e-11e6-9e6a-d28fca03b9eb.png)

**Comment by ButchersBoy** [comment]
ah...see, dont always trust me :)
