### ISSUE TITLE
The button effect is too small

### ISSUE THREAD

**Issue by mountainviper** [ButchersBoy/MaterialDesignInXamlToolkit#52]
Hi,

So I added this awesome toolkit to my project. When I click a button, it should animate the entire button area right? It only animated the area around the click in a circle. Is there any setting to be done?

**Comment by ButchersBoy** [comment]
Hey, I'm actually working on improving the effects right now, so you there will be some improvements over the next few days.  

Note, I've moved the nuget package to beta, so you'll need to include pre-release packages in your nuget search to see the latest changes.

**Comment by mountainviper** [comment]
Awesome thanks! Looking forward to it.
