### ISSUE TITLE
Tab Navigation Bug Sample

### ISSUE THREAD

**Issue by Kawbi** [ButchersBoy/MaterialDesignInXamlToolkit#525]
Hi,

Tab Navigation stops working upon using DialogHost. - Not using an MVVM approach in this sample but this is also reproducible when using the original MaterialDeisgnInXamlToolkit project. 

In order to reproduce this issue; Press "Open Popup" and then the "Close" buttons. (Use mouse for both).

Now try to use the tab key to navigate through controls. Also note that the shortcuts are not working when this problem happens - ex: ALT + O.

This problem doesn't happen always, if you aren't able to reproduce this, try again with the above example.

Sometimes, ALT + Tab and ALT Tabbing again fixes the problem, you are able to navigate through controls and use shortcuts. - My guess is that DialogHost is not closing properly.

[TabNavigation Bug Sample.zip](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/files/550048/TabNavigation.Bug.Sample.zip)

Thanks 👍

**Comment by ButchersBoy** [comment]
Same problem in reverse :)

![image](https://cloud.githubusercontent.com/assets/658107/19678629/6c4f4626-9a96-11e6-8b68-232cb8c1d663.png)

**Comment by Kawbi** [comment]
Hi, what about this link: https://ufile.io/3da12

**Comment by Kawbi** [comment]
I managed to upload the file on this thread, take a look at the first post/comment.

Thanks!

**Comment by ButchersBoy** [comment]
Same.  But I won't be able to look at it today anyway.  In the meantime if you can find someway of creating a GitHub repo that would be beneficial.

**Comment by Kawbi** [comment]
I will try to create a repo. But that's weird since the file is now uploaded on the Github server.

**Comment by Kawbi** [comment]
Hi James,

I managed to upload the file on Github itself!

**Comment by Kawbi** [comment]
Hi, just tested your patch fix. Works flawlessly! Thank you :)
