### ISSUE TITLE
Can any one help me to add sub list to the list for Menu  in material design for wpf application ... For Example I have Add as a Main Header under that i have to add subitem so that when i click subitem it navigates to that page

### ISSUE THREAD

**Issue by raghuram8123** [ButchersBoy/MaterialDesignInXamlToolkit#529]
# PLEASE READ BEFORE POSTING AN ISSUE

# This is a place for issues.  Questions are better asked in the Gitter chat room.

# Seriously consider creating and linking to a test repo which takes absolutely minimal setup to illustrate how reproduce the problem. My time is limited and and .Zip files, code snippets and partial examples are often a code snippet.  GitHub also provides great communication and code review tools which can be utilised.

# HOW TO POST A GOOD SAMPLE.  Follow these guidelines and I will most likely look at the issue sooner:

* Post a full GitHub repository. Not a zip file, half baked snippet etc.  If GitHub is new to you consider it a great learning opportunity and chance to get involved.
* The repository should have just ONE step max for me to get running, and that is "Restore NuGet Packages".  If there are any other missing dependencies, or uncompiling features I will most likely move on to another issue.
* I'm not trying to be awkward.  I'm just busy and I'm helping a lot of people, not just you, so help me out and I will help you out.

**Comment by spiegelp** [comment]
Do you mean the menu inside the navigation drawer? The demo uses a ListBox. Consider to create a class `MenuMainItem` and a class `MenuSubItem`. Then define a DataTemplate for each class. `MenuSubItem` might get more margin to the left and a smaller font size. Finally add objects of these two classes in the correct order to the ListBox.

I already built a complex menu with hierarchies inside an ItemControl. I can create a simple example repository if you like. 

@ButchersBoy Or should I create such classes and templates as feature for the API?

**Comment by raghuram8123** [comment]
ya if you have please do send me

**Comment by ButchersBoy** [comment]
I don't want to add more classes for dealing with menus, there's plenty of existing controls to do that.  Further styling for drawer type menus for _existing_ controls is something I'm considering for the future.

**Comment by spiegelp** [comment]
@raghuram8123 You will find the example repository at [DrawerItemExample](https://github.com/spiegelp/DrawerItemExample). 

The ListBox solution is suitable for basic menus. The custom classes are a proposal to realise a more sophisticated menu considering detailed UI and specific behaviour of your own application. However this exceeds the scope of the API. Just take the API's basics and compose them for your specific needs.
