### ISSUE TITLE
Graphical bug while resizing the window

### ISSUE THREAD

**Issue by furiousbuilder** [ButchersBoy/MaterialDesignInXamlToolkit#530]
Hi !

I'm encountering a bad issue with materialdesigninxaml toolkit that happen with every apps using it, even your demo. When I maximize the window, the app appears to be glitchy like in this screenshot : 
![screenshot 39](https://cloud.githubusercontent.com/assets/10899984/19804932/aa7731f2-9d11-11e6-9d96-42686e00a4f1.png)

**Comment by ButchersBoy** [comment]
You might want to force software rendering...

```
RenderOptions.ProcessRenderMode = RenderMode.SoftwareOnly;
```

**Comment by furiousbuilder** [comment]
Ohh thanks for the tip, I used this and all is fine now :) 
`    public partial class App : Application
    {
        public bool ForceSoftwareRendering
        {
            get
            {
                int renderingTier = (System.Windows.Media.RenderCapability.Tier >> 16);
                return renderingTier == 0;
            }
        }
        protected override void OnStartup(StartupEventArgs e)
        {
            if (ForceSoftwareRendering)
                RenderOptions.ProcessRenderMode = System.Windows.Interop.RenderMode.SoftwareOnly;
        }
    }`
