### ISSUE TITLE
Different MaterialDesignFloatingHintComboBox Hint behavior in 2.1 compared to 1.5

### ISSUE THREAD

**Issue by stigrune** [ButchersBoy/MaterialDesignInXamlToolkit#532]
After updating from 1.5 to 2.1 I noticed different Hint behavior with MaterialDesignFloatingHintComboBox when selecting an empty ComboBoxItem. 

I have created a test repo here: https://github.com/stigrune/MaterialDesignInXamlToolkit-BugReport 

**Steps**
![bugreport-step0](https://cloud.githubusercontent.com/assets/1052748/19884473/2e952a6a-a01a-11e6-93c5-b6ae95a241fd.PNG)
Select something in the ComboBox. 
![bugreport-step1](https://cloud.githubusercontent.com/assets/1052748/19884478/34515bcc-a01a-11e6-81b8-204da0f2c6e7.PNG)
Then select the blank item in the top of the list.
![bugreport-step2](https://cloud.githubusercontent.com/assets/1052748/19884483/36f61796-a01a-11e6-9e59-b2c36dada0f3.PNG)
As you can see in 1.5 the hint reset to its starting position. But in 2.1 it stays floated.
![bugreport-step3](https://cloud.githubusercontent.com/assets/1052748/19884487/39aff8da-a01a-11e6-98d9-4b5e1c41701d.PNG)

**Comment by EdonGashi** [comment]
Hello, I made this change in #417.

This was intentional. The reasoning behind this has been that the hint should only be displayed when the ComboBox has no selection at all. With this idea, an empty item counts as a selection, because both the SelectedItem != null and SelectedIndex != -1.

This behavior occurs only when the ComboBox is non-editable, because in a non-editable ComboBox it is the programmer's decision how to supply the displayed items and how to handle blank values.

In my opinion a blank option creates confusion no matter the hint behavior. It would be better to put a `None` or `(blank)` option instead.

I might not know your specific issue with the new behavior and I apologize if this has caused any inconvenience. I have no say in the project but we could raise a PR if a change is necessary. Thanks.

**Comment by stigrune** [comment]
Thank you for the thorough answer and suggestion Edon. 

Using a blank item on top of the collection seems to be widely accepted approach for deselecting a noneditable combobox in WPF. With your suggestion to use `None` or `(blank)` the nice floating visual hint reset animation will never happen when “deselecting”. I really like this animation when deselecting as its very clear and gives the user a visual feedback that nothing is selected without having to read. 

It boils down to a question of preferred method for deselecting, and how each individual developer would expect this style/hint to work. For me the 1.5 behavior was the natural way, and when I saw the 2.1 I was sure it was a bug, hence this reported issue. 

If James as the project owner think the current 2.1 behavior is correct I will consider implementing your suggestion. Or even override the setter in the selected property and override it to be `null` if the blank item is selected, although I don’t find this last solution ideal.

**Comment by ButchersBoy** [comment]
Hi @EdonGashi , thanks for getting back on this.

I agree that non-editable combo boxes have always been a little weird regarding empty values.  It's a close thing, but I also think the screen shot we are looking at in 2.1 is weird also, and we go back to 1.5 behaviour...can your raise the PR for this?

**Comment by EdonGashi** [comment]
I agree that this is a matter of perspective on what is considered an empty ComboBox.

To restore previous behavior you can implement a class level handler to check if the selection matches a criteria, based on which you can deselect the combobox. This has the added benefit that your ComboBox will count as deselected in code.

```cs
// or Main()
static MainWindow()
{
    EventManager.RegisterClassHandler(typeof(ComboBox),
        ComboBox.SelectionChangedEvent,
        new SelectionChangedEventHandler(DeselectWhenEmpty));
}

private static void DeselectWhenEmpty(object sender, SelectionChangedEventArgs e)
{
    ComboBox cb = (ComboBox)sender;
    if (cb.SelectedIndex == -1) return;
    ComboBoxItem comboBoxItem = cb.SelectedItem as ComboBoxItem;
    if (comboBoxItem != null)
    {
        string value = comboBoxItem.Content?.ToString();
        if (string.IsNullOrEmpty(value) || value == "None")
        {
            cb.SetCurrentValue(ComboBox.SelectedItemProperty, null);
        }
    }
    else
    {
        // Might be a plain string instead of ComboBoxItem
        string value = cb.SelectedItem as string;
        if (value == "" || value == "None")
        {
            cb.SetCurrentValue(ComboBox.SelectedItemProperty, null);
        }
    }
}
```

**Comment by EdonGashi** [comment]
Hey @ButchersBoy, no problem at all. Will do that in a moment.

**Comment by EdonGashi** [comment]
Added PR #533.

**Comment by ButchersBoy** [comment]
@EdonGashi thanks...OK, when I get 5 minutes I will try out the PR locally and get a better feel for it

**Comment by stigrune** [comment]
Thank you both for the quick responses and fix! :)
I do however disagree that this bug should be closed. The fix should also work for custom types with DisplayMemberPath as it did in version 1.5. 

I updated my test repo to version 2.2.0-ci720 and included a combobox using DisplayMemberPath.

![notfixed](https://cloud.githubusercontent.com/assets/1052748/19964823/370b89a4-a1c4-11e6-80ef-29b39cbadf9c.PNG)

**Comment by EdonGashi** [comment]
The cause of all these troubles is that the SelectionChanged of the ComboBox gets fired before the .Text property is updated. Either a rework of the hint proxy is necessary or it needs to listen to a later event.

http://stackoverflow.com/questions/2961118/wpf-combobox-selectionchanged-event-has-old-value-not-new

A suggestion here seems to be to listen to DropDownClosed, but that is probably unreliable.

To emulate DisplayMember path in code would require reflection, and that too doesn't sound right...

.Text is a DependencyProperty so some sort of binding could be established to react to its changes.

If this issue outweighs the color bug we can revert completely to the 1.5 behavior. I will look into these ideas and see if I can find a reasonable solution.

**Comment by EdonGashi** [comment]
I found this neat DependencyPropertyListener here:
http://stackoverflow.com/questions/4764916/listen-to-changes-of-dependency-property

This allowed me to listen to the .Text property without bothering with the selection events. Even in editable comboboxes you don't have to subscribe to the inner textbox change event as that too will update .Text eventually.

I didn't test this 100% so @stigrune could you please make some tests with this in your repo.

https://github.com/EdonGashi/MaterialDesignInXamlToolkit/tree/ComboBoxHint

If it works as expected I PR this branch once again.

**Comment by ButchersBoy** [comment]
Think I have a simple way of dealing with this...

**Comment by EdonGashi** [comment]
I'm afraid this caused the focus color bug to come back... Try switching back and forth from blank to an item back to notice it.

![colorbug](https://cloud.githubusercontent.com/assets/12145268/20007992/0a912984-a29f-11e6-84d8-9267ec4c33e5.png)

IsEmpty() is probing Combobox.Text, but IsEmpty is called on SelectionChanged, and that event is fired before the .Text gets a chance to update.

**Comment by ButchersBoy** [comment]
We will squash this balloon :)

**Comment by EdonGashi** [comment]
😆 This is a bad design from wpf... they should have named it SelectionChanging and added a proper SelectionChanged..

The proxy hint API was fine, it's the early event that's causing this. Shall I pr my solution?

**Comment by ButchersBoy** [comment]
We will beat the system 👹 , if Selection fires before text changes, we'll just put our selection change to the back of the queue:

```
private void ComboBoxSelectionChanged(object sender, SelectionChangedEventArgs e)
{
    _comboBox.Dispatcher.InvokeAsync(() => ContentChanged?.Invoke(sender, EventArgs.Empty));
}
```

Seems to work...we have a saying, "bish bash bosh" :)

New version incoming...

**Comment by EdonGashi** [comment]
That's brilliant xD 
Congratulations and thanks

**Comment by stigrune** [comment]
Can confirm that latest prebuild 2.2.0-ci726 is working as expected! Thank you very much :)
