### ISSUE TITLE
Drawerhost/DialogHost overlay dimming is too dark

### ISSUE THREAD

**Issue by maciz84** [ButchersBoy/MaterialDesignInXamlToolkit#544]
It would be great if we are able to adjust the drawerhost and/or dialog hosts background overlay colour as it seems to dark on some monitors.

**Comment by ButchersBoy** [comment]
I'll make it lighter, but not going to make it a property for now as it's in a storyboard via vis state manager.

**Comment by maciz84** [comment]
Thanks James you are a legend

**Comment by StealthRT** [comment]
I'll open this back up again and ask that you **do** add this as a property @ButchersBoy . I would like to be able to change the overlay color and also its opacity. I feel this would be a nice added feature and much needed depending on the users design habits.
