### ISSUE TITLE
MaterialDesignTheme.PasswordBox.xaml

### ISSUE THREAD

**Issue by MysthawkCanada** [ButchersBoy/MaterialDesignInXamlToolkit#547]
Hello,

The "MaterialDesignTheme.PasswordBox.xaml" file appears to be missing the two following lines from the <wpf:SmartHint x:Name="Hint" tag, which were found and copied from the "MaterialDesignTheme.TextBox.xaml" file:

```
FloatingScale="{Binding Path=(wpf:HintAssist.FloatingScale), RelativeSource={RelativeSource TemplatedParent}}"
FloatingOffset="{Binding Path=(wpf:HintAssist.FloatingOffset), RelativeSource={RelativeSource TemplatedParent}}" 
```

I've tested it in my local project and when those lines have been added it allows the Floating scales and floating offset to work for the password boxes.

Thanks,
Michael

**Comment by Keboo** [comment]
This is the same issue as #495
