### ISSUE TITLE
Calendar localization

### ISSUE THREAD

**Issue by andersberglund** [ButchersBoy/MaterialDesignInXamlToolkit#55]
Calendar doesn't localize, shows english names for day and month regardless of culture.

**Comment by andersberglund** [comment]
Great!

**Comment by ButchersBoy** [comment]
fixed.

**Comment by Arnh** [comment]
Hi All.

Me too have this problem.
At design time show correctly in Italian, at run time change in english names.
Cannot manage to solve this issue :)

Another question:
How to show the name of day in top of the control?

Thanks.

Arn

**Comment by ButchersBoy** [comment]
Hey...have you tried setting this? http://stackoverflow.com/questions/4041197/how-to-set-and-change-the-culture-in-wpf

...wondering if that has an effect for you.

**Comment by Arnh** [comment]
Hi James, THANKS for the support ... Don't work :)
Good, because, COPYNG from Your calendar I have made one by myself..

Thanks

Arn

**Comment by ButchersBoy** [comment]
@Arnh ...is there a fix I'm missing then?

**Comment by Arnh** [comment]
Hi James. SORRY for the delay to reply. :)

Surely I do something wrong, but if I put a MaterialDateDisplay on a form it show Italian settings.
After launch show english settings.

If You wtite the exact xaml code to set culture IT i'll try and .. report.

Ciao

Arn

**Comment by andersberglund** [comment]
I found what I think is the easiest way to set the current language for the application.
In MainWindow, before Initialize() use this.
this.Language = XmlLanguage.GetLanguage(CultureInfo.CurrentCulture.IetfLanguageTag);
