### ISSUE TITLE
Top part of Calendar element not need

### ISSUE THREAD

**Issue by Kadosh77** [ButchersBoy/MaterialDesignInXamlToolkit#550]
![itsnotneed](https://cloud.githubusercontent.com/assets/5004274/20167359/b3b71c66-a723-11e6-8c81-27cd28f9bcbe.png)

Greetings to all who love and use MaterialDesignInXamlToolkit for your projects!
Dear designers and programmers, I was faced with such problems, and I can not solve them:
1. Customer requests to the calendar was not informative upper element (as in the picture). Tell me how to clean it up so as not to rewrite the calendar again?
2. I do not understand how on the calendar to show a few dates with one color, and the other another.
3. You should also disable the ability to correct the date (tried `IsEnabled = "False"`, but that's not what I want).
 
I would be grateful for any hint.

**Comment by ButchersBoy** [comment]
This is an edge case and I'm note sure a specific style is warranted within the library itself, unless there is more  popular demand.

The style is here:

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Calendar.xaml#L294

You can take a local copy of the style, rename it, and remove the elements you don't want.

Then create a new version of:

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Calendar.xaml#L607

and apply your new style.  See how the current style is applied on this line:

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Calendar.xaml#L615
