### ISSUE TITLE
ComboBox popup doesn't show full text of selected item.

### ISSUE THREAD

**Issue by jlesp** [ButchersBoy/MaterialDesignInXamlToolkit#551]
When a ComboBox doesn't have enough space to display the full text of the selected item, it is truncated as such:
![closed](https://cloud.githubusercontent.com/assets/20480367/20231624/86dd07f2-a820-11e6-8179-0d050754173f.png)

However, when the ComboBox is opened and the popup is displayed, the selected item text should be displayed in full instead of still being truncated:
![open](https://cloud.githubusercontent.com/assets/20480367/20231649/b66d344c-a820-11e6-9a37-bc7869598a91.png)

**Comment by elvince** [comment]
In fact, the way the template have been done, the selected item that you are seeing is the "current render" of the combobox in your view. It's not part of the list that is rendered in the popup. In fact, in the popup header, there is "hole" so you can see what's under and in this case, It's you combobox.

This design is causing side effect like yours or like my issues: #552

**Comment by ButchersBoy** [comment]
Hi.  Achieving the true look and feel of the Material Design combo, compared to what we see on Android phones, but utilising the WPF ComboBox control, is a pretty tricky task.  There is a mode where it drops below in a more classic sense.  I've wanted to expose this mode as an option for a while, for cases such as yours where display is not working correctly.  So I will try and do this.

Filling in the clipped area is not really an option as delegating keyboard presses becomes a pain in the a$$.

**Comment by jlesp** [comment]
@ButchersBoy I had also noticed that the popup just had a 'window' to the ComboBox behind it. I actually thought this was a clever way to implement the MaterialDesign combo in WPF and avoid any flicker issues, have the fill around, etc.

Thanks!

**Comment by ButchersBoy** [comment]
Well, credit to @l1pton17 for his work on this control.

**Comment by ButchersBoy** [comment]
@l1pton17 in this situation should it not jump into "classic" mode?

**Comment by l1pton17** [comment]
@ButchersBoy it can lead to incomprehension from customers like "why in one sitation i see beatiful wrapper and in another don't?" :smile:

**Comment by ButchersBoy** [comment]
Yes this is a good point.

I think from pure UI design perspective you have to ask yourself if you are going to layout out your combos so you can see the whole field.  Classically, in desktop apps (especially LoB apps) we tend to squash things together, probably a bit like in the above screenshot.  

Personally, I like to give things a lot more white-space.

However, I do think we need to introduce the option to force "classic" mode...then client apps can set a standard look and feel for their whole application.

**Comment by ButchersBoy** [comment]
@jlesp You can now use ``` ComboBoxAssist.ClassicMode ``` for scenarios where your combo is shrunk like this.  This inherits, so you can apply at Window level.
