### ISSUE TITLE
WPF UI Freeze

### ISSUE THREAD

**Issue by swingfox** [ButchersBoy/MaterialDesignInXamlToolkit#556]
Hello!

I've got a bug that I haven't resolved it yet for two months. If I would recreate the situation, at my singleton materialize program I have SystemEvents_SessionSwitch event to detect whether the user is entering to the screen lock/unlock state. When I try to lock my screen and unlock it later. The UI freezes including my system timer that was there. But the only button I could click is the WPF's close button. My program has several threads and socket listeners listening. In this case, if I could try for the second time, my screen lock/unlock action,the SystemEvents_SessionSwitch event is fired but I still the UI freezes. I could no longer use the application after the unlock screen except I'll terminate it using Task Manager and open it again.

What is the cause of this one nasty bug in WPF? I tried to do some StackOverflow searches and Google but they said it is on the WPF UI thread issue. What is the solution for this case? 

Thanks!

**Comment by ButchersBoy** [comment]
Sounds like you have a deadlock involving your UI thread.  It's not a "bug in WPF".  Also, I'm afraid this really isn't the right forum for this; this board is specifically for Material Design bug reports.

**Comment by swingfox** [comment]
Okay, thanks :)
