### ISSUE TITLE
Button text should be capitalized

### ISSUE THREAD

**Issue by mcmullintimothy** [ButchersBoy/MaterialDesignInXamlToolkit#565]
According to the [material design guidelines](https://material.google.com/components/buttons.html#buttons-style), "Button text should be capitalized in languages that have capitalization." However, as far as I can tell, none of the MaterialDesign buttons are styled to change their text to all caps.

Is this intentional or did this part of the design get overlooked?

**Comment by bebenins** [comment]
IMO it's the way it is for flexibility.
Sure, MD calls for all caps but why does it have to be forced?  
All you have to do is capitalize it on your side

**Comment by ButchersBoy** [comment]
Yes, this is intentionally left up the the client code.  If it's forced all that will happen is a bunch of people will ask to turn it off.

**Comment by mcmullintimothy** [comment]
Thanks for the quick responses!

**Comment by cmeeren** [comment]
Is there a way to do this in XAML without hardcoding the actual strings to be all-caps? I've tried `Typography.Capitals="AllPetiteCaps"`, but it doesn't work (at least not for the font this library uses).
