### ISSUE TITLE
DialogHost Close

### ISSUE THREAD

**Issue by krimeshraiyani** [ButchersBoy/MaterialDesignInXamlToolkit#567]
Hi

i want to close dialog box from SaveCommand through but i don't know how can close  dialog box plz help me

my current code 

`<Button IsDefault="True" Style="{DynamicResource MaterialDesignFlatButton}"
                    Command="{Binding SaveCommand}" >   Ok
            </Button>` 

--------------------------------------------------------
 public CityAddControlViewModel()
        {
            _canExecute = true;
        }
        private ICommand _saveCommand;
        public ICommand SaveCommand
        {
            get
            {
                return _saveCommand ?? (_saveCommand = new CommandHandler(() => MyAction(), _canExecute));
            }
        }
        private bool _canExecute;
        public void MyAction()
        {
            //code here
           
        }

**Comment by ButchersBoy** [comment]
Did you check the wiki?

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/Dialogs#close-dialog-strategies

**Comment by krimeshraiyani** [comment]
i check this but i don't understand so plz give me full example

**Comment by ButchersBoy** [comment]
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Domain/DialogsViewModel.cs#L21

**Comment by ButchersBoy** [comment]
Hi, I'm sorry but I really don't have time to post a "full" example, but there are several demos available in the main demo, and in the demos linked to from the main read.me.

I closed this as it's not an issue, but a request for help.  Please join the Gitter chat room for more informal chat/help.

**Comment by krimeshraiyani** [comment]
thanks for help me and issue solved

**Comment by ButchersBoy** [comment]
Cool. Always feel free to drop by the Gitter chat for ad-hoc support.
