### ISSUE TITLE
HeaderedContentControl

### ISSUE THREAD

**Issue by ButchersBoy** [ButchersBoy/MaterialDesignInXamlToolkit#57]

**Comment by JamesIrish** [comment]
Couple of ideas for Tabs below - food for thought :) - apologies for not having the time to contribute to the repo itself.  Cheers, James
http://materializecss.com/tabs.html
http://www.getmdl.io/components/index.html#layout-section/tabs
http://foodtrack.de/

**Comment by ButchersBoy** [comment]
@JamesIrish 

Dragablz already has a material design theme:

https://github.com/ButchersBoy/Dragablz 

You can set it in action  in the MashUp project in the demo app.
