### ISSUE TITLE
Badges Support

### ISSUE THREAD

**Issue by ruslanfedoseenko** [ButchersBoy/MaterialDesignInXamlToolkit#572]
Please implement badges in MaterialDesignInXamlToolkit

**Comment by punker76** [comment]
@ruslanfedoseenko What are budges?

**Comment by ButchersBoy** [comment]
![](https://i.ytimg.com/vi/nkB3cDy-goE/maxresdefault.jpg)

**Comment by punker76** [comment]
Ok, I give up!

**Comment by ButchersBoy** [comment]
https://github.com/google/material-design-lite/issues/708

**Comment by ButchersBoy** [comment]
Badges.  :)

**Comment by punker76** [comment]
:-D

It's already possible with the current available source and Xaml WPF language tools... 🎱

**Comment by ruslanfedoseenko** [comment]
Sorry for my perferct english))
yeap i mean badges.

**Comment by mgnslndh** [comment]
https://www.youtube.com/watch?v=VqomZQMZQCQ

**Comment by ButchersBoy** [comment]
Available in 2.3
