### ISSUE TITLE
Open the Dialog by mvvm binding command from PopupBox or ContextMenu, and CloseDialogCommand can't execute in mvvm 

### ISSUE THREAD

**Issue by helenchixp** [ButchersBoy/MaterialDesignInXamlToolkit#573]
i want to show dialog by mvvm binding command from PopupBox as it:

                <materialDesign:PopupBox DockPanel.Dock="Right" HorizontalAlignment="Right"
                                         VerticalAlignment="Top"
                                         PlacementMode="BottomAndAlignRightEdges" StaysOpen="False"  Focusable="False">

                    <StackPanel Orientation="Vertical"  >
                        <Button Content="Show Dialog " ToolTip="Can't close dialog by left button."
                                            Command="{Binding OpenDialogCommand}" IsTabStop="True" />
                     </StackPanel>
                </materialDesign:PopupBox>

And OpenDialogCommand in ViewModel like it:
        public RelayCommand OpenDialogCommand
        {
            get
            {
                return _openDialogCommand
                    ?? (_openDialogCommand = new RelayCommand(
                    () =>
                    {
                          DialogHost.Show(new DialogView());
                    }));
            }
        }

and a button in shown Dialog call binding CloseDialogCommand like it:

        public RelayCommand CloseDialogCommand
        {
            get
            {
                return _closeDialogCommand
                    ?? (_closeDialogCommand = new RelayCommand(
                    () =>
                    {
                        //i want to add the branch at here.

                        //if (false) return;

                        DialogHost.CloseDialogCommand.Execute(new object(), null);  //??? the second parament is wrong?

                    }));
            }
        }

it can't execute in mvvm command.

if opened dialog is not from popupbox or contextmenu, DialogHost.CloseDialogCommand will be excuted in ViewModel.

and DialogHost.CloseDialogCommand have been excuted in ViewModel when Version V2.2.0.

i can't sure the reason is fixed #445 in MaterialDesignThemes.Wpf/Themes/Generic.xaml
used 
FocusManager.IsFocusScope="True".

How can i CloseDialog in ViewModel?

samples is here.

https://github.com/helenchixp/TabAndTree/tree/master/MaterialTest

Thanks.

**Comment by ButchersBoy** [comment]
Hi,

In MVVM the best way to close a dialog is via it's ``` DialogSession ```.

You can grab the session when you call the ``` .Open ``` method, by providing delegate as one of the parameters.

Example syntax here:

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/Dialogs#dialogsessionclose

**Comment by helenchixp** [comment]
Hi, thanks you answer.
I know use the DialogSession.Close can close a dialog.
but i want to know, In MVVM DialogHost.CloseDialogCommand.Execute can execute by shown dialog from other UIElement,
and can't execute from Popup and ContextMenu.

i think the reason for focus.
if i move the focus by TAB key on button and press the enterkey,
it will be closed the dialog by DialogHost.CloseDialogCommand.Execute in MVVM.
but can't close the dialog by mouse left click.

**Comment by helenchixp** [comment]
sorry , this picture is what i want to question

![closedialog](https://cloud.githubusercontent.com/assets/11284048/21166332/40914f4c-c1e8-11e6-8301-7ae51c0a2480.png)

**Comment by ButchersBoy** [comment]
You need to add ``` IsDefault ``` or ``` IsCancel ``` to your buttons to get proper keyboard  control.  I've created a PR to your demo repo: https://github.com/helenchixp/TabAndTree/pull/1

**Comment by helenchixp** [comment]
thanks you answer.
but i want to know why can't close the dialog by mouse. like this GIF picture (Step 2).
![click](https://cloud.githubusercontent.com/assets/11284048/21209253/cbe7df1a-c2b6-11e6-8635-678484903de1.gif)

it could close the dialog when Version V2.2.0.

**Comment by ButchersBoy** [comment]
Hmmm, thought I tested that yesterday, and it was working OK. But is your sample repo up to date? The version I forked looked a little different. I will try and have another look later today.

**Comment by ButchersBoy** [comment]
Hey...OK...I sent you  a new PR illustrating how to do it.

**Comment by helenchixp** [comment]
Thanks your PR.
and i read you source commit for this:

//CloseDialogCommand is a RoutedCommand.  Which means it has to be executed in XAML, for the DialogHost event to correctly detect it.
//So you have to provide a target in the second parameter...
// DialogHost.CloseDialogCommand.Execute(new object(), null);

but i don't think the reason is the second parameter of RoutedCommand.
it can use the RoutedCommand Execute method when dialog is opened by Button.

and i try to update the MaterialDesignThemes.Wpf/Themes/Generic.xaml like this.
The DialogHost.CloseDialogCommand.Execute(new object(), null) can executed when dialog is opend by Popup and Context.

![generic](https://cloud.githubusercontent.com/assets/11284048/21258024/66721944-c3be-11e6-91f5-af89f182a726.png)

**Comment by ButchersBoy** [comment]
Hey, is this still an issue?  I lost track?

**Comment by helenchixp** [comment]
I try to  i try to update the MaterialDesignThemes.Wpf/Themes/Generic.xaml 
and forked it in my repo. 
https://github.com/helenchixp/MaterialDesignInXamlToolkit
and updated the test project of my repo.
https://github.com/helenchixp/TabAndTree

it can be used DialogHost.CloseDialogCommand.Execute without DialogSession .

open the dialog by the PopMenu or ContextMenu please.  :-)

**Comment by ButchersBoy** [comment]
I've just retested your repo on 2.3.0 (ci)....seems OK now?

**Comment by helenchixp** [comment]
i think it is OK. thanks.
