### ISSUE TITLE
FloatingHint is can't Float in PasswordBox when password is only SPACE

### ISSUE THREAD

**Issue by helenchixp** [ButchersBoy/MaterialDesignInXamlToolkit#574]
The FloatingHint is can't Float in PasswordBox when password is inputted all SPACE.

like this:

![password](https://cloud.githubusercontent.com/assets/11284048/21169746/4f279240-c202-11e6-8cea-cf22e971a80c.png)

**Comment by helenchixp** [comment]
i wish this:
public bool IsEmpty() => string.IsNullOrWhiteSpace(_passwordBox.Password);          
  ↓
public bool IsEmpty() => string.IsNullOrEmpty(_passwordBox.Password);

**Comment by ButchersBoy** [comment]
Wanna raise a PR?  Join the contributors list?  :smile:

**Comment by helenchixp** [comment]
How to join the contributors list? sorry, i don't know.........

**Comment by EdonGashi** [comment]
I think in most MD implementations fields float on focus rather than on input, some optional hint proxies should be considered... the factory container is private though, maybe convert it to <Type,Func> dictionary?
