### ISSUE TITLE
Calendar localization 

### ISSUE THREAD

**Issue by Spyspyspy** [ButchersBoy/MaterialDesignInXamlToolkit#580]
Hello. The calendar shows choosen date in english (like in screen). And months in russian. How can i change this date, that it become only russian or english text?

![321](https://cloud.githubusercontent.com/assets/22395104/21342515/f7c7dd3c-c69a-11e6-9dfc-4d57bf12f06a.JPG)
![123](https://cloud.githubusercontent.com/assets/22395104/21342516/f7c9156c-c69a-11e6-9849-51c9001e1829.JPG)

**Comment by ButchersBoy** [comment]
Something like this:

```
    public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            Thread.CurrentThread.CurrentCulture = new CultureInfo("fr-FR");
            Thread.CurrentThread.CurrentUICulture = new CultureInfo("fr-FR");
            FrameworkElement.LanguageProperty.OverrideMetadata(typeof(FrameworkElement), new FrameworkPropertyMetadata(
                        XmlLanguage.GetLanguage(CultureInfo.CurrentCulture.IetfLanguageTag)));

            base.OnStartup(e);
        }
    }
```

**Comment by Spyspyspy** [comment]
Thank you very much!
