### ISSUE TITLE
Overriding MouseOver ListboxItem style

### ISSUE THREAD

**Issue by omarmallat** [ButchersBoy/MaterialDesignInXamlToolkit#583]
Not sure if I should consider this as issue, but I couldn't override the listboxitem mouseover style. I don't want to have any action to be done when mouse is over. I change the trigger, but I still have it changing the color when mouse is over any item in the listbox.

**Comment by ButchersBoy** [comment]
Hi, this isn't a fault.  Ask on SO under the material-design-in-xaml tag, or in the gitter room.
