### ISSUE TITLE
A hole in ComboBox control popup  part

### ISSUE THREAD

**Issue by BrightShadow** [ButchersBoy/MaterialDesignInXamlToolkit#584]
Problem can be noticed below.
![2017-01-02](https://cloud.githubusercontent.com/assets/3819638/21589603/d7953aa6-d0f3-11e6-9212-ddedfe68f234.png)

**Comment by gregsdennis** [comment]
I've seen this too.  It's also noticeable when the background (behind the combobox) is something different than the popup background.

**Comment by matortheeternal** [comment]
I've been looking into the code to find a workaround for this issue.  I think that setting the [attached property `ShowSelectedItem`](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/bf0d57ffef304ba7b3cf16a5ef7ebcc58a30a250/MaterialDesignThemes.Wpf/ComboBoxAssist.cs#L33-L53) to true should resolve this.  I have not yet figured out how to set the property in my project XAML, but hope to have a solution soon.
