### ISSUE TITLE
[Feature request] Split view for dragablz

### ISSUE THREAD

**Issue by QuantumDeveloper** [ButchersBoy/MaterialDesignInXamlToolkit#59]
Could you also implement split view for dragablz tabs like in VS to see 2 tabs near each other at the same time? 
Could be useful for comparing two documents and in other cases.
As I understand, this will need to create new dragablz control and place it near the first.

Likely this will require creation of the wrapper control around dragablz, I suppose.

**Comment by ButchersBoy** [comment]
...already there....checkout the Layout control.  If you run up the demos you'll see some of them are using it.

**Comment by QuantumDeveloper** [comment]
Sorry, didnt see it. Could you point me where exactly I can find it in the demo??

**Comment by ButchersBoy** [comment]
No problem. Two windows in the demo (the demo in the **main** source project) illustrate it:

![image](https://cloud.githubusercontent.com/assets/658107/9830202/0d29b5de-591d-11e5-9317-c177322b3a24.png)

![image](https://cloud.githubusercontent.com/assets/658107/9830203/110fa1d6-591d-11e5-9520-1612cc688778.png)

Have a look in BoundExampleWindow.xaml, it uses a LayoutControl, with two import parts:

The content is a TabablzControl, but you also have to provide BranchTemplate so it can render the second TababzControl.

**Comment by QuantumDeveloper** [comment]
Aha. Sorry, I didnt look at Dragablz demo (thought in material design demo present all parts). So, this is cool that it already present. Seems only side panels left to be implemented and (maybe some tab stuff like close/pin/hide buttons for each tab)

**Comment by ButchersBoy** [comment]
Yeah...there's already an issue raised for side panels. You can actually set the FixedHeaderCount to pin tabs (but you'd have to provide your own style with the pin it right now).

**Comment by QuantumDeveloper** [comment]
I am looking forward for new upgraded gragablz to start using it for my needs (game editor main control). Hope that you will find some time to implement pin/unpin(for main tabs) and hide/show (for side panels). Your projects are amazing!
