### ISSUE TITLE
How Can I save the Palette Color  for individual UserSetting ?

### ISSUE THREAD

**Issue by sar2436** [ButchersBoy/MaterialDesignInXamlToolkit#591]
# PLEASE READ BEFORE POSTING AN ISSUE

# This is a place for issues.  Questions are better asked in the Gitter chat room.

# Seriously consider creating and linking to a test repo which takes absolutely minimal setup to illustrate how reproduce the problem. 

My time is limited and .Zip files, code snippets and partial examples are often a time sink.  GitHub also provides great communication and code review tools which can be utilised.

# HOW TO POST A GOOD SAMPLE.  Follow these guidelines and I will most likely look at the issue sooner:

* Post a full GitHub repository. Not a zip file, half baked snippet etc.  If GitHub is new to you consider it a great learning opportunity and chance to get involved.
* The repository should have just ONE step max for me to get running, and that is "Restore NuGet Packages".  If there are any other missing dependencies, or uncompiling features I will most likely move on to another issue.
* I'm not trying to be awkward.  I'm just busy and I'm helping a lot of people, not just you, so help me out and I will help you out.

**Comment by sar2436** [comment]
How Can I Save The Palette Color for Individual UserSetting ?

**Comment by neomaximus2k** [comment]
I stored the primary and secondary/accent colours as a string in the settings for the app. then I called SetPrimary() while getting the swatch.

**Comment by ButchersBoy** [comment]
Hi, this is a question, quite a generic one, and not an issue, so closing.  If you want to chat please stop by the gitter room.
