### ISSUE TITLE
How to set an button VerticalAlignment=Stretch?

### ISSUE THREAD

**Issue by wrjcs** [ButchersBoy/MaterialDesignInXamlToolkit#592]
Hello,
In my xaml code I have put VerticalAlignment=Stretch, but I can't get the stretch result but center?
So anyone could tell me how to resolve it?

Thanks.

**Comment by ButchersBoy** [comment]
Stretch the button or the content?  What's your XAML?

**Comment by wrjcs** [comment]
<Button VerticalAlignment="Stretch" Grid.Row="1" />
![image](https://cloud.githubusercontent.com/assets/7202194/22029429/d3b8581c-dcda-11e6-8247-dce9f3a1f9bf.png)

**Comment by wrjcs** [comment]
<Button VerticalAlignment="Stretch" Grid.Row="1" />

**Comment by ButchersBoy** [comment]
Hi, The Height is defined in the style to a standard size.  So you can unset it like this:

```
<Button VerticalAlignment="Stretch" Height="{x:Static system:Double.NaN}">
    Hello World
</Button>
```
