### ISSUE TITLE
Issues With Demo 

### ISSUE THREAD

**Issue by BoxerBuzz559** [ButchersBoy/MaterialDesignInXamlToolkit#593]
Why are all demo and examples always done in C#, Even when i try to rewrite the codes in vb.net the codes don't always work as they should.
For example when i tried rewriting the Textbox error validation, it didn't work so fine even when i input a wrong text or leave the textbox blank or even with text it still show red and tells me field can not be left blank

**Comment by ButchersBoy** [comment]
Hi, 

Unfortunately I don't have capacity to write examples in VB.Net, I have to go with the most popular language.

However, validation is a standard WPF feature, this lib provides style.  So this most likely a fault with your setup.  I suggest you ask in the gitter room or raise a SO question using the material-design-in-xaml tag.

**Comment by BoxerBuzz559** [comment]
Thanks a lot ButchersBoy I really appreciate... Am new to the framework and
I so much love it... Thanks once more for materialDesignInXaml
