### ISSUE TITLE
NuGet installation error for UWP/Grid(8.1) application 

### ISSUE THREAD

**Issue by manumohant** [ButchersBoy/MaterialDesignInXamlToolkit#594]
Hi,
Please see below error that i get while trying to install through NuGet

> Error Could not install package 'Material Design Colors 1.1.2'. You are trying to install this package into a project that targets 'Windows,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author. 0

I am using Visual studio 2015 in Windows 10 OS. Should I run Visual studio updates to resolve this?

**Comment by ButchersBoy** [comment]
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/163
