### ISSUE TITLE
How could I drag the item of listview or listbox ro rearange

### ISSUE THREAD

**Issue by wrjcs** [ButchersBoy/MaterialDesignInXamlToolkit#595]
Hello,
Could I drag an item in listview or listbox to rearange the list?

Thanks.

**Comment by ButchersBoy** [comment]
https://github.com/MaterialDesignInXAML/MotionList

or

https://github.com/punker76/gong-wpf-dragdrop

**Please note** this is an _issues_ list.  If you want to chat or ask questions the Gitter chatroom or SO are better places.

**Comment by wrjcs** [comment]
what is your id in gitter charroom?

**Comment by ButchersBoy** [comment]
https://gitter.im/ButchersBoy/MaterialDesignInXamlToolkit
