### ISSUE TITLE
Issue with MaterialDesignThemes.Mahapps 0.0.9

### ISSUE THREAD

**Issue by bbougot** [ButchersBoy/MaterialDesignInXamlToolkit#597]
Using MahApps 1.4.1.0, an exception is thrown at app launch with this message : 

`Set property 'System.Windows.ResourceDictionary.DeferrableContent' threw an exception.`

Seems to be thrown by MaterialDesignTheme.MahApps.Defaults.xaml

**Comment by Insire** [comment]
I'm having the same problem, For me the problem is 

`<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.MahApps;component/Themes/MaterialDesignTheme.MahApps.Flyout.xaml" />`

Removing that from my App.xaml lets my app start as usual

**Comment by punker76** [comment]
@bbougot @Insire Can one of you create a repo sample? Would be really useful. thx

**Comment by Insire** [comment]
https://github.com/Insire/InsireBot-V2 you can see the problem here

**Comment by Insire** [comment]
check my App.xaml Line 32 and uncomment that line and the error is back

**Comment by SProst** [comment]
Having this same issue.

**Comment by mgnslndh** [comment]
When I look into the MaterialDesignThemes.MahApps assembly with dotPeek there is no type for `FlyoutAssist`, which exist in source code. 

It seems like the 0.0.9 package includes the 0.0.1 assembly:

![image](https://cloud.githubusercontent.com/assets/1139118/22509398/3721d9b4-e88e-11e6-8d6f-90e28081b9b0.png)

Should be verifiable by downloading the nuget package at https://www.nuget.org/packages/MaterialDesignThemes.MahApps/

**Comment by ButchersBoy** [comment]
Sorry guys...will try to look at this v. soon.

**Comment by ButchersBoy** [comment]
OK, please retry with https://www.nuget.org/packages/MaterialDesignThemes.MahApps/0.0.10

**Comment by Insire** [comment]
Most recent version works for me. Thanks for your work!

**Comment by langebo** [comment]
I am just experiencing the exact same error. Appeared using 0.0.11, tried 0.0.10 but still have the same issue.

**Comment by yokrysty** [comment]
I experience the same problem in this latest release 0.0.11 :(

**Comment by STDGA** [comment]
The issue is because of the paket.lock file,
please check this:
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/659
