### ISSUE TITLE
DataGridCheckboxColumn not styled properly

### ISSUE THREAD

**Issue by MrMitch** [ButchersBoy/MaterialDesignInXamlToolkit#599]
Manually generated `DataGridCheckboxColumn` are not properly styled, the theme applied to the checkbox is the native WPF style.

You can clone an example repository : https://github.com/MrMitch/DataGridCheckboxColumn-Issue
```bash
git clone https://github.com/MrMitch/DataGridCheckboxColumn-Issue.git
```

Here is a minimal extract with the visual result. Please let me know if I can help in any way.

```xaml
<DataGrid x:Name="DataGrid1"
            Grid.Row="1" Grid.Column="0"
            AutoGenerateColumns="False">
    <DataGrid.Columns>
        <DataGridCheckBoxColumn Binding="{Binding Item1, Mode=OneWay}" Header="bool" />
        <DataGridTextColumn Binding="{Binding Item2}" Header="string" />
    </DataGrid.Columns>
</DataGrid>
```
![image](https://cloud.githubusercontent.com/assets/576772/22185006/3f703948-e0dd-11e6-8d14-50fdb9b20a4c.png)

**Comment by MrMitch** [comment]
It seems adding `MaterialDesignCheckBox` as the `ElementStyle` and the `EditingElementStyle`, solves this.

```xaml
<DataGridCheckBoxColumn Binding="{Binding Item1}"
    Header="bool"
    ElementStyle="{StaticResource MaterialDesignCheckBox}"
    EditingElementStyle="{StaticResource MaterialDesignCheckBox}" />
```

Still, it would be nice if the manually generated columns were properly styled. If there's no way around this, I'll close the issue if this solution seems acceptable to @ButchersBoy.

**Comment by ButchersBoy** [comment]
It's not easily achievable; thus the demo has always illustrated that for manual columns you must explicitly set the style.

**Comment by MrMitch** [comment]
that's what i thought upon further investigation, thanks for the feedback !
