### ISSUE TITLE
Date pickers

### ISSUE THREAD

**Issue by ButchersBoy** [ButchersBoy/MaterialDesignInXamlToolkit#6]
Looks like a fun one!

http://www.google.com/design/spec/components/pickers.html

**Comment by brunobelarmino** [comment]
:+1:

**Comment by quicoli** [comment]
Hello ButchersBoy!

I'd like to collaborate with this project. For so, I'd like to know your planning. For example, that  picker, are you implementing right now?

thank you

**Comment by ButchersBoy** [comment]
Hi...planning on starting on date pickers next week. I wanna be careful to keep separation between the control and any potential need for a dialog. Would you like to have a go at the menus or scrollbars to get started?

**Comment by ButchersBoy** [comment]
FYI templates for primitive DatePicker/Calendar controls checked in.  Will start on brand new TimePicker controls in a couple of days.

**Comment by ButchersBoy** [comment]
Done time!  Two new controls: TimePicker & Clock.  See demos, and enjoy!
