### ISSUE TITLE
Dialog buttons get disabled when clicking inside dialog

### ISSUE THREAD

**Issue by chrischu** [ButchersBoy/MaterialDesignInXamlToolkit#602]
I am currently having a problem with the dialog system. I can even reproduce it in your example application (see screenshots).

Thats the initial state when opening the dialog:
![image](https://cloud.githubusercontent.com/assets/447251/22309561/0d2a68e8-e34c-11e6-99cd-563405bd63b5.png)

However when I click somewhere other than the TextBox (e.g. on the "Add a new fruit" text) both buttons seem to get disabled and I cannot figure out a way to enable them again:
![image](https://cloud.githubusercontent.com/assets/447251/22309604/38993ce8-e34c-11e6-9d63-2d50e0dfcd98.png)

**Comment by chrischu** [comment]
Any update on this?

**Comment by EdonGashi** [comment]
Seems to be a focus issue. I can get the buttons enabled again by tabbing around or when opening another dialog...

The routedcommand is disabling the button, so an option is to opt out of using the default commands and implement your own event handler or some command to manually close your dialog by reference. That's most likely one or two lines of code so it won't be very problematic: `MyDialogHost.IsOpen = false;`

**Comment by chrischu** [comment]
Yay, thanks a lot!

**Comment by ButchersBoy** [comment]
You can get the latest CI/-pre build from nuget,

**Comment by chrischu** [comment]
Oh wow, it took me a while to realize that the newer version are not actually listed as newer by NuGet. You might want to consider changing your versioning scheme to make sure the chronologically newest version is actually regarded as newest version by NuGet to enable users to check for updates via NuGet :).
