### ISSUE TITLE
Drawers aren't completely hidden

### ISSUE THREAD

**Issue by AndreasFurster** [ButchersBoy/MaterialDesignInXamlToolkit#603]
When you click (or drag) at the most left side of a window with an drawer, you can still click inside the drawer. 

An image to illustrate the problem:
![](https://i.gyazo.com/c142346640119f0c3619535d5870515f.gif)

As a workaround I added an right margin of 1 to my Dockpanel inside the DrawerHost.

**Comment by andybond006** [comment]
I just checked and this occurs in an application that I have made using a drawer for navigation as well.
The workaround of a right-margin = 1 also worked for me.

Good catch!

**Comment by ButchersBoy** [comment]
ha, cool bug :)

**Comment by AndreasFurster** [comment]
:) The dragging comes actually pretty in handy when you need to quick peek on pages. I use it all the time when I search a control in the demo application. 

<img src="http://i.qkme.me/3u7fdu.jpg" width="400">

**Comment by AmitBhatnagar24** [comment]
Another bug: try setting a FloatingActionPopupBox button's Visibility to collapsed/hidden. When the mouse moves over it, the items within it "pop up"..
