### ISSUE TITLE
DatePicker - Blackout Dates Not Keeping Opacity When Switching Months

### ISSUE THREAD

**Issue by andybond006** [ButchersBoy/MaterialDesignInXamlToolkit#605]
## Explanation of Issue

I am working with a list of dates that the user will have the ability to select from. I want to black out the dates that have not occurred yet (if date > today, black it out). After blacking out all of the dates that should not be selectable, and setting a DisplayDateStart and DisplayDateEnd, the DatePicker looks correct at first glance.

However, if the user scrolls through the months available, some of the blacked out dates will suddenly appear to be selectable (even though they are not).

## How to Reproduce

Visual Glitch Repository: [Here](https://github.com/andybond006/MaterialDesign-BlackOutDatesError)

- Download and Open
- Run Application
- Open the DatePicker Calendar Menu
- Go to January (left arrow) (dates appear correct)
- Go to February (right arrow) (dates probably changed opacity)
- Go back to January (left arrow) (dates probably changed opacity)
- You should notice that some dates that were "blacked out" (lowered opacity), now have their opacity set to 100% again. The "unable to select" cursor still appears however (as it should).

It seems some dates are more likely to switch opacity than others. In my data, I notice that the first 6 days of the month and the last few days of the month are more likely to switch opacity

## Screenshots

On First Pass through Months (these dates appear correctly):

![first_pass_1](https://cloud.githubusercontent.com/assets/10934345/22555387/89392934-e931-11e6-99c9-5d8d674c0e13.png)

On Second Pass through Months (the dates now do not appear correctly, the last 5 days should be greyed out):

![second_pass_1](https://cloud.githubusercontent.com/assets/10934345/22555395/9354de0e-e931-11e6-8a0a-3409f87246e0.png)

**Comment by jdf3** [comment]
Thanks for the detailed steps.

I downloaded and built the case you supplied and followed your steps, and I wasn't able to reproduce the bug. Is this still an issue? I'd be happy to look into it if it is.

**Comment by andybond006** [comment]
@jdf3 Yes, this issue is still occurring for me when I perform those steps exactly. I will see if I can record my screen or something tomorrow to demonstrate it better. Not sure why it would affect me but not you.

Has anyone else been able to test this? I noticed you thumbs it up @mgnslndh , did you happen to give this a shot?

**Comment by Keboo** [comment]
I can confirm that I am also seeing the issue with your repo (haven't had time to look into what it causing it though). Specifically Feb 1-6 show up for me as the problem dates.
