### ISSUE TITLE
Icon Pack 

### ISSUE THREAD

**Issue by BoxerBuzz559** [ButchersBoy/MaterialDesignInXamlToolkit#606]
**# Please I need Help with this** 
Each time i make use of the pack Icon it does not show fully E.g the icon shows in half....i make use of VB.Net In Windows Presentation Foundation

**Comment by ButchersBoy** [comment]
Sample repo isolating issue please.

**Comment by BoxerBuzz559** [comment]
Please Elaborate a bit

**Comment by ButchersBoy** [comment]
I'm asking YOU to elaborate a bit.  You have provided no sample code/XAML or project which replicates the issue.

**Comment by BoxerBuzz559** [comment]
<Controls:MetroWindow  x:Class="MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
         xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
        xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
        xmlns:local="clr-namespace:Trail"
        mc:Ignorable="d"
        Title="" Height="350" Width="525" Activated="MetroWindow_Activated" Loaded="MetroWindow_Loaded">
    <Controls:MetroWindow.RightWindowCommands>
        <Controls:WindowCommands>
        </Controls:WindowCommands>
    </Controls:MetroWindow.RightWindowCommands>
    <Grid Height="319" VerticalAlignment="Bottom">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" MinHeight="52"/>
            <RowDefinition Height="Auto" MinHeight="115"/>
        </Grid.RowDefinitions>
        <materialDesign:ColorZone Mode="PrimaryMid" Padding="16">
            <DockPanel>
                <ToggleButton Style="{StaticResource MaterialDesignSwitchAccentToggleButton}" VerticalAlignment="Center"
                                  DockPanel.Dock="Right" />
                <StackPanel Orientation="Horizontal"
                            materialDesign:RippleAssist.IsCentered="True">
                    <materialDesign:ColorZone Mode="Standard" Padding="8 4 8 4" CornerRadius="2" Panel.ZIndex="1"
                                   Margin="16 0 0 0"
                                   materialDesign:ShadowAssist.ShadowDepth="Depth1">
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition Width="*" />
                                <ColumnDefinition Width="Auto" />
                            </Grid.ColumnDefinitions>
                            <Button Style="{DynamicResource MaterialDesignToolButton}">
                                <materialDesign:PackIcon Kind="AccountBox" />
                            </Button>
                            <TextBox Grid.Column="1" Margin="8 0 0 0" materialDesign:HintAssist.Hint="Build a search bar" 
                                     materialDesign:TextFieldAssist.DecorationVisibility="Hidden" BorderThickness="0"
                                     MinWidth="200" VerticalAlignment="Center" />
                            <Button Style="{DynamicResource MaterialDesignToolButton}" Grid.Column="2">
                                <materialDesign:PackIcon Kind="Facebook"  />
                            </Button>
                        </Grid>
                    </materialDesign:ColorZone>
                    <Button Style="{DynamicResource MaterialDesignToolForegroundButton}" Margin="8 0 0 0" Panel.ZIndex="0" Width="30" VerticalContentAlignment="Center" >
                        <materialDesign:PackIcon Kind="Android"  />
                    </Button>
                    <Button Style="{DynamicResource MaterialDesignToolForegroundButton}" 
                             
                            Margin="8 0 0 0" Panel.ZIndex="0" Width="30" VerticalContentAlignment="Center"
                            IsEnabled="True">
                      <materialDesign:PackIcon Kind="Action"/>
                    </Button>

                </StackPanel>
            </DockPanel>
        </materialDesign:ColorZone>
        <Grid   Grid.Row="1" VerticalAlignment="Stretch" HorizontalAlignment="Stretch" Margin="0,0,0,-130" >
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="Auto" MinWidth="150"/>
                <ColumnDefinition Width="Auto" MinWidth="232"/>
            </Grid.ColumnDefinitions>
            <TreeView x:Name="TreeViewContent1"
                  MinWidth="120" Padding="10,10,10,10">
                <TreeViewItem Header="Books" x:Name="ItmBooks" Width="110"/>
                <TreeViewItem Header="PDF" x:Name="ItmPDF" Width="110" Height="32" />
                <TreeViewItem Header="MP3" x:Name="ItmMP3" Width="110" Height="32"/>
                <TreeViewItem Header="MP4" x:Name="ItmMP4" Width="118"/>
                <TreeViewItem Header="Archive" x:Name="ItmArchive" Width="110" Height="32"/>
            </TreeView>
        </Grid>
    </Grid>
</Controls:MetroWindow >

**Comment by BoxerBuzz559** [comment]
that's my sample code i dont know why the icon keep cutting in half ............

**Comment by ButchersBoy** [comment]
Is this even valid XAML?

</Controls:MetroWindow.RightWindowCommands>
<Grid.RowDefinitions>

How could those lines be adjacent?

**Comment by BoxerBuzz559** [comment]
i probably omitted some text as i copied them

**Comment by Codeusa** [comment]
When filing a new bug, please include:

- Descriptive title - use keywords so others can find your bug (avoiding duplicates)
- Steps to trigger the problem that are specific, and repeatable
- What happens when you follow the steps, and what you expected to happen instead.
- Include the exact text of any error messages if applicable (or upload screenshots).

**Comment by BoxerBuzz559** [comment]
![capture](https://cloud.githubusercontent.com/assets/25007742/22622952/80069d7c-eb4a-11e6-86c7-5a240dbb7b5e.PNG)

**Comment by BoxerBuzz559** [comment]
if you observe the dropdown an the tree view they are hidden

**Comment by BoxerBuzz559** [comment]
![capture1](https://cloud.githubusercontent.com/assets/25007742/22622967/cdfefdf8-eb4a-11e6-8081-0aa0c0ec2416.PNG)
 

on the other hand thats what they should look like

**Comment by ButchersBoy** [comment]
Hi, if you can provide a sample repository on GitHub illustrating the issue the please re-open.
