### ISSUE TITLE
SnackbarMessageQueue Bug?

### ISSUE THREAD

**Issue by devriesb13** [ButchersBoy/MaterialDesignInXamlToolkit#614]
Hi There,

I may of found a bug in the SnackbarMessageQueue class. Can you please confirm if this is correct?

Cheers

![2017-02-09_15-43-54](https://cloud.githubusercontent.com/assets/10214916/22769847/a3bbefc2-eedf-11e6-93a8-baec0e74e591.png)

**Comment by ButchersBoy** [comment]
Let's call it a "pending feature with reserved API contract" :)
