### ISSUE TITLE
Remove MaterialDesignColors from dependencies of MaterialDesignThemes

### ISSUE THREAD

**Issue by Tyrrrz** [ButchersBoy/MaterialDesignInXamlToolkit#619]
As far as I can tell, MaterialDesignColors is not needed as long as you define the brush resources by yourself, but MaterialDesignThemes insists that it depends on it. Since I always use my own colors, I just end up manually removing it from references/packages.config but it re-adds itself after every update and is generally a little bit annoying. I think it would make more sense if the dependency was inversed - so that MaterialDesignColors needed MaterialDesignThemes instead.

**Comment by ButchersBoy** [comment]
There is absolutely no need to inverse the reference: __'Colors__ has no dependency on __'Themes__.

_However_; __'Themes__ _does_ depend on __'Colors__.  ``` PaletteHelper ``` from __'Themes__ uses ``` SwatchesProvider ``` from __'Colors__.

Also, the majority of users draw from standard palettes and severing the link would add an extra step in the intial setup which new users/applications have to go through.  I don't want to complicate that which is currently a pretty easy process.

For these reasons this request wont happen.

As you have a more advanced use case then maybe you should just consider amending your build/CI/deploy process so the __'Colors__ assembly does not make it your end output without you having to delete it manually when you upgrade.

**Comment by Tyrrrz** [comment]
I see. I didn't know about `PaletteHelper`. 

> As you have a more advanced use case then maybe you should just consider amending your build/CI/deploy process so the 'Colors assembly does not make it your end output without you having to delete it manually when you upgrade.

I'm already doing that, but I was wondering if the solution could be globalized :)
