### ISSUE TITLE
TimePicker AM/PM hide

### ISSUE THREAD

**Issue by victormx** [ButchersBoy/MaterialDesignInXamlToolkit#62]
Is there any way to hide the AM/PM radios from timepicker? Thank you for your hard work.

**Comment by ButchersBoy** [comment]
...stretch goal is to make a full 24 hour mode, got a few other things in the queue first though.

**Comment by ButchersBoy** [comment]
@quicoli is currently playing around with getting a 24hr version working

**Comment by NihatO** [comment]
Is there any progress with the 24hr version?
If not it would be great if you could share your work in progress so maybe i can support with the left issues.

**Comment by quicoli** [comment]
Hi,

24h timepicker is done. James said it will be released on 1.1 version

Thanks

Enviado pelo meu Windows Phone 

-----Mensagem Original-----
De: "NihatO" <notifications@github.com>
Enviada em: ‎11/‎10/‎2015 19:25
Para: "ButchersBoy/MaterialDesignInXamlToolkit" <MaterialDesignInXamlToolkit@noreply.github.com>
Cc: "Paulo Roberto Quicoli" <pauloquicoli@gmail.com>
Assunto: Re: [MaterialDesignInXamlToolkit] TimePicker AM/PM hide (#62)

Is there any progress with the 24hr version?
If not it would be great if you could share your work in progress so maybe i can support with the left issues.

**Comment by ButchersBoy** [comment]
1.2

**Comment by ButchersBoy** [comment]
@quicoli ...can you fix the merge conflicts on your branch?  then I will try and pull in this week.

**Comment by quicoli** [comment]
Ok, I gonna try

Enviado pelo meu Windows Phone 

-----Mensagem Original-----
De: "James Willock" <notifications@github.com>
Enviada em: ‎12/‎10/‎2015 04:54
Para: "ButchersBoy/MaterialDesignInXamlToolkit" <MaterialDesignInXamlToolkit@noreply.github.com>
Cc: "Paulo Roberto Quicoli" <pauloquicoli@gmail.com>
Assunto: Re: [MaterialDesignInXamlToolkit] TimePicker AM/PM hide (#62)

@quicoli ...can you fix the merge conflicts on your branch? then I will try and pull in this week.
