### ISSUE TITLE
Multiple textboxes with validation

### ISSUE THREAD

**Issue by Paley01** [ButchersBoy/MaterialDesignInXamlToolkit#620]
If I have more than one TextBox with validation on a window the red validation line only appears on every 2nd TextBox if it has focus - if no focus it disappears.

**Comment by ButchersBoy** [comment]
You'll have to post a sample repo.

**Comment by Paley01** [comment]
I have no idea how to do that. Only joined Git today.

**Comment by ButchersBoy** [comment]
Time to up-skill yourself then :)

**Comment by Paley01** [comment]
Fixed it - having FontFamily="{DynamicResource MaterialDesignFont}" in the window properties causes it - removing it fixes it. Very odd
