### ISSUE TITLE
ComboBoxPopup can cause memory leak

### ISSUE THREAD

**Issue by spdjudd** [ButchersBoy/MaterialDesignInXamlToolkit#622]
Hi James,

Firstly, thanks very much for MDXT (and Dragablz) - they're great projects and much appreciated.

The issue I'm seeing is that using a ComboBox causes a memory leak, as the ComboBoxPopup constructor calls AddValueChanged() on a dependency property and never calls RemoveValueChanged().  In my case this prevents views and datatemplates that have comboboxes being collected. 

I've posted a test repo here: https://github.com/spdjudd/MdxtComboBoxLeak along with instructions - the app is trivial but to see the leak and the GC roots needs a few windbag steps.

I've also forked and made a change to ComboBoxPopup.cs that fixes the issue here: https://github.com/spdjudd/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/ComboBoxPopup.cs

Happy to submit a pull request if you'd like,

Simon.

**Comment by ButchersBoy** [comment]
Hi,

Yes, please submit a PR and I will review.

James

**Comment by spdjudd** [comment]
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/pull/624 submitted

**Comment by hinduCoder** [comment]
Still causes a memory leak.
![image](https://user-images.githubusercontent.com/5616901/49457748-6f8b0080-f7fc-11e8-96d1-e200cacc2d01.png)
![image](https://user-images.githubusercontent.com/5616901/49457776-79acff00-f7fc-11e8-82d9-766c1fdddd4a.png)
![image](https://user-images.githubusercontent.com/5616901/49457813-90535600-f7fc-11e8-9099-17110846f30d.png)
