### ISSUE TITLE
make data grid cell padding and data grid HeaderColumn padding configurable

### ISSUE THREAD

**Issue by Arnh** [ButchersBoy/MaterialDesignInXamlToolkit#63]
Hi All.

**Comment by ButchersBoy** [comment]
There are now two new attached properties you can use:

```
<DataGrid wpf:DataGridAssist.CellPadding="4 2 2 2" wpf:DataGridAssist.ColumnHeaderPadding="4 2 2 2" />
```

You can see this in action in the demo:

![image](https://cloud.githubusercontent.com/assets/658107/10029400/956d00f0-6169-11e5-9a94-eed287850541.png)

**Comment by Arnh** [comment]
Hi.

Thanks James :+1:  I'll wait the release ...

Thanks again.

arn

**Comment by Arnh** [comment]
Hi All.

James has updated the Nugets packages, ALL works fine.

Thanks to Him for the work done.

Arn

**Comment by ButchersBoy** [comment]
good good
