### ISSUE TITLE
Flipper is missing from the current NuGet package

### ISSUE THREAD

**Issue by fjames** [ButchersBoy/MaterialDesignInXamlToolkit#637]
I installed from the NuGet package MaterialDesignColors (1.1.3) and MaterialDesignThemes (2.2.1.750).  Tried using Flipper.  This is the error I get:

Exception: An error occurred while finding the resource dictionary "pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Flipper.xaml".

Oddly enough the Demo works

**Comment by ButchersBoy** [comment]
Hi,

The demo is always the very latest "dev". The control is still in beta, so you need to install the latest pre-release from nuget.
