### ISSUE TITLE
Underline color change

### ISSUE THREAD

**Issue by andrewpros** [ButchersBoy/MaterialDesignInXamlToolkit#640]
Hi.

Can somebody help me with changing underline color to accent in textbox based controls and combobox?

I have added and merged

` <Style TargetType="{x:Type material:Underline}" >
        <Setter Property="Background" Value="{DynamicResource SecondaryAccentBrush}"/>
    </Style>`

This works then focusing, but in half, the default thin state on mouse over has still primary color, if it can't be done i can live with it, combobox on the other hand seems not working, it animates with primary color but getting out of focus changes the color to accent, so it almost works.

Any advice?

**Comment by Keboo** [comment]
Hi @andrewpros 
As you pointed out there are actually two separate "underlines" on the text box. The underline control is the one that animates in and out when the text box has keyboard focus. To change the color of that underline the style you have should work fine. 
The other underline is controlled with the TextBox's BorderBrush/BorderThickness properties. By default the thickness is set to 0,0,0,1. The change in color when the mouse hover's over it is done with a style trigger on the IsMouseOver. So to control it you have a couple options.
If you want it to be a constant brush regardless of the mouse state, you can simply set the BorderBrush on the TextBox directly. If you want to set it via a style, or have a separate color when the mouse is over it, you can simply override the trigger in your own style. Something like this:

```xml
<Style TargetType="TextBox" BasedOn="{StaticResource MaterialDesignTextBox}">
    <Setter Property="BorderBrush" Value="Fuchsia" />
    <Style.Triggers>
        <Trigger Property="IsMouseOver" Value="true">
            <Setter Property="BorderBrush" Value="GreenYellow"/>
        </Trigger>
    </Style.Triggers>
</Style>
```

**Comment by andrewpros** [comment]
@Keboo 

Thx for the answer, it helped, the code you provided work for textboxes.

Sadly, combobox still wont work in current release version, upon further investigation, the underline is set here https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/bf0d57ffef304ba7b3cf16a5ef7ebcc58a30a250/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml#L550 by its name, so the only way to change it is to make own copy of template.

This will not work in current release cuz ComboBoxPopup is set internal in 2.2.1, in master it is public, so...

For now i just installed the latest prerelease 2.3.0 nuget and done a MaterialDesignFloatingHintComboBoxTemplate copy, this is working.

Thank you again.

**Comment by Keboo** [comment]
Glad you got it working. 

I assume this issue can be closed now since it is fixed in the latest release?

**Comment by andrewpros** [comment]
Yeah
