### ISSUE TITLE
Shadow doesn't seem to be dropping on top of cards

### ISSUE THREAD

**Issue by Tyrrrz** [ButchersBoy/MaterialDesignInXamlToolkit#647]
Here's the setup. The toolbar (top part of the window) is a `ColorZone` and has `ShadowAssist.Depth = Depth2`. Looks fine and the shadow is correctly dropped on the scrollviewer's content.

![2017-03-04 19_40_39-youtubeexplode demo](https://cloud.githubusercontent.com/assets/1935960/23580875/cc9e4d3c-0112-11e7-8a61-ec949295febe.png)

Now if you scroll down a bit, the shadow doesn't drop on top of the underlying card.

![2017-03-04 19_40_48-youtubeexplode demo](https://cloud.githubusercontent.com/assets/1935960/23580892/2290fb86-0113-11e7-9f50-a12d23c168c9.png)

I feel like I might be missing something, but not sure what exactly is wrong.

The window's XAML: https://github.com/Tyrrrz/YoutubeExplode/blob/master/YoutubeExplodeDemoWpf/Views/MainWindow.xaml#L38

Tell me if you need a bare-bones example set up.

**Comment by Keboo** [comment]
Hi @Tyrrrz 
I suspect the problem has to do with the ZOrder of the items. The default values are inferred based on the order in the XAML. 
Try putting `Panel.ZOrder="1"` on the Toolbar ColorZone and `Panel.ZOrder="0"` on the Video info ScrollViewer and see if that resolves the issue. Alternatively you could reorder those items in the XAML.

**Comment by Tyrrrz** [comment]
@Keboo 
Thanks a lot, that did the trick. I never had to deal with layering in XAML, so I didn't know about that. 
Also the property name is `Panel.ZIndex`.

**Comment by Keboo** [comment]
Ah yes, sorry about that. Glad it worked.
