### ISSUE TITLE
'DialogHost is already open' when opening a Dialog with the drawer open

### ISSUE THREAD

**Issue by TheJuniorAde** [ButchersBoy/MaterialDesignInXamlToolkit#653]
I have been trying to solve an annoying problem:
I have a control that opens a Dialog whenever you click on the Drawer menu item. The problem is: the 'DialogHost is already open' error keeps popping. If I open the control programmatically it works, but when i click the item in the Drawer it triggers this error.
Haven't been able to solve it, please help D:

**Comment by ngodugu** [comment]
did you find a solution to this?

**Comment by TheJuniorAde** [comment]
@ngodugu i had to use the following lines to counter the problem:
`DialogHost.CloseDialogCommand.Execute(new object(), null);`
Then I run this whenever the OnPreviewMouseLeftButtonUp event is fired on the drawer items
