### ISSUE TITLE
Datagrid SelectionMode Single

### ISSUE THREAD

**Issue by SeaBear622** [ButchersBoy/MaterialDesignInXamlToolkit#654]
Datagrid SelectionMode Single selects entire row

**Comment by Keboo** [comment]
@SeaBear622 SelectionMode Single only controls the number of items that can be selected in the DataGrid, not whether it selects the entire row.
If you want to change whether it selects the individual cell or the entire row set the SelectionUnit to Cell or FullRow.

**Comment by SeaBear622** [comment]
That makes total sense, thank you for the information.
