### ISSUE TITLE
PopupEx Stay active when close

### ISSUE THREAD

**Issue by elvince** [ButchersBoy/MaterialDesignInXamlToolkit#658]
Hi,

Following my request #655 I saw that there is an issue with the PopupEx.

When it's closed, the popup is "still" there. 
To hightlight the issue,  you can set the AllowsTransparency to "False" instead of true. (in generic.xaml, line 602)
you will see a black background instead of the transparency one.
When you press "cancel" button (on the add fruit sample by example), you will see that the content is fading properly but that the Popuphost is still there.

![image](https://cloud.githubusercontent.com/assets/7021898/24010109/37c6b9d8-0a77-11e7-9567-a84b4d3d72c1.png)

Thanks

**Comment by Keboo** [comment]
@elvince I am still trying to recreate the issue (without success). Here is what I am seeing:

![output](https://cloud.githubusercontent.com/assets/952248/24034329/25b93ebe-0aae-11e7-8dff-10636e394f2c.gif)

The IsOpened property for the popup is controlled by several storyboards. Perhaps something is happening to prevent those for occurring? Perhaps try wiring up on the Closed event inside of PopupEx to verify that it is firing? (it is being raised for me) Just trying to determine if this is a behavior problem or a rending issue.

**Comment by elvince** [comment]
@Keboo 
thanks for the testing. 

I added the Closed Event and it's not called when I click on cancel. 
The event is called when the page is loaded, also the PopupEx unloaded event. But once the page is fully loaded, the closed is never called.

I try with the latest code & 2.3 code.

I do confirm that with AllowsTransparency=True, the closed event is called.

So we have something weird on this.

FYI I'm on W10 64 bits, Dual Screen, vs2015 update 3 pro, nvidia card with latest drivers.
If that can help to track down the issue.

This is what I did To highlight the closed event call:

` public PopupEx()
        {
            this.Loaded += this.PopupEx_Loaded;
            this.Opened += this.PopupEx_Opened;
            this.Closed += this.PopupEx_Closed;
        }

        private void PopupEx_Closed(object sender, EventArgs e)
        {
            System.Diagnostics.Debug.Write("Closed");
        }`

In my case, when loading the dialog test pages, I can see 4 closed event called.
Then I open the addfruit popup, and click on cancel.
I can see the log : SAMPLE 1: Closing dialog with parameter: False
but closed is never called then.

Any hint on where to look at ? I honnestly don't know where to look for this.

**Comment by Keboo** [comment]
@elvince Here are a few things to try just to try and diagnose which piece is failing.

- Swap out the PopupEx int he DialogHost template for a normal Popup control (there are only a few things that need to be changed in the template for this to compile and run). This will eliminate any of the fancy code in PopupEx from being the cause.
- In the Dialogs.xaml sample add `materialDesign:TransitionAssist.DisableTransitions="True"` to the DialogHost. This will eliminate any of the transition storyboards from interfering. 
- Change the Storyboard in the Closed visual state of the DialogHost template to only contain this key frame `<DiscreteBooleanKeyFrame Value="False" KeyTime="0:0:0" />`. This should make the popup dismiss immediately. I am wondering if perhaps there is an timing issue with the storyboard clock.
- Do you have a second machine that you can try this on? Just wondering if this is specific to your particular computer.
- Also I would be curious if you see this same problem in a plain WPF application without the material design. This might be a bit more difficult to setup since to get an accurate test you will want a custom control template that contains a popup that is dismissed with a storyboard triggered by moving to a particular visual state.

**Comment by elvince** [comment]
Hi
sorry for the late answer.

I did some additional test `materialDesign:TransitionAssist.DisableTransitions="True"` is fixing the issue.

`<DiscreteBooleanKeyFrame Value="False" KeyTime="0:0:0" />` this is not doing anything for the issue.

I found a cause:
in <VisualTransition From="Open" To="Closed"> line 522.
The storyboard is managing the "IsOpen" value. 
First the code is written twice.
Second, it seems to take priority over the closed visual state "IsOpen" value.

I'm not an expert in this area, but as you think there is a timing issue somewhere.

Any idea?

More, are you seeing the black background when the dialog screen is loading. I mean, I have a blink black background for all the dialog host during loading, then the correct screen. 
I'm seing during event in DialogHost, that the dialog are loaded and closing when created. Why aren't they closed from start? They should load as closed and not open they closed. (easy to see it if you log all the "Closed" events in the PopupEx)

**Comment by Keboo** [comment]
Hi @elvince 

Can you give [this branch](https://github.com/Keboo/MaterialDesignInXamlToolkit/tree/popupDiagnostics) a try? 
If you open the dialogs page, and open and close the dialog in Sample 1. I think there is a problem with the timing in the storyboards (and I hope these changes address it). 
For me, this shows the black, with the popup properly dismissing.
![popup](https://cloud.githubusercontent.com/assets/952248/24213225/f35ad32a-0eee-11e7-8f36-c40ebda996ee.gif)

**Comment by elvince** [comment]
HI,

I tried your branch and still have the same behavior. That's weird. 

Here what I get: 
![issue](https://cloud.githubusercontent.com/assets/7021898/24242144/2de3a2a6-0fb7-11e7-92a9-227f18bac51f.gif)

You can see the "non closing issue" and also the weird glitch of all popup when the screen is loading.

Thanks for your support and your time on this!

**Comment by punker76** [comment]
Setting `AllowsTransparency` to false is not a goof option for `Popup`. It's maybe better to use the `AirspaceDecorator` together with the `WindowsFormHost`. This issue is always the same, cause WPF and WinForms have different rendering mechanism.

Here is the FAQ for MahApps: https://github.com/MahApps/MahApps.Metro/wiki/FAQ#why-is-windowsformshost-and-webbrowser-flickering

**Comment by elvince** [comment]
@punker76 
Thanks for the proposal. I did some try with this control. It works partially.
I mean the pdfviewer is shown, but all the overlay to control it is not appearing.

More, once the windowshost have the focus, I can't get out of it.

So, it might not be the solution.

**Comment by Keboo** [comment]
@elvince would you mind trying the branch again? I just pushed another change to it.

Also if you still see the failure, would you try commenting out the individual animations inside the storyboard one at a time? I suspect once you get down to only having the BooleanAnimationUsingKeyFrames it will work, but I am curious if there is a combination that is causing it to fail.

**Comment by punker76** [comment]
@Keboo there are always proplems when setting AllowsTransparency to false of a Popup

- You lose the animation when opening a combo box (slide) or a menu (fade) or Popup
- You lose the shadow.
- If you apply a transform, the popup will not match it

here is a link which I found as I changed some MahApps stuff some years ago, it's about ClearType but also the AllowsTransparency https://arbel.net/2007/02/03/give-me-back-my-cleartype/

**Comment by Keboo** [comment]
@punker76 I understand, and agree that most of the time you do not want to set it to false. However, that does not answer the question of why the Storyboard appears to fail for elvince yet succeed for me. Do you have any insight into what could be causing it?

**Comment by elvince** [comment]
@Keboo 
Yeah the last version is working great. The popup is now fading and closing correctly.

Any clue about the blinking black background during components loading? 
I mean when you load a page with a popup in it, it blinks where the popup is located. We only  see it with the settings to false because the background is black and not transparent.

@punker76 
The goal is not to set if to false by default, but to be able to do it. In my case, I need it in order to put a winformshost in it in order to display PDF.

thanks,

**Comment by Keboo** [comment]
@elvince excellent, I will get the code cleaned up and submit a PR a bit later.

**Comment by Keboo** [comment]
@elvince can you please test the linked PR #665 (and comment on it if it works for you). It should be the same as the ranch I had you test and the initial blinking of the popup should be fixed as well.

**Comment by elvince** [comment]
@Keboo 
Working as expected now. The 2 issues are solved. Good job!

Just need the 2 PRs now to be accepted & merged and we have a full solution!

again thanks for the time you spent on it to dig the storyboard issues.

**Comment by ButchersBoy** [comment]
hey guys...i will review PRs soon...just need a week or two off to recharge my batteries :)

**Comment by Keboo** [comment]
@ButchersBoy  not a problem. I understand; managing OS projects like this can be pretty draining at times.

**Comment by elvince** [comment]
Hi ButchersBoy,

Any idea when you will be able to release the different changes on popup?
including this #665, #657, #658.

Thanks,
