### ISSUE TITLE
ListView horizontal alignment

### ISSUE THREAD

**Issue by NekoSin4eG** [ButchersBoy/MaterialDesignInXamlToolkit#662]
I want to request a function so that the ListView items can have horizontal alignment. If you set the value of the alignment in style, then the material style disappears. Thank you.

P.S. Thank you for your work.

**Comment by Keboo** [comment]
@NekoSin4eG you should already be able to do this. The key is to make sure that your style derives from the material design style by setting the [BasedOn property](https://msdn.microsoft.com/en-us/library/system.windows.style.basedon.aspx). 

Something like this perhaps?

```XAML
<ListView>
    <ListView.ItemContainerStyle>
        <Style TargetType="ListViewItem" BasedOn="{StaticResource {x:Type ListViewItem}}">
            <Setter Property="HorizontalContentAlignment" Value="Right" />
        </Style>
    </ListView.ItemContainerStyle>
    <ListViewItem>
        Hello
    </ListViewItem>
    <ListViewItem>
        World
    </ListViewItem>
    <ListViewItem>
        :)
    </ListViewItem>
</ListView>
```

**Comment by NekoSin4eG** [comment]
@Keboo Exactly! I forgot that I can base the style.

**Comment by timothyparez** [comment]
Actually it should be based on `MaterialDesignGridViewItem` otherwise it might simply   
base itself on the default `ListViewItem` style.

```
<ListView.ItemContainerStyle>
    <Style TargetType="ListViewItem" BasedOn="{StaticResource MaterialDesignGridViewItem}">
        <Setter Property="HorizontalContentAlignment" Value="Right" />
    </Style>
</ListView.ItemContainerStyle>
```
