### ISSUE TITLE
DataGrid cell header Issue

### ISSUE THREAD

**Issue by bluecomb** [ButchersBoy/MaterialDesignInXamlToolkit#666]
Using the library in several of my college projects and frankly, i just fall in love with the provided UI. Recently I have used the library in one of my projects and I defined few columns in a DataGrid user can resize. While resizing the column I noticed that if I tried to drag the resize handle of the cell header it resized the cell weirdly.
Also, I want to suggest to implement a helper behavior for row index in the DataGrid row header.

**Comment by Keboo** [comment]
@bluecomb can you provide a solution the reproduces the problem?

**Comment by ButchersBoy** [comment]
Closing issue until a sample repo is provided.
