### ISSUE TITLE
Hidden caret

### ISSUE THREAD

**Issue by HamedMousavi** [ButchersBoy/MaterialDesignInXamlToolkit#674]
TextBox inside ColorZone with FlowDirection set to RightToLeft and materialDesign:TextFieldAssist.DecorationVisibility="Hidden" will cause caret to disappear. Setting custom caret brush doesn't help.

`<materialDesign:ColorZone Mode="Standard" Padding="1" CornerRadius="2" Panel.ZIndex="1"
                                              Margin="0"
                                              materialDesign:ShadowAssist.ShadowDepth="Depth1">
<TextBox FlowDirection="RightToLeft" Margin="8 0 0 0" materialDesign:HintAssist.Hint="Build a search bar" 
                                 materialDesign:TextFieldAssist.DecorationVisibility="Hidden" BorderThickness="0"
                                 MinWidth="200" VerticalAlignment="Center" />
                    </materialDesign:ColorZone>`

It will hide caret even if the parent control has set the FlowDirection to RTL.

**Comment by HamedMousavi** [comment]
As a matter of fact it doesn't need to be inside a ColorZone. Removing decoration alone will hide the caret.

**Comment by ButchersBoy** [comment]
Hi, you can try tweaking the attached prop `TextFieldAssist.TextBoxViewMargin`.

This property shunts the carat right to the edge of the box, inline with MD standards.  However, in some circumstances WPF seems to calculate the carat width to almost zero.  Have a play, maybe set it to 2, see what happens...

**Comment by HamedMousavi** [comment]
It works. Thank you very much. :-)

Sorry for late response, I didn't get a notification for this. :-/
