### ISSUE TITLE
DialogHost doesn't hide to change Dragablz Tab

### ISSUE THREAD

**Issue by ezekiel911** [ButchersBoy/MaterialDesignInXamlToolkit#676]
DialogHost Doesn't hide to change Tab of Dragablz

I try to show a Dialog Message Waiting as DialogHost in a Tab but I when change to other tab DialogHost Keep showing in MainWindow.

Here is Example.
https://drive.google.com/file/d/0B_RjndxyJNUad1NrcEpoSGd6MTA/view?usp=sharing

I hope that you can help me.

Thank so much.

**Comment by Jakartoine** [comment]
@ButchersBoy, I have exactly the same issue... If you're able to give us an answer, we will appreciate a lot ;-)

I also noticed that a DialogHost is, in fact, brought to the front of all opened windows on the desktop...

Here is two pictures explaining the issue :
![firstscreen](https://cloud.githubusercontent.com/assets/27675999/25085563/3108233e-2363-11e7-98cc-126b9491d156.png)

![bringbacktothefront](https://cloud.githubusercontent.com/assets/27675999/25085562/3106e528-2363-11e7-8bef-084bae8c81b1.png)

**Comment by ButchersBoy** [comment]
Problem is, the dialog is a popup, is effectively a new window.  So if you want to use this technique you should probably bind IsPopupOpen, and you'd have to manage that in your app according to your current tab.
