### ISSUE TITLE
.Net 4.5.1 nuget package support

### ISSUE THREAD

**Issue by farp** [ButchersBoy/MaterialDesignInXamlToolkit#68]
I´m trying to use it in a Windows 8.1 targeted WinRT app using the nuget package but it fails due the original package doesn´t reference .NET 4.5.1

Could you add support to it or tell me if I´m doing something wrong please?

Thanks in advance

**Comment by QuantumDeveloper** [comment]
I heared that MSwill skip support fron all .Net < 4.6 in the next year. so, maybe we should upgrade to 4.6?

**Comment by ButchersBoy** [comment]
WinRT?  There is no WinRT support.  I've made a start on UWP support, but it's early days on that front.

**Comment by ButchersBoy** [comment]
Closing...no intention to support WinRT...UWP is in progress.
