### ISSUE TITLE
DialogHost.Show?

### ISSUE THREAD

**Issue by mummyildiz** [ButchersBoy/MaterialDesignInXamlToolkit#680]
Can we do ShowModal like in DialogHost.Show?

Is Window available in DialogHost.Show?

The portion of code that follows DialogHost.Show or DialogHost.ShowModal
Is it possible to wait until the answer from ShowModal is not working?

Thank you

**Comment by Keboo** [comment]
Hi @mummyildiz 
So the answer is yes, sort of. The DialogHost.Show methods return Task objects so they can be awaited allowing you to have the code that requires the result wait until it is available.

Take a look at the [Dialog sample 3](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Domain/DialogsViewModel.cs#L36) for doing this. 
You might also want to read up on the [async/await](https://msdn.microsoft.com/en-us/library/mt674882.aspx) in C#.

**Comment by mummyildiz** [comment]
thank you.
What do I need to do to prevent the form being opened with DialogHost.Show from closing before the necessary checks are completed.
(Without MVVM)

**Comment by Keboo** [comment]
@mummyildiz I am not entirely sure I understand the question.
The DialogHost.Show methods have several overloads that take a `DialogOpenedEventHandler`. This delegate is invoked just prior to the dialog being closed. It also allows you the Cancel the closing event, and instead manually call close at a later point by calling the Close method on the Session object.
Something like this:
```C#
await DialogHost.Show(content, OnClosing);

private async void OnClosing(object sender, DialogClosingEventArgs e)
{
    e.Cancel();
    await Task.Run(() => {/*Do something here*/});
    e.Session.Close();
}
```

**Comment by mummyildiz** [comment]
Teşekkür ederim.

**Comment by Keboo** [comment]
Rica ederim
