### ISSUE TITLE
PopupBox button demo unexpectedly pops up when mousing over hidden buttons (VS 2017)

### ISSUE THREAD

**Issue by DeleteIT** [ButchersBoy/MaterialDesignInXamlToolkit#681]
![image](https://cloud.githubusercontent.com/assets/6223141/24992449/5f194fb6-2019-11e7-89cf-79a09ff646cb.png)

Green = Expected area to trigger expansion
Red     = Unexpected area for expansion trigger

If you mouse over the PopupBox demo button, it expands with three buttons.

Prior to expansion, if you mouse over where those buttons *will* be, it also expands those three buttons.
Is that the expected behaviour?

The green button to the far right also has the same issue.

Several XAML theme resources make VS 2017's designer encounter exceptions attempting to *find* them, despite being exactly where they're supposed to be, and others in the same folder are fine, not sure if that's related.
Also, any reference in the demo to `MaterialDesignTheme.PopupBox.xaml"` is considered a null value, which *might* be related.

Is this an issue resolved by going back to VS 2015? =/

**Comment by Keboo** [comment]
Hi @DeleteIT this is actually expected.
The PopupBox has a property called [PopupMode](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/PopupBox.cs#L77) that controls when the popup is displayed. What is a little un-intuitive is the [style](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PopupBox.xaml#L155) that is being applied to it sets this property to be MouseOverEager (ie. it opens when the mouse is over the toggle button or the space where the popup would occupy).
You can either change the PopupMode on your control or take a look at some of the [other styles](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PopupBox.xaml) available for the popup box.

**Comment by DeleteIT** [comment]
@Keboo Ah, I can't see the properties menus, since there's exceptions, so I missed that.
