### ISSUE TITLE
Not install

### ISSUE THREAD

**Issue by shahinesi** [ButchersBoy/MaterialDesignInXamlToolkit#684]
im used vs2017 ! this not install!
plz help me
`PM> Install-Package MaterialDesignThemes
  GET https://api.nuget.org/v3/registration1-gz/materialdesignthemes/index.json
  OK https://api.nuget.org/v3/registration1-gz/materialdesignthemes/index.json 276ms
  GET https://api.nuget.org/v3/registration1-gz/materialdesignthemes/page/2.2.0-ci733/2.3.0.823.json
  OK https://api.nuget.org/v3/registration1-gz/materialdesignthemes/page/2.2.0-ci733/2.3.0.823.json 283ms
Restoring packages for C:\Users\shahi\Documents\Visual Studio 2017\Projects\App1\App1\project.json...
  GET https://api.nuget.org/v3-flatcontainer/materialdesignthemes/index.json
  OK https://api.nuget.org/v3-flatcontainer/materialdesignthemes/index.json 645ms
  GET https://api.nuget.org/v3-flatcontainer/materialdesignthemes/2.3.0.823/materialdesignthemes.2.3.0.823.nupkg
  OK https://api.nuget.org/v3-flatcontainer/materialdesignthemes/2.3.0.823/materialdesignthemes.2.3.0.823.nupkg 601ms
  GET https://api.nuget.org/v3-flatcontainer/materialdesigncolors/index.json
  OK https://api.nuget.org/v3-flatcontainer/materialdesigncolors/index.json 677ms
  GET https://api.nuget.org/v3-flatcontainer/materialdesigncolors/1.1.2/materialdesigncolors.1.1.2.nupkg
  OK https://api.nuget.org/v3-flatcontainer/materialdesigncolors/1.1.2/materialdesigncolors.1.1.2.nupkg 599ms
Installing MaterialDesignColors 1.1.2.
Installing MaterialDesignThemes 2.3.0.823.
Install-Package : Package MaterialDesignThemes 2.3.0.823 is not compatible with uap10.0 (UAP,Version=v10.0). Package MaterialDesignThemes 2.3.0.823 supports: net45 (.NETFramework,Version=v4.5)
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package MaterialDesignColors 1.1.2 is not compatible with uap10.0 (UAP,Version=v10.0). Package MaterialDesignColors 1.1.2 supports: net45 (.NETFramework,Version=v4.5)
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more packages are incompatible with UAP,Version=v10.0.
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package MaterialDesignThemes 2.3.0.823 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm. Package MaterialDesignThemes 2.3.0.823 supports: net45 (.NETFramework,Version=v4.5)
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package MaterialDesignColors 1.1.2 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm. Package MaterialDesignColors 1.1.2 supports: net45 (.NETFramework,Version=v4.5)
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more packages are incompatible with UAP,Version=v10.0 (win10-arm).
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package MaterialDesignThemes 2.3.0.823 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm-aot. Package MaterialDesignThemes 2.3.0.823 supports: net45 (.NETFramework,Version=v4.5)
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package MaterialDesignColors 1.1.2 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm-aot. Package MaterialDesignColors 1.1.2 supports: net45 (.NETFramework,Version=v4.5)
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package MaterialDesignThemes 2.3.0.823 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64. Package MaterialDesignThemes 2.3.0.823 supports: net45 (.NETFramework,Version=v4.5)
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package MaterialDesignColors 1.1.2 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64. Package MaterialDesignColors 1.1.2 supports: net45 (.NETFramework,Version=v4.5)
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more packages are incompatible with UAP,Version=v10.0 (win10-x64).
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package MaterialDesignThemes 2.3.0.823 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64-aot. Package MaterialDesignThemes 2.3.0.823 supports: net45 (.NETFramework,Version=v4.5)
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package MaterialDesignColors 1.1.2 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64-aot. Package MaterialDesignColors 1.1.2 supports: net45 (.NETFramework,Version=v4.5)
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package MaterialDesignThemes 2.3.0.823 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86. Package MaterialDesignThemes 2.3.0.823 supports: net45 (.NETFramework,Version=v4.5)
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package MaterialDesignColors 1.1.2 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86. Package MaterialDesignColors 1.1.2 supports: net45 (.NETFramework,Version=v4.5)
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more packages are incompatible with UAP,Version=v10.0 (win10-x86).
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package MaterialDesignThemes 2.3.0.823 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86-aot. Package MaterialDesignThemes 2.3.0.823 supports: net45 (.NETFramework,Version=v4.5)
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package MaterialDesignColors 1.1.2 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86-aot. Package MaterialDesignColors 1.1.2 supports: net45 (.NETFramework,Version=v4.5)
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'App1'.
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:19.6333035`

**Comment by ButchersBoy** [comment]
Currently this only supports WPF
