### ISSUE TITLE
Create winform project and use wpf usercontrol

### ISSUE THREAD

**Issue by ivandgetic** [ButchersBoy/MaterialDesignInXamlToolkit#687]
Recently I found a problem:
Create Winform project and add five references:
PresentationCore,PresentationFramework,System.Xaml,WindowsBase,WindowsFormsIntegration
then add new Item about User Control(WPF) name of UserControl1.xaml
add this content between UserControl

    <UserControl.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.DeepPurple.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Lime.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </UserControl.Resources>

(and also you can add a Button in Grid)
then Bulid this Project , Open Form1.cs [Design] and put UserControl1 into Form1.
Now,We can see a error dialog about "Could not load file or assembly 'MaterialDesignThemes.Wpf'" and this elementHost show nothing.
But bulid this Project and add UserControl1 to Form1 before add UserControl.Resources it will not show this error dialog.It can run no error.
I do not know how to user MaterialDesignInXamlToolkit in User Control(WPF) with WinForm.

**Comment by Keboo** [comment]
Hi @ivandgetic 
I am not much of a WinForms guy, but this appears to be an issue with the WinForm's Visual Studio designer. I would suggest rather than setting the content of the element host in the designer, simply set it in the Form's constructor after the call the initialize component.

**Comment by ivandgetic** [comment]
Finally I put `MaterialDesignColors.dll` and `MaterialDesignThemes.Wpf.dll` into this directory where path is
`C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE`
The problem has been solved.
