### ISSUE TITLE
Unable to set a custom color-palette

### ISSUE THREAD

**Issue by Nickvanklompenburg** [ButchersBoy/MaterialDesignInXamlToolkit#691]
Hello,

First of all thank you for creating such amazing software for me! It has a very nice look and feel!
I'm trying to set a custom color-scheme for my application and run into some problems:
After a discussion on Gitter I figured I'd place a request here.

My App.xaml looks like this:
![im2](https://cloud.githubusercontent.com/assets/27722987/25124870/51686178-242d-11e7-8b15-6836045935a2.png)

In my code I try to replace the color scheme with this:
![im1](https://cloud.githubusercontent.com/assets/27722987/25124880/5bbf0bd6-242d-11e7-8651-f2187385600a.png)

I thought this would be the right way to set swatches and palette's, but I keep getting the folowwing error:
{"PrimaryHueMidBrush is not from standard swatches"}

This error ocurres while loading a user control in my Wpf application, so I think it can't find some resource (In my case a slider)

Any idea how to fix this?

**Comment by Insire** [comment]
I have a working example [here](https://github.com/Insire/MaterialDesignInXamlToolkitTestApp/blob/master/EnterpriseTestApp/App.xaml.cs)

**Comment by Nickvanklompenburg** [comment]
Hi Insire!
This example is working fine, but I found out what the problem really is:
Appearantly somewhere in my program I want to find out what the accent hue is in the current configuration with the "new PaletteHelper().QueryPalette();" but this is not working and then generating the previously mentioned error about the PrimaryHueMidBrush.

Any idea how to set the text foreground color to the primary accent color from code?

**Comment by Keboo** [comment]
Hi @Nickvanklompenburg 
The answer is, it depends on what you are doing. Depending on what styles you are using, most of the "text" controls simply use the inherited Foreground property. In the [example app](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/MainWindow.xaml#L11) this is set to the MaterialDesignBody brush. 

So a few things. The PaletteHelper.QueryPalette method should be working. This is the proper way to get access to the various theme colors. 
Alternatively, if you have access to any FrameworkElement you can always get current brushes by their keys. 
```C#
FrameworkElement element = ...;
var brush = element.TryFindResource("PrimaryHueMidBrush") as Brush;
//Or simply go straight through the application, to retrieve application level resources
var brush = Application.Current.TryFindResource("PrimaryHueMidBrush") as Brush;
```
You can then apply this brush to the Foreground property of your Window (or any Control) with this Brush and your text should update.

**Comment by Nickvanklompenburg** [comment]
Hi @Keboo ,
Thank you for this awnser, this fixed it for me!
