### ISSUE TITLE
Data Grid Paging ??

### ISSUE THREAD

**Issue by mummyildiz** [ButchersBoy/MaterialDesignInXamlToolkit#696]
Can you add a paging feature to the data grid object?

**Comment by ButchersBoy** [comment]
Hi, the ``` DataGrid ``` is a standard WPF control.  This lib merely skins/themes it.  It is down to your client code to manage paging.

**Comment by mummyildiz** [comment]
I wrote to find out if it could be added.
thank you.
But MaterialDesignInXamlToolkit is super.
