### ISSUE TITLE
Can we use it as uwp?

### ISSUE THREAD

**Issue by mummyildiz** [ButchersBoy/MaterialDesignInXamlToolkit#702]
Can we use the toolkit used for wpf in UWP applications as well?

**Comment by Keboo** [comment]
@mummyildiz currently the library only supports WPF.

**Comment by mummyildiz** [comment]
Is there any possibility of using it in the future?

**Comment by Keboo** [comment]
Perhaps at some point, but right now there is a significant amount of work that needs to get done before it will be available on UWP.

**Comment by mummyildiz** [comment]
thank you.
