### ISSUE TITLE
PopupBox is not open if layout is changed

### ISSUE THREAD

**Issue by Sergey-Terekhin** [ButchersBoy/MaterialDesignInXamlToolkit#703]
Hello!
I've encountered bug with PopupBox control:
If it placed on control which layout is changed in runtime (for example, grid's row become visible or hidden), it show content only while layout is unchanged. If it's changed, PopupBox seems to be inactive
Sample repository below:
https://github.com/Sergey-Terekhin/MaterialDesignPopupBoxTest

**Comment by Keboo** [comment]
@ButchersBoy I believe this issue can be closed now.
