### ISSUE TITLE
Spelling mistake in documentation

### ISSUE THREAD

**Issue by BryceBarbara** [ButchersBoy/MaterialDesignInXamlToolkit#705]
The documentation for Transitioner.AutoApplyTransitionOrigins is the following:

> If enabled, **trnaisiotns** origins will be applied to wipes, according to where a transition was triggered from.  For example, the mouse point where a user clicks a button.

**Comment by ButchersBoy** [comment]
Want to raise a PR?

**Comment by BryceBarbara** [comment]
Done. #706

**Comment by Tyrrrz** [comment]
Impressive typo
