### ISSUE TITLE
[Improvement] Color Picker

### ISSUE THREAD

**Issue by Thalhammer** [ButchersBoy/MaterialDesignInXamlToolkit#707]
Maybe I missed it, but I didn't find a Color Picker.
I thought about something like this:
https://s-media-cache-ak0.pinimg.com/originals/1e/a2/c4/1ea2c4436154b784910355f373a08585.png

**Comment by ButchersBoy** [comment]
The demo provides a sample of how to use the palette APIs, but no, a colour picker is not currently in scope for the lib itself.
