### ISSUE TITLE
PasswordTextbox has unsincronized caret position with hint position

### ISSUE THREAD

**Issue by joaomarcosmareto** [ButchersBoy/MaterialDesignInXamlToolkit#718]
When setting padding property in a PasswordBox, the hint and caret positions, become different.
Looking in the source code of the component (PasswordBox.xaml), in the hint section, is possible to see the absence of binding the padding property.

Adding the following code to the SmartHint section 
`Padding="{TemplateBinding Padding}"`
should solve the problem.

Sorry for bad english.

**Comment by Keboo** [comment]
@joaomarcosmareto thank you. I have submitted a PR with the change you suggested.
