### ISSUE TITLE
TimePicker - DateTime instead TimeSpan

### ISSUE THREAD

**Issue by Crsk** [ButchersBoy/MaterialDesignInXamlToolkit#719]
I guess TimePicker should get and return TimeSpan instead DateTime.

So if I've a TimeSpan (14:00:00), to set it to my TimePicker I've to create a DateTime with any date, add my TimeSpan to it and just then I'm ready to go.

**Comment by ButchersBoy** [comment]
This wont change now, as we (mostly) follow SemVer and there is very little gain.  Both types have issues; for example with a TimeSpan client code could set values > 24hours, and again there is granularity which isn't displayed by the control (such as millseconds).
