### ISSUE TITLE
WPF Switches/Toggles/Checkboxes : migrate to Triggers VisualStateManager

### ISSUE THREAD

**Issue by ButchersBoy** [ButchersBoy/MaterialDesignInXamlToolkit#73]
There's a small issue with all the toggles where if they are already checked when the control is loaded the animation is triggered.  I want to only run animations when the control transitions due to a user action.

Moving the animations to visual state manager will sort this out.

**Comment by jfehr** [comment]
The hint animations for comboboxes and textboxes are similarly affected.

**Comment by jfehr** [comment]
Can you assign this one to me?  I have half of it done.

**Comment by ButchersBoy** [comment]
Can't assign...have labelled instead.

**Comment by ButchersBoy** [comment]
...happy to manage the PR on a control by control basis if you have certain controls done.  In fact would rather this, so I can code review it easier.

But thanks!

**Comment by jfehr** [comment]
Will do.

**Comment by ButchersBoy** [comment]
- [ ] MaterialDesignActionToggleButton
- [ ] MaterialDesignCheckBox
- [ ] MaterialDesignUserForegroundCheckBox
- [ ] MaterialDesignFlatToggleButton
- [ ] MaterialDesignSwitchToggleButton
- [ ] MaterialDesignHamburgerToggleButton
- [ ] MaterialDesignComboBox (floating hint, editable)
- [ ] MaterialDesignComboBox (floating hint, non editable)
- [ ] MaterialDesignTextBox (floating hint)

**Comment by ButchersBoy** [comment]
@jdf3 went on a roll and got it all done...

**Comment by jdf3** [comment]
Looks good. Apologies for dragging my feet - had other obligations materialize over the last few weeks and couldn't tidy up any PRs... 😊
