### ISSUE TITLE
Custom title window with Primary etc color

### ISSUE THREAD

**Issue by mariusz695** [ButchersBoy/MaterialDesignInXamlToolkit#759]
Hi, 
can you add or tell me how I can change window title color to another like 'primary indigo' background/foreground etc. Google tell me I can use ' Custom Window Chrome' for change this color and this is one solution.. Maybe is now solution for that with MaterialDesigner ?? 

thanks and sry for my english :)

**Comment by Keboo** [comment]
Hi @mariusz695 

Unfortunately in WPF you only have control over the style of the client area of the window (the area inside of the window chrome). This means that you cannot simply change the color of the title. What you can do is simply remove all of the window chrome (the stuff around the outside of the window) and design your own window template using the [WindowChrome](https://msdn.microsoft.com/en-us/library/system.windows.shell.windowchrome.aspx). 

This will take some work but it totally doable.

Here are some examples and tutorials to get you started.
[Link 1](https://code.msdn.microsoft.com/WPF-styling-a-Window-in-fcf4e4ce)
[Link 2](https://stackoverflow.com/questions/6792275/how-to-create-custom-window-chrome-in-wpf)
[Link 3](https://blog.magnusmontin.net/2013/03/16/how-to-create-a-custom-window-in-wpf/)
[Link 4](https://stackoverflow.com/questions/39882290/custom-wpf-window-style)

**Comment by EdonGashi** [comment]
Mahapps metro provides excellent window customization. I think there's a demo in this repo demonstrates integration with these two libraries.

**Comment by EdonGashi** [comment]
Were you asking about this? Try http://mahapps.com/ and MahAppsDragablzDemo

![md_metro](https://user-images.githubusercontent.com/12145268/28637267-412e48e2-7241-11e7-9c13-855a1791f2bf.png)

**Comment by mariusz695** [comment]
Thanks for all :), yes EdonGashi this is it what I want :).
