### ISSUE TITLE
Possible wrong enqueue handling in SnackBarMessageQueue.cs

### ISSUE THREAD

**Issue by smith1401** [ButchersBoy/MaterialDesignInXamlToolkit#761]
I tried to implement the very nice Snackbar feature in my application and run into problems. I wanted to show the message every time, even if it is the same. It seems that everything, to use this kind of behavior, is implemented but not used.

```
public void Enqueue(object content, bool neverConsiderToBeDuplicate)
        {
            if (content == null) throw new ArgumentNullException(nameof(content));

            _snackbarMessages.AddLast(new SnackbarMessageQueueItem(content));
            _messageWaitingEvent.Set();
        }
```

```
public void Enqueue(object content, object actionContent, Action actionHandler, bool promote)
        {
            if (content == null) throw new ArgumentNullException(nameof(content));

            _snackbarMessages.AddLast(new SnackbarMessageQueueItem(content, actionContent, actionHandler));
            _messageWaitingEvent.Set();
        }
```

In both cases the boolean variables, which to my understanding, are responsible for this kind of behavior  are not used.

**Comment by EdonGashi** [comment]
I have also experienced this bug. I forced duplicates by appending a variable number of \0's at the end of messages, which causes equality tests to fail. A bit hacky, but it won't affect appearance.

**Comment by Keboo** [comment]
This bit me on my project as well. PR submitted with proposed fix.
