### ISSUE TITLE
Calendar blackout dates style bug when in Transitioner

### ISSUE THREAD

**Issue by rrs** [ButchersBoy/MaterialDesignInXamlToolkit#771]
When using a calendar within a transitioner the blacked out dates do not show as faded, they do however show the correct hover icon and cannot be selected.

When navigating forwards then back it resolves itself

When navigating back it is harder to explain and best seen, if the date range is only a couple of days then it will resolve it, if you have used 
`Calendar.BlackoutDates.AddDatesInPast();`
it will still not black out the dates from the current month that should have been, but it will grey out the other dates, so it looks half and half if you where doing it on the 15th for example

demo repo https://github.com/rrs/MaterialDesignCalendarBug

**Comment by Keboo** [comment]
@rss There is a bug fix for issue #605 (appears to potentially be related) that is scheduled to be in the next release. Would you mind testing with the latest code on master to see if this still reproduces?

**Comment by rrs** [comment]
Ah, shame on my issue searching skills, i was focusing on the calendar and transitioner aspect. That does fix it. I'll remember to test with master as a matter of course next time. Thanks

**Comment by Keboo** [comment]
No problem, glad it is fixed :).
