### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by sk8Guerra** [ButchersBoy/MaterialDesignInXamlToolkit#781]
I have just downloaded the material design. I want to compile it to open the .exe; and when I compile it, I get 113 errors. I do not know what it is! is it my visual studio? 

![screenshot 25](https://user-images.githubusercontent.com/18681676/29672771-6898115e-88aa-11e7-885c-47f62ac5708f.png)

**Comment by ButchersBoy** [comment]
You're probably not running VS2017?

Which is required to compile from source.

**Comment by sk8Guerra** [comment]
So much thanks for your answer. That was exacly the problem. I have downloaded VS 2017, and then everything worked fine. :)
