### ISSUE TITLE
.Net 4 Branch not working on VS 2017

### ISSUE THREAD

**Issue by MohanVijayakumar** [ButchersBoy/MaterialDesignInXamlToolkit#782]
Hi ,
I downloaded the .Net 4 branch and compiled in my system and I am able to successfully run the sample applications. 
When I create the new application and reference the material design I stuck with the following situations

1. When I use materialDesign:HintAssist.Hint application is not building and throws the following error
"The property 'HintAssist.Hint' does not exist in XML namespace 'http://materialdesigninxaml.net/winfx/xaml/themes"

2. When I don't use the components causing the building error and only use button then the application is building but goes into break mode shows below info
 "The application is in break mode
 Your app has entered a break state, but there is no code to show because all threads were executing external code (typically system or framework code)."

Previously I was able to successfully create and run the application in following environment
 Windows 7, VS 2012

My current environment 
 Windows 10, VS 2017 15.3.2

Attached the sample app in which I face the issue
Please Help

[md_chk.zip](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/files/1251443/md_chk.zip)

**Comment by MohanVijayakumar** [comment]
Hi ,
The issue is resolved .
The problem is when I copy only DLL files from MaterialDesignColor , Themes and Mahapps I get this error if I reference the DLL along with all files created in the that particular project build then there is no error

**Comment by surapich** [comment]
@MohanVijayakumar  I know what did you meant by "referencing the DLL along with all files created in the that particular project build" ?
I'm stuck with the same problem

**Comment by MohanVijayakumar** [comment]
@surapich reference the dll from project's bin\debug folder or 
copy all the files from debug folder and place somewhere and do the reference from pasted folder
both work for me

**Comment by surapich** [comment]
That didn't work for me actually.
I had to install BCL packages separately worked for me haha, thx btw
