### ISSUE TITLE
For everyone  who want launch MaterialDesignDemo with VS2015Community

### ISSUE THREAD

**Issue by PierreLeGit** [ButchersBoy/MaterialDesignInXamlToolkit#783]
Dear all,

I've intalled VS community 2015 and want to launch the MaterialDesignDemo.
Unfortunately, some errors appeared when built achieved like:
Invalid expression term 'double' in MathMultipleConverter.cs and asignement call in flipper.cs

I've install xunit and shouldly with nuget but already 120errors.
Maybe external content not intalled (dragablz??) 

Hard to find clear information.

Thanks a lot for your help

**Comment by Insire** [comment]
VS2015 is [not supported anymore](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit#-source-code), if you want to compile from source. You can grab the binaries from nuget or the [releases](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/releases) page.

**Comment by Keboo** [comment]
You can also use VS2017 community edition instead.

**Comment by PierreLeGit** [comment]
Right, 
VS2017 for the sources.
VS2015 some controls working.
Thanks a lot.

**Comment by PierreLeGit** [comment]
Project demo runing but Build error and xaml designer doesn't show all xaml contents... error on some pages.

**Comment by ButchersBoy** [comment]
Unfortunately this project can't take responsibility for the XAML designer not working.  It's a Visual Studio problem. The XAML is fine (bar some warnings), the code compiles, the demo runs, and the nuget package installs and works too.

My honest advice is get comfortable hand cranking the XAML, this will make you better in the long run.  95% of the XAML in this lib was hand written.

**Comment by ButchersBoy** [comment]
For clarity, I know it's already been said, but:

You CAN develop with VS2015, so long as you install from Nuget (or pull binaries from Releases page).

Designer errors occur in ALL versions of Visual Studio.
