### ISSUE TITLE
Resources can not be resolved in x64 project

### ISSUE THREAD

**Issue by hadzhiyski** [ButchersBoy/MaterialDesignInXamlToolkit#787]
Hello,

I have a project which is built for x64, but the WPF designer is broken when I use your library. All resources are underlined and I get the text "Static resource can not be resolved". I tried to build MaterialDesignThemes.Wpf and MaterialDesignColors , but the result is the same. If I am using AnyCPU everything is fine with the designer, but I have other dependencies in the project and must be x64. 

Repo with example: https://github.com/hadzhiyski/MaterialDesignXamlDemo64

![Screenshot](https://user-images.githubusercontent.com/20074286/29993803-12d72288-8fca-11e7-92a6-cfd58bfeacac.PNG)

If you have any additional questions, please do not hesitate to ask.

**Comment by ButchersBoy** [comment]
But is it working at runtime?

**Comment by hadzhiyski** [comment]
Yes. The runtime is OK. I am building a quite complex UI and without the designer is like nightmare.

**Comment by punker76** [comment]
This is a problem of the VS designer which doesn't work with x64. Cause the whole UI of VS is 32bit.

**Comment by hadzhiyski** [comment]
Thanks. I guess if I use AnyCPU for designer and x64 for runtime will solve my case.

**Comment by ButchersBoy** [comment]
Sorry...but there's not a lot I can do about this...learn to love the XAML and write smaller views is my advice...

**Comment by hadzhiyski** [comment]
Thanks 👍

**Comment by utherbone** [comment]
Hi, I know it's old, 2017, however I went through it in 2018 and the same now, I recommend creating the interfece using AnyCPU and compiling X64 works for me in the VS 2019 Community Preview. What punker76 said makes all sense.
