### ISSUE TITLE
React Native Linking

### ISSUE THREAD

**Issue by amorenew** [ButchersBoy/MaterialDesignInXamlToolkit#795]
I wonder if you could make your toolkit support React native?
Thanks a lot

**Comment by Keboo** [comment]
@amorenew Perhaps take a look at [Material Design Lite](https://getmdl.io/index.html)?

**Comment by amorenew** [comment]
@Keboo thank you for your answer but react native for mobile
for example
react js text  
<p>hello world</p>
while react native
<Text>hello world</Text>

**Comment by garyng** [comment]
I'm pretty sure that this toolkit spells "XAML" in its name... and it's probably will not be compatible with React Native.

A simple Google Search gives me: 
http://mrn.js.org/  
https://github.com/xinthink/react-native-material-kit  
http://react-native-material-design.github.io/
