### ISSUE TITLE
Make Button Styles more consistent with Guidlines

### ISSUE THREAD

**Issue by stefan-schweiger** [ButchersBoy/MaterialDesignInXamlToolkit#8]
The raised buttons should have a border radius of about 2-3px, also there is no hover effect in the guidlines (so maybe just use a different cursor to indicate the hover)

http://www.google.com/design/spec/components/buttons.html#buttons-flat-raised-buttons

**EDIT:** Polymer is always a good reference point for this kind of stuff

https://www.polymer-project.org/0.5/components/paper-elements/demo.html#paper-button

**Comment by ButchersBoy** [comment]
OK, I'll update the shadows.  As for the hover effect, one could argue there is no guideline for a different cursor either (or a border highlight etc).  Also, I have some people already using it who are happy with the hover.  I will look at creating a method (maybe attached properties) so we provide more options for the visual feedback.

**Comment by ButchersBoy** [comment]
Checked in updated shadows, I'll come back to the other stuff.

**Comment by stefan-schweiger** [comment]
I guess you are right with the hover argument, but as some kind of compromise could you just make add the ripple effect to the background and not also to the text? I think this would make it look much nicer ;)

**Comment by ButchersBoy** [comment]
OK, i'll try shunting it down the z-order and see what it looks like.

**Comment by ButchersBoy** [comment]
Pushed the hover behind the text, good call, looks a bit less dirty.  Also, I softened the effect a little, and made both the hover and the click animation colours based on the foreground text colour, which looks a bit better with white animation on a darker background.
