### ISSUE TITLE
typo on web site

### ISSUE THREAD

**Issue by fabsenet** [ButchersBoy/MaterialDesignInXamlToolkit#800]
hi!

just wanted to let you know, that there is a small type on [the front page](http://materialdesigninxaml.net/):

> To download the source and included demo, vist GitHub

it should be **visit**

I would have provided an easy pull request, but your gh-pages branch does not reflect your website or something 👀

**Comment by ButchersBoy** [comment]
https://github.com/MaterialDesignInXAML/Website

:smile:
