### ISSUE TITLE
TabablzControl TabStripPlacement resets the style to default !

### ISSUE THREAD

**Issue by kushwb** [ButchersBoy/MaterialDesignInXamlToolkit#802]
TabablzControl Style="{StaticResource MaterialDesignAlternateTabablzControlStyle}" TabStripPlacement="Left" doesn't work together and the backgroud still remains the primary color !

**Comment by Keboo** [comment]
@kushwb thanks for opening this issue. As @ButchersBoy indicated the various TabStripPlacement options have not been implemented. 

It appears there is already an [existing issue](https://github.com/ButchersBoy/Dragablz/issues/129) for this feature.

**Comment by ButchersBoy** [comment]
Closing issue as there is the issue in Dragablz repo
