### ISSUE TITLE
Can't inherit styles for more than one inheritence level

### ISSUE THREAD

**Issue by abdelkader27** [ButchersBoy/MaterialDesignInXamlToolkit#825]
Hi, 

I'm trying to create custom style so if I declare a style that inherit from MaterialDesignRaisedButton it's working fine but if I declare a base style based on MaterialDesignRaisedButton and I try to create another style that inherit from my base style I get a warning that the resource MaterialDesignRaisedButton cannot be resolved and the MaterialDesignRaisedButton style is not applied.

here my base style that inherit from MaterialDesignRaisedButton
```
<Style x:Key="BaseButtonStyle" TargetType="{x:Type Button}" BasedOn="{StaticResource MaterialDesignRaisedButton}">
        <Setter Property="FontFamily" Value="{StaticResource FontFamilyName}" />
</Style>
```
and here my custom style that inherit from BaseButtonStyle
```
<Style x:Key="CustomButtonStyle" TargetType="{x:Type Button}" BasedOn="{StaticResource BaseButtonStyle}">
                <Setter Property="VerticalAlignment" Value="Center"/>
                <Setter Property="HorizontalAlignment" Value="Right"/>
                <Setter Property="FontSize" Value="{StaticResource FontButtonSize}"/>
</Style>
```
So is it possible to create a base style that inherit from MaterialDesignRaisedButton and use it as a base style for other styles?

**Comment by brabideau** [comment]
I copied your code into a test app and was able to get both button styles working without trouble. This error should only happen if the base style is defined after the child style, or if the base style isn't linked properly.

Where did you define the button styles? Were they both in the same document?

**Comment by abdelkader27** [comment]
Thank you for your answer.

I checked my code and I'm defining the base style before the child style and they are all defined on the same XAML window.

I attached a sample app where I see the issue. perhaps it's a problem with my environment, I'm using VS 2017 entreprise 15.4.1.

[StyleInheritanceTest.zip](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/files/1441823/StyleInheritanceTest.zip)

**Comment by Keboo** [comment]
Just to be clear, the styles all work at runtime. The issue is with the designer (where the warning occurs).

As a workaround, you can simply set the merged dictionary directly on the style itself, and the designer will be happy again.
```XAML
<Style x:Key="BaseButtonStyle" TargetType="{x:Type Button}" BasedOn="{StaticResource MaterialDesignRaisedButton}">
    <Style.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Button.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Style.Resources>
    <Setter Property="FontFamily" Value="{StaticResource FontFamilyName}" />
</Style>
```

**Comment by abdelkader27** [comment]
Thank you @Keboo. I can see the style applied on the designer now with the mergeddictionaries defined on the base style.
