### ISSUE TITLE
TreeView Style not work

### ISSUE THREAD

**Issue by srvr4vr** [ButchersBoy/MaterialDesignInXamlToolkit#844]
When I use TreeView, the style is still the default WPF style. Whatever I did, everything remains as before. I even copied the entire dictionary with the style, renamed it and applied it manually - it does not work.

**Comment by Keboo** [comment]
@srvr4vr can you post an example repository showing the issue? The [basic tree views](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Trees.xaml) should work.

**Comment by srvr4vr** [comment]
Sorry, I'm just redefined Style.
