### ISSUE TITLE
Demo WPF - Link not working

### ISSUE THREAD

**Issue by Symbai** [ButchersBoy/MaterialDesignInXamlToolkit#848]
In demo WPF under "Dialogs" menu the "Demo View Model" button at the top results in 404 page.

**Comment by wongjiahau** [comment]
@vers-one Do you want to help fix this issue?

**Comment by vers-one** [comment]
@wongjiahau, I believe it has been already fixed in https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/758.
