### ISSUE TITLE
SnackbarMessageQueue do

### ISSUE THREAD

**Issue by malbaladejo** [ButchersBoy/MaterialDesignInXamlToolkit#852]
Hi,

I enqueue several message in SnackbarMessageQueue.
All messages have same content and same actionContent but different actionHandler.
SnackbarMessageQueue consider messages as duplicate and show only the first one.

It would be great to add neverConsiderToBeDuplicate in all methods.

On the other hand, neverConsiderToBeDuplicate is never used in Enqueue(object content, bool neverConsiderToBeDuplicate).

**Comment by Keboo** [comment]
Should be addressed by PR #762

**Comment by malbaladejo** [comment]
Duplicates #761
