### ISSUE TITLE
push nuget ibrary to "MaterialDesignThemes.MahApps"

### ISSUE THREAD

**Issue by tanaka-takayoshi** [ButchersBoy/MaterialDesignInXamlToolkit#86]
This is a great library and now I'm using it.
However it seems only "MaterialDesignThemes.WPF" is pushed to Nuget library.
I'd like to also use "MaterialDesignThemes.MahApps" from nuget.

**Comment by ButchersBoy** [comment]
...yes...this will happen...i want to put something in it first...

Keep the faith :wink:

**Comment by ButchersBoy** [comment]
https://www.nuget.org/packages/MaterialDesignThemes.MahApps
