### ISSUE TITLE
HintOpacity changing Opacity of the object itself

### ISSUE THREAD

**Issue by mrfrostfire** [ButchersBoy/MaterialDesignInXamlToolkit#87]
HintOpacityPropertyChangedCallback in TextFieldAssist changes the Opacity of the object itself which makes not only the hint change opacity, but the entire object, including the regular input text.
Since the hintopacity is already bound in the style, there is no need for a propertychangedcallback and it can be removed completely.

I have tested this on a TextBox and a ComboBox using a slider to change the HintOpacity and it works as expected when the callback is removed.

**Comment by ButchersBoy** [comment]
yeah...not right...

**Comment by ButchersBoy** [comment]
fixed

**Comment by mrfrostfire** [comment]
Thanks! can you update the nuget package?

tis 6 okt. 2015 kl 15:48 skrev James Willock <notifications@github.com>:

**Comment by ButchersBoy** [comment]
It's on CI, provided you are getting the latest pre-release version you'll pick it up.

**Comment by mrfrostfire** [comment]
Found it, We had include prereleases unchecked.

Thanks again.

tis 6 okt. 2015 kl 17:51 skrev James Willock <notifications@github.com>:
