### ISSUE TITLE
Assemblies are not Signed with a Strong Name!

### ISSUE THREAD

**Issue by HesamKashefi** [ButchersBoy/MaterialDesignInXamlToolkit#870]
Hi,
Is there any reason that the assemblies are not strongly named (No public Key Token) ??
We can't reference and use it in our project because of this!

**Comment by Keboo** [comment]
Hi @HesamKashefi 
There is a short [wiki page](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/Strong-Naming) on how you can strong name the assemblies if you need it.

**Comment by HesamKashefi** [comment]
Why did you close this? @ButchersBoy 
I could not solve my problem with the proposed solution... It didn't work for me!
