### ISSUE TITLE
I CANT COMPILE ON 4.0

### ISSUE THREAD

**Issue by zirius666** [ButchersBoy/MaterialDesignInXamlToolkit#90]
The code shows erros on some parts of code when i try to compile with 4.0 .
if i wrong i need download de source code for 4.0 of another repo? thanks

**Comment by ButchersBoy** [comment]
Hi.  There is a net40 branch.  No nuget, you must compile yourself.  Evey so often I update it from master.  See: 

* https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/31
* https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/tree/net40

**Comment by ButchersBoy** [comment]
Please note the net40 branch still requires VS2015 though for C#6 features.

**Comment by zirius666** [comment]
Thanks for help guy
