### ISSUE TITLE
Not displaying keyboard short cuts in menus

### ISSUE THREAD

**Issue by sonyraj** [ButchersBoy/MaterialDesignInXamlToolkit#91]
Menu items are not showing keyboard shortcuts to the right even if it is set through code, is this intentional

**Comment by ButchersBoy** [comment]
OK...

**Comment by punker76** [comment]
@sonyraj @ButchersBoy i've tested the main demo and it seems that there is no issue... ?

<MenuItem Header="_File">
<MenuItem Header="_Edit">

![2015-10-09_21h26_26](https://cloud.githubusercontent.com/assets/658431/10403534/a9e6bde4-6ecc-11e5-8500-4d852993bde8.png)

![2015-10-09_21h26_32](https://cloud.githubusercontent.com/assets/658431/10403539/ac131518-6ecc-11e5-88f8-d7b2e393721d.png)

**Comment by l1pton17** [comment]
@punker76, @sonyraj talks about InputGestureText property of menuitem, which is not working in materialdesign menu.

**Comment by sonyraj** [comment]
The only workaround i've found is to format the menu header a fixed length string and then appending the input gesture text to the end of it. But it still have issues with alignment

**Comment by l1pton17** [comment]
I have fixed this issue, pr will come after fee hours

**Comment by ButchersBoy** [comment]
:+1:

**Comment by sonyraj** [comment]
Great? Do i have to change any thing to make it display shortcuts

**Comment by ButchersBoy** [comment]
Just sit tight and wait for the fix :wink:

**Comment by sonyraj** [comment]
:-)

**Comment by sonyraj** [comment]
Its working Yeah.......... Thanks man @l1pton17
