### ISSUE TITLE
DialogHostEx HideDialog

### ISSUE THREAD

**Issue by olegsavelos** [ButchersBoy/MaterialDesignInXamlToolkit#921]
There is no way to manually hide dialog or at least i cant find one :)
This is required in some cases when dialog should be closed without any user interaction.

**Comment by Keboo** [comment]
@olegsavelos take a look at the [wiki page on dialogs](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/Dialogs#close-dialog-strategies)

**Comment by olegsavelos** [comment]
Totally missed that!
Thanks a lot for response :)

**Comment by Keboo** [comment]
@olegsavelos no problem. I assume this issue can be closed now?

**Comment by olegsavelos** [comment]
Yes :)
