### ISSUE TITLE
Can't find resource MaterialDesignMultiFloatingActionPopupBox

### ISSUE THREAD

**Issue by Symxn** [ButchersBoy/MaterialDesignInXamlToolkit#926]
Hello,

why is this resource not found?
Have you removed it or have it an another name?

`<materialDesign:PopupBox Style="{StaticResource MaterialDesignMultiFloatingActionPopupBox}"></materialDesign:PopupBox>`

I use the latest version of "MaterialDesignThemes" (Version 2.4.0.1044).
I hope you can help.

**Comment by Keboo** [comment]
@Symxn it is still there but it is not one of the default styles you have to include it on the XAML pages where you need it. Just like in the [demo app](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Home.xaml#L13)
