### ISSUE TITLE
Button with OpenDialogCommand and CommandParameter is disabled all the time

### ISSUE THREAD

**Issue by Rainson12** [ButchersBoy/MaterialDesignInXamlToolkit#966]
Im trying to create a simple dialog based on the wpf sample you created:
` <Button Command="{x:Static materialDesign:DialogHost.OpenDialogCommand}"
                                Width="128" Margin="0 32 0 0">
                            <Button.CommandParameter>
                                
                                <system:DateTime>1966-JUL-30</system:DateTime>
                            </Button.CommandParameter>
                            PASS MODEL
                        </Button>`

When using the exact same code the button is always disabled.

**Comment by Rainson12** [comment]
Got it. To get the sample work as stand alone you need to wrap the Button inside a DialogHost:
` <materialDesign:DialogHost Grid.Column="2">

                <Button Command="{x:Static materialDesign:DialogHost.OpenDialogCommand}"   >
                    <Button.CommandParameter>
                        <StackPanel Margin="16">
                            <ProgressBar Style="{DynamicResource MaterialDesignCircularProgressBar}" HorizontalAlignment="Center" Margin="16" IsIndeterminate="True" Value="0" />
                            <Button IsCancel="True" Margin="8 0 0 0" 
                                    Command="{x:Static materialDesign:DialogHost.CloseDialogCommand}" Content="Save" />
                        </StackPanel>
                    </Button.CommandParameter>
                    Edit
                </Button>
            </materialDesign:DialogHost>
`

**Comment by TheoEssoh** [comment]
thank's you help me !!!

**Comment by q913777031** [comment]
thank's you helped me !!!
