### ISSUE TITLE
Question: portabity

### ISSUE THREAD

**Issue by gedw99** [ButchersBoy/MaterialDesignInXamlToolkit#97]
I use polymer for desktop, web, mobile apps.
All are using web components for UI layer.

I used to do wpf and xaml. 
This project looks very well done.

My question:
Can this run on mobile ?
I tried running .net on mac and Linux but its horrible.

**Comment by ButchersBoy** [comment]
No this is WPF so strictly Windows desktop.  A UWP version is in the works, but this will target Windows 10/Windows 10 mobile.

Maybe, just maybe, I will port to Xamarin and this in the future: https://github.com/Perspex/Perspex , which would be cross platform.

But, I probably need someone to sponsor me to get all that done quickly!  :wink:

**Comment by gedw99** [comment]
@ButchersBoy 
Perspex looks very nice. Its nice to see MS / .NET world not being beholden to just Windows OS finally.

Material Design as a GUI style for everything is compelling to me as a developer. I have been doing all mobile apps and web apps with it for a while.
Desktop Material Design will now be possible.

The thing of course is that the developer needs to write in WPF. Easy and nice.
But i wonder if anyone has thought about WPF translated to web ? 

I am just a freelancer, so no big company sponsorship from me i am afraid.

**Comment by SuicSoft** [comment]
@gedw99 Maybe http://papyros.io/developer/index.html might help for cross-platform, although it isn't C#

**Comment by gedw99** [comment]
@SuicSoft Yeah i know that one well its QT / QML based. Its not bad either.
At the moment i am playing with Flutter (ios and android), and polymer (web).
http://flutter.io/
ww.polymer.org

they are both google projects.

But QML and QT is much more expressive i have found. My current fav is this:
https://github.com/go-qml/qml

The examples are astounding, and fast
