### ISSUE TITLE
The tag 'PackIcon' does not exist in XML namespace 'http://materialdesigninxaml.net/winfx/xaml/themes'. Line 46 Position 38.

### ISSUE THREAD

**Issue by pantonis** [ButchersBoy/MaterialDesignInXamlToolkit#974]
I am trying to build on my CI Server and I am getting the following error:

```
 error MC3074: The tag 'PackIcon' does not exist in XML namespace 'http://materialdesigninxaml.net/winfx/xaml/themes'. Line 46 Position 38.
```

**Comment by Keboo** [comment]
@pantonis I would probably need to see the build logs and project to diagnose it. I suspect the issue is likely nuget packages are not being restored prior to the build.

**Comment by pantonis** [comment]
@Keboo I checked. I think you are right. Question is why? All other packages are successfully installed I can see them in the packages folder. I receive no errors or warnings at all during restoration. Please bear in mind that I use PackageReference in my csproj.

**Comment by Keboo** [comment]
@pantonis That is difficult to answer without digging through the project and the CI system. As you pointed out the other nugets appear to work correctly. Typically what I do is a fresh clone (ideally on a clean VM) of my project locally and attempt to run the same commands that the CI system is running. If the error reproduces it is usually easier to debug at that point. If it doesn't reproduce then dig further into the CI system and the logs.

**Comment by pantonis** [comment]
@Keboo You are right. This is not related to the library but indeed to nuget configuration. Switching back to packages.config solved the problem.
I will close this issue since it is not a problem with the library. Thanks for the support
